namespace BTL.GUI.InsertForm {
    partial class isrKhachHang {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing) {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent() {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(isrKhachHang));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuButton21 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.txtSDT = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtDiaChi = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtTenKH = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtMaKH = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtLuotMua = new Bunifu.UI.WinForms.BunifuTextBox();
            this.cbbGhiChu = new Bunifu.UI.WinForms.BunifuDropdown();
            this.SuspendLayout();
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.Font = new System.Drawing.Font("Segoe UI Semibold", 13F, System.Drawing.FontStyle.Bold);
            this.bunifuLabel1.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(79)))), ((int)(((byte)(79)))), ((int)(((byte)(79)))));
            this.bunifuLabel1.Location = new System.Drawing.Point(123, 34);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(181, 30);
            this.bunifuLabel1.TabIndex = 17;
            this.bunifuLabel1.Text = "Thêm Khách Hàng";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuButton21
            // 
            this.bunifuButton21.AllowAnimations = true;
            this.bunifuButton21.AllowMouseEffects = true;
            this.bunifuButton21.AllowToggling = false;
            this.bunifuButton21.AnimationSpeed = 200;
            this.bunifuButton21.AutoGenerateColors = false;
            this.bunifuButton21.AutoRoundBorders = false;
            this.bunifuButton21.AutoSizeLeftIcon = true;
            this.bunifuButton21.AutoSizeRightIcon = true;
            this.bunifuButton21.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton21.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.bunifuButton21.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton21.BackgroundImage")));
            this.bunifuButton21.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton21.ButtonText = "Thêm";
            this.bunifuButton21.ButtonTextMarginLeft = 0;
            this.bunifuButton21.ColorContrastOnClick = 45;
            this.bunifuButton21.ColorContrastOnHover = 45;
            this.bunifuButton21.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.bunifuButton21.CustomizableEdges = borderEdges1;
            this.bunifuButton21.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton21.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton21.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton21.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton21.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.bunifuButton21.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuButton21.ForeColor = System.Drawing.Color.White;
            this.bunifuButton21.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton21.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton21.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButton21.IconMarginLeft = 11;
            this.bunifuButton21.IconPadding = 10;
            this.bunifuButton21.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton21.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton21.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton21.IconSize = 25;
            this.bunifuButton21.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButton21.IdleBorderRadius = 15;
            this.bunifuButton21.IdleBorderThickness = 1;
            this.bunifuButton21.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButton21.IdleIconLeftImage = null;
            this.bunifuButton21.IdleIconRightImage = null;
            this.bunifuButton21.IndicateFocus = false;
            this.bunifuButton21.Location = new System.Drawing.Point(84, 513);
            this.bunifuButton21.Name = "bunifuButton21";
            this.bunifuButton21.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton21.OnDisabledState.BorderRadius = 15;
            this.bunifuButton21.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton21.OnDisabledState.BorderThickness = 1;
            this.bunifuButton21.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton21.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton21.OnDisabledState.IconLeftImage = null;
            this.bunifuButton21.OnDisabledState.IconRightImage = null;
            this.bunifuButton21.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButton21.onHoverState.BorderRadius = 15;
            this.bunifuButton21.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton21.onHoverState.BorderThickness = 1;
            this.bunifuButton21.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButton21.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton21.onHoverState.IconLeftImage = null;
            this.bunifuButton21.onHoverState.IconRightImage = null;
            this.bunifuButton21.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButton21.OnIdleState.BorderRadius = 15;
            this.bunifuButton21.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton21.OnIdleState.BorderThickness = 1;
            this.bunifuButton21.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButton21.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton21.OnIdleState.IconLeftImage = null;
            this.bunifuButton21.OnIdleState.IconRightImage = null;
            this.bunifuButton21.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton21.OnPressedState.BorderRadius = 15;
            this.bunifuButton21.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton21.OnPressedState.BorderThickness = 1;
            this.bunifuButton21.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton21.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton21.OnPressedState.IconLeftImage = null;
            this.bunifuButton21.OnPressedState.IconRightImage = null;
            this.bunifuButton21.Size = new System.Drawing.Size(260, 44);
            this.bunifuButton21.TabIndex = 16;
            this.bunifuButton21.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButton21.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton21.TextMarginLeft = 0;
            this.bunifuButton21.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButton21.UseDefaultRadiusAndThickness = true;
            this.bunifuButton21.Click += new System.EventHandler(this.bunifuButton21_Click);
            // 
            // txtSDT
            // 
            this.txtSDT.AcceptsReturn = false;
            this.txtSDT.AcceptsTab = false;
            this.txtSDT.AnimationSpeed = 200;
            this.txtSDT.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtSDT.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtSDT.AutoSizeHeight = true;
            this.txtSDT.BackColor = System.Drawing.Color.White;
            this.txtSDT.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtSDT.BackgroundImage")));
            this.txtSDT.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtSDT.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtSDT.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtSDT.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtSDT.BorderRadius = 10;
            this.txtSDT.BorderThickness = 1;
            this.txtSDT.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtSDT.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSDT.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtSDT.DefaultText = "";
            this.txtSDT.FillColor = System.Drawing.Color.White;
            this.txtSDT.HideSelection = true;
            this.txtSDT.IconLeft = null;
            this.txtSDT.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSDT.IconPadding = 10;
            this.txtSDT.IconRight = null;
            this.txtSDT.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSDT.Lines = new string[0];
            this.txtSDT.Location = new System.Drawing.Point(84, 237);
            this.txtSDT.MaxLength = 32767;
            this.txtSDT.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtSDT.Modified = false;
            this.txtSDT.Multiline = false;
            this.txtSDT.Name = "txtSDT";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtSDT.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtSDT.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtSDT.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtSDT.OnIdleState = stateProperties4;
            this.txtSDT.Padding = new System.Windows.Forms.Padding(3);
            this.txtSDT.PasswordChar = '\0';
            this.txtSDT.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtSDT.PlaceholderText = "SDT";
            this.txtSDT.ReadOnly = false;
            this.txtSDT.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtSDT.SelectedText = "";
            this.txtSDT.SelectionLength = 0;
            this.txtSDT.SelectionStart = 0;
            this.txtSDT.ShortcutsEnabled = true;
            this.txtSDT.Size = new System.Drawing.Size(260, 43);
            this.txtSDT.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtSDT.TabIndex = 13;
            this.txtSDT.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtSDT.TextMarginBottom = 0;
            this.txtSDT.TextMarginLeft = 3;
            this.txtSDT.TextMarginTop = 1;
            this.txtSDT.TextPlaceholder = "SDT";
            this.txtSDT.UseSystemPasswordChar = false;
            this.txtSDT.WordWrap = true;
            // 
            // txtDiaChi
            // 
            this.txtDiaChi.AcceptsReturn = false;
            this.txtDiaChi.AcceptsTab = false;
            this.txtDiaChi.AnimationSpeed = 200;
            this.txtDiaChi.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtDiaChi.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtDiaChi.AutoSizeHeight = true;
            this.txtDiaChi.BackColor = System.Drawing.Color.White;
            this.txtDiaChi.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtDiaChi.BackgroundImage")));
            this.txtDiaChi.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtDiaChi.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtDiaChi.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtDiaChi.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtDiaChi.BorderRadius = 10;
            this.txtDiaChi.BorderThickness = 1;
            this.txtDiaChi.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtDiaChi.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDiaChi.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtDiaChi.DefaultText = "";
            this.txtDiaChi.FillColor = System.Drawing.Color.White;
            this.txtDiaChi.HideSelection = true;
            this.txtDiaChi.IconLeft = null;
            this.txtDiaChi.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDiaChi.IconPadding = 10;
            this.txtDiaChi.IconRight = null;
            this.txtDiaChi.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDiaChi.Lines = new string[0];
            this.txtDiaChi.Location = new System.Drawing.Point(84, 308);
            this.txtDiaChi.MaxLength = 32767;
            this.txtDiaChi.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtDiaChi.Modified = false;
            this.txtDiaChi.Multiline = false;
            this.txtDiaChi.Name = "txtDiaChi";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDiaChi.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtDiaChi.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDiaChi.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDiaChi.OnIdleState = stateProperties8;
            this.txtDiaChi.Padding = new System.Windows.Forms.Padding(3);
            this.txtDiaChi.PasswordChar = '\0';
            this.txtDiaChi.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtDiaChi.PlaceholderText = "Địa chỉ";
            this.txtDiaChi.ReadOnly = false;
            this.txtDiaChi.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtDiaChi.SelectedText = "";
            this.txtDiaChi.SelectionLength = 0;
            this.txtDiaChi.SelectionStart = 0;
            this.txtDiaChi.ShortcutsEnabled = true;
            this.txtDiaChi.Size = new System.Drawing.Size(260, 43);
            this.txtDiaChi.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtDiaChi.TabIndex = 12;
            this.txtDiaChi.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtDiaChi.TextMarginBottom = 0;
            this.txtDiaChi.TextMarginLeft = 3;
            this.txtDiaChi.TextMarginTop = 1;
            this.txtDiaChi.TextPlaceholder = "Địa chỉ";
            this.txtDiaChi.UseSystemPasswordChar = false;
            this.txtDiaChi.WordWrap = true;
            // 
            // txtTenKH
            // 
            this.txtTenKH.AcceptsReturn = false;
            this.txtTenKH.AcceptsTab = false;
            this.txtTenKH.AnimationSpeed = 200;
            this.txtTenKH.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtTenKH.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtTenKH.AutoSizeHeight = true;
            this.txtTenKH.BackColor = System.Drawing.Color.White;
            this.txtTenKH.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtTenKH.BackgroundImage")));
            this.txtTenKH.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtTenKH.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtTenKH.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtTenKH.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtTenKH.BorderRadius = 10;
            this.txtTenKH.BorderThickness = 1;
            this.txtTenKH.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtTenKH.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtTenKH.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtTenKH.DefaultText = "";
            this.txtTenKH.FillColor = System.Drawing.Color.White;
            this.txtTenKH.HideSelection = true;
            this.txtTenKH.IconLeft = null;
            this.txtTenKH.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtTenKH.IconPadding = 10;
            this.txtTenKH.IconRight = null;
            this.txtTenKH.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtTenKH.Lines = new string[0];
            this.txtTenKH.Location = new System.Drawing.Point(84, 165);
            this.txtTenKH.MaxLength = 32767;
            this.txtTenKH.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtTenKH.Modified = false;
            this.txtTenKH.Multiline = false;
            this.txtTenKH.Name = "txtTenKH";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtTenKH.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtTenKH.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtTenKH.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtTenKH.OnIdleState = stateProperties12;
            this.txtTenKH.Padding = new System.Windows.Forms.Padding(3);
            this.txtTenKH.PasswordChar = '\0';
            this.txtTenKH.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtTenKH.PlaceholderText = "Tên khách hàng";
            this.txtTenKH.ReadOnly = false;
            this.txtTenKH.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtTenKH.SelectedText = "";
            this.txtTenKH.SelectionLength = 0;
            this.txtTenKH.SelectionStart = 0;
            this.txtTenKH.ShortcutsEnabled = true;
            this.txtTenKH.Size = new System.Drawing.Size(260, 43);
            this.txtTenKH.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtTenKH.TabIndex = 11;
            this.txtTenKH.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtTenKH.TextMarginBottom = 0;
            this.txtTenKH.TextMarginLeft = 3;
            this.txtTenKH.TextMarginTop = 1;
            this.txtTenKH.TextPlaceholder = "Tên khách hàng";
            this.txtTenKH.UseSystemPasswordChar = false;
            this.txtTenKH.WordWrap = true;
            // 
            // txtMaKH
            // 
            this.txtMaKH.AcceptsReturn = false;
            this.txtMaKH.AcceptsTab = false;
            this.txtMaKH.AnimationSpeed = 200;
            this.txtMaKH.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtMaKH.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtMaKH.AutoSizeHeight = true;
            this.txtMaKH.BackColor = System.Drawing.Color.White;
            this.txtMaKH.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtMaKH.BackgroundImage")));
            this.txtMaKH.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtMaKH.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtMaKH.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtMaKH.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtMaKH.BorderRadius = 10;
            this.txtMaKH.BorderThickness = 1;
            this.txtMaKH.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtMaKH.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtMaKH.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtMaKH.DefaultText = "";
            this.txtMaKH.FillColor = System.Drawing.Color.White;
            this.txtMaKH.HideSelection = true;
            this.txtMaKH.IconLeft = null;
            this.txtMaKH.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtMaKH.IconPadding = 10;
            this.txtMaKH.IconRight = null;
            this.txtMaKH.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtMaKH.Lines = new string[0];
            this.txtMaKH.Location = new System.Drawing.Point(84, 96);
            this.txtMaKH.MaxLength = 32767;
            this.txtMaKH.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtMaKH.Modified = false;
            this.txtMaKH.Multiline = false;
            this.txtMaKH.Name = "txtMaKH";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtMaKH.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtMaKH.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtMaKH.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtMaKH.OnIdleState = stateProperties16;
            this.txtMaKH.Padding = new System.Windows.Forms.Padding(3);
            this.txtMaKH.PasswordChar = '\0';
            this.txtMaKH.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtMaKH.PlaceholderText = "Mã khách hàng";
            this.txtMaKH.ReadOnly = false;
            this.txtMaKH.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtMaKH.SelectedText = "";
            this.txtMaKH.SelectionLength = 0;
            this.txtMaKH.SelectionStart = 0;
            this.txtMaKH.ShortcutsEnabled = true;
            this.txtMaKH.Size = new System.Drawing.Size(260, 43);
            this.txtMaKH.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtMaKH.TabIndex = 10;
            this.txtMaKH.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtMaKH.TextMarginBottom = 0;
            this.txtMaKH.TextMarginLeft = 3;
            this.txtMaKH.TextMarginTop = 1;
            this.txtMaKH.TextPlaceholder = "Mã khách hàng";
            this.txtMaKH.UseSystemPasswordChar = false;
            this.txtMaKH.WordWrap = true;
            // 
            // txtLuotMua
            // 
            this.txtLuotMua.AcceptsReturn = false;
            this.txtLuotMua.AcceptsTab = false;
            this.txtLuotMua.AnimationSpeed = 200;
            this.txtLuotMua.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtLuotMua.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtLuotMua.AutoSizeHeight = true;
            this.txtLuotMua.BackColor = System.Drawing.Color.White;
            this.txtLuotMua.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtLuotMua.BackgroundImage")));
            this.txtLuotMua.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtLuotMua.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtLuotMua.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtLuotMua.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtLuotMua.BorderRadius = 10;
            this.txtLuotMua.BorderThickness = 1;
            this.txtLuotMua.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtLuotMua.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtLuotMua.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtLuotMua.DefaultText = "";
            this.txtLuotMua.FillColor = System.Drawing.Color.White;
            this.txtLuotMua.HideSelection = true;
            this.txtLuotMua.IconLeft = null;
            this.txtLuotMua.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtLuotMua.IconPadding = 10;
            this.txtLuotMua.IconRight = null;
            this.txtLuotMua.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtLuotMua.Lines = new string[0];
            this.txtLuotMua.Location = new System.Drawing.Point(84, 376);
            this.txtLuotMua.MaxLength = 32767;
            this.txtLuotMua.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtLuotMua.Modified = false;
            this.txtLuotMua.Multiline = false;
            this.txtLuotMua.Name = "txtLuotMua";
            stateProperties17.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtLuotMua.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtLuotMua.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtLuotMua.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Silver;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtLuotMua.OnIdleState = stateProperties20;
            this.txtLuotMua.Padding = new System.Windows.Forms.Padding(3);
            this.txtLuotMua.PasswordChar = '\0';
            this.txtLuotMua.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtLuotMua.PlaceholderText = "Lượt mua";
            this.txtLuotMua.ReadOnly = false;
            this.txtLuotMua.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtLuotMua.SelectedText = "";
            this.txtLuotMua.SelectionLength = 0;
            this.txtLuotMua.SelectionStart = 0;
            this.txtLuotMua.ShortcutsEnabled = true;
            this.txtLuotMua.Size = new System.Drawing.Size(260, 43);
            this.txtLuotMua.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtLuotMua.TabIndex = 19;
            this.txtLuotMua.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtLuotMua.TextMarginBottom = 0;
            this.txtLuotMua.TextMarginLeft = 3;
            this.txtLuotMua.TextMarginTop = 1;
            this.txtLuotMua.TextPlaceholder = "Lượt mua";
            this.txtLuotMua.UseSystemPasswordChar = false;
            this.txtLuotMua.WordWrap = true;
            // 
            // cbbGhiChu
            // 
            this.cbbGhiChu.BackColor = System.Drawing.Color.Transparent;
            this.cbbGhiChu.BackgroundColor = System.Drawing.Color.White;
            this.cbbGhiChu.BorderColor = System.Drawing.Color.Silver;
            this.cbbGhiChu.BorderRadius = 1;
            this.cbbGhiChu.Color = System.Drawing.Color.Silver;
            this.cbbGhiChu.Direction = Bunifu.UI.WinForms.BunifuDropdown.Directions.Down;
            this.cbbGhiChu.DisabledBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.cbbGhiChu.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.cbbGhiChu.DisabledColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.cbbGhiChu.DisabledForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            this.cbbGhiChu.DisabledIndicatorColor = System.Drawing.Color.DarkGray;
            this.cbbGhiChu.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.cbbGhiChu.DropdownBorderThickness = Bunifu.UI.WinForms.BunifuDropdown.BorderThickness.Thin;
            this.cbbGhiChu.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cbbGhiChu.DropDownTextAlign = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.cbbGhiChu.FillDropDown = true;
            this.cbbGhiChu.FillIndicator = false;
            this.cbbGhiChu.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.cbbGhiChu.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.cbbGhiChu.ForeColor = System.Drawing.Color.Black;
            this.cbbGhiChu.FormattingEnabled = true;
            this.cbbGhiChu.Icon = null;
            this.cbbGhiChu.IndicatorAlignment = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.cbbGhiChu.IndicatorColor = System.Drawing.Color.DarkGray;
            this.cbbGhiChu.IndicatorLocation = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.cbbGhiChu.IndicatorThickness = 2;
            this.cbbGhiChu.IsDropdownOpened = false;
            this.cbbGhiChu.ItemBackColor = System.Drawing.Color.White;
            this.cbbGhiChu.ItemBorderColor = System.Drawing.Color.White;
            this.cbbGhiChu.ItemForeColor = System.Drawing.Color.Black;
            this.cbbGhiChu.ItemHeight = 36;
            this.cbbGhiChu.ItemHighLightColor = System.Drawing.Color.DodgerBlue;
            this.cbbGhiChu.ItemHighLightForeColor = System.Drawing.Color.White;
            this.cbbGhiChu.ItemTopMargin = 3;
            this.cbbGhiChu.Location = new System.Drawing.Point(84, 444);
            this.cbbGhiChu.Name = "cbbGhiChu";
            this.cbbGhiChu.Size = new System.Drawing.Size(260, 42);
            this.cbbGhiChu.TabIndex = 20;
            this.cbbGhiChu.Text = "Ghi Chú";
            this.cbbGhiChu.TextAlignment = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.cbbGhiChu.TextLeftMargin = 5;
            // 
            // isrKhachHang
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.White;
            this.ClientSize = new System.Drawing.Size(429, 592);
            this.Controls.Add(this.cbbGhiChu);
            this.Controls.Add(this.txtLuotMua);
            this.Controls.Add(this.bunifuLabel1);
            this.Controls.Add(this.bunifuButton21);
            this.Controls.Add(this.txtSDT);
            this.Controls.Add(this.txtDiaChi);
            this.Controls.Add(this.txtTenKH);
            this.Controls.Add(this.txtMaKH);
            this.Name = "isrKhachHang";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "isrKhachHang";
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 bunifuButton21;
        private Bunifu.UI.WinForms.BunifuTextBox txtSDT;
        private Bunifu.UI.WinForms.BunifuTextBox txtDiaChi;
        private Bunifu.UI.WinForms.BunifuTextBox txtTenKH;
        private Bunifu.UI.WinForms.BunifuTextBox txtMaKH;
        private Bunifu.UI.WinForms.BunifuTextBox txtLuotMua;
        private Bunifu.UI.WinForms.BunifuDropdown cbbGhiChu;
    }
}