namespace BTL.GUI.InsertForm {
    partial class isrNhanVien {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing) {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent() {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(isrNhanVien));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.nhanvienBtnAdd = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.txtSDT = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtDiaChi = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtTenNhanVien = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtMaNhanVien = new Bunifu.UI.WinForms.BunifuTextBox();
            this.nhanvienBtnUpdate = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.SuspendLayout();
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.Font = new System.Drawing.Font("Segoe UI Semibold", 13F, System.Drawing.FontStyle.Bold);
            this.bunifuLabel1.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(79)))), ((int)(((byte)(79)))), ((int)(((byte)(79)))));
            this.bunifuLabel1.Location = new System.Drawing.Point(156, 60);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(105, 30);
            this.bunifuLabel1.TabIndex = 17;
            this.bunifuLabel1.Text = "Nhân Viên";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // nhanvienBtnAdd
            // 
            this.nhanvienBtnAdd.AllowAnimations = true;
            this.nhanvienBtnAdd.AllowMouseEffects = true;
            this.nhanvienBtnAdd.AllowToggling = false;
            this.nhanvienBtnAdd.AnimationSpeed = 200;
            this.nhanvienBtnAdd.AutoGenerateColors = false;
            this.nhanvienBtnAdd.AutoRoundBorders = false;
            this.nhanvienBtnAdd.AutoSizeLeftIcon = true;
            this.nhanvienBtnAdd.AutoSizeRightIcon = true;
            this.nhanvienBtnAdd.BackColor = System.Drawing.Color.Transparent;
            this.nhanvienBtnAdd.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.nhanvienBtnAdd.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("nhanvienBtnAdd.BackgroundImage")));
            this.nhanvienBtnAdd.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.nhanvienBtnAdd.ButtonText = "Thêm";
            this.nhanvienBtnAdd.ButtonTextMarginLeft = 0;
            this.nhanvienBtnAdd.ColorContrastOnClick = 45;
            this.nhanvienBtnAdd.ColorContrastOnHover = 45;
            this.nhanvienBtnAdd.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.nhanvienBtnAdd.CustomizableEdges = borderEdges1;
            this.nhanvienBtnAdd.DialogResult = System.Windows.Forms.DialogResult.None;
            this.nhanvienBtnAdd.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.nhanvienBtnAdd.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.nhanvienBtnAdd.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.nhanvienBtnAdd.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.nhanvienBtnAdd.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.nhanvienBtnAdd.ForeColor = System.Drawing.Color.White;
            this.nhanvienBtnAdd.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.nhanvienBtnAdd.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.nhanvienBtnAdd.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.nhanvienBtnAdd.IconMarginLeft = 11;
            this.nhanvienBtnAdd.IconPadding = 10;
            this.nhanvienBtnAdd.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.nhanvienBtnAdd.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.nhanvienBtnAdd.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.nhanvienBtnAdd.IconSize = 25;
            this.nhanvienBtnAdd.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.nhanvienBtnAdd.IdleBorderRadius = 15;
            this.nhanvienBtnAdd.IdleBorderThickness = 1;
            this.nhanvienBtnAdd.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.nhanvienBtnAdd.IdleIconLeftImage = null;
            this.nhanvienBtnAdd.IdleIconRightImage = null;
            this.nhanvienBtnAdd.IndicateFocus = false;
            this.nhanvienBtnAdd.Location = new System.Drawing.Point(236, 438);
            this.nhanvienBtnAdd.Name = "nhanvienBtnAdd";
            this.nhanvienBtnAdd.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.nhanvienBtnAdd.OnDisabledState.BorderRadius = 15;
            this.nhanvienBtnAdd.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.nhanvienBtnAdd.OnDisabledState.BorderThickness = 1;
            this.nhanvienBtnAdd.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.nhanvienBtnAdd.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.nhanvienBtnAdd.OnDisabledState.IconLeftImage = null;
            this.nhanvienBtnAdd.OnDisabledState.IconRightImage = null;
            this.nhanvienBtnAdd.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.nhanvienBtnAdd.onHoverState.BorderRadius = 15;
            this.nhanvienBtnAdd.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.nhanvienBtnAdd.onHoverState.BorderThickness = 1;
            this.nhanvienBtnAdd.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.nhanvienBtnAdd.onHoverState.ForeColor = System.Drawing.Color.White;
            this.nhanvienBtnAdd.onHoverState.IconLeftImage = null;
            this.nhanvienBtnAdd.onHoverState.IconRightImage = null;
            this.nhanvienBtnAdd.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.nhanvienBtnAdd.OnIdleState.BorderRadius = 15;
            this.nhanvienBtnAdd.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.nhanvienBtnAdd.OnIdleState.BorderThickness = 1;
            this.nhanvienBtnAdd.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.nhanvienBtnAdd.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.nhanvienBtnAdd.OnIdleState.IconLeftImage = null;
            this.nhanvienBtnAdd.OnIdleState.IconRightImage = null;
            this.nhanvienBtnAdd.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.nhanvienBtnAdd.OnPressedState.BorderRadius = 15;
            this.nhanvienBtnAdd.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.nhanvienBtnAdd.OnPressedState.BorderThickness = 1;
            this.nhanvienBtnAdd.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.nhanvienBtnAdd.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.nhanvienBtnAdd.OnPressedState.IconLeftImage = null;
            this.nhanvienBtnAdd.OnPressedState.IconRightImage = null;
            this.nhanvienBtnAdd.Size = new System.Drawing.Size(117, 44);
            this.nhanvienBtnAdd.TabIndex = 16;
            this.nhanvienBtnAdd.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.nhanvienBtnAdd.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.nhanvienBtnAdd.TextMarginLeft = 0;
            this.nhanvienBtnAdd.TextPadding = new System.Windows.Forms.Padding(0);
            this.nhanvienBtnAdd.UseDefaultRadiusAndThickness = true;
            this.nhanvienBtnAdd.Click += new System.EventHandler(this.bunifuButton21_Click);
            // 
            // txtSDT
            // 
            this.txtSDT.AcceptsReturn = false;
            this.txtSDT.AcceptsTab = false;
            this.txtSDT.AnimationSpeed = 200;
            this.txtSDT.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtSDT.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtSDT.AutoSizeHeight = true;
            this.txtSDT.BackColor = System.Drawing.Color.White;
            this.txtSDT.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtSDT.BackgroundImage")));
            this.txtSDT.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtSDT.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtSDT.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtSDT.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtSDT.BorderRadius = 10;
            this.txtSDT.BorderThickness = 1;
            this.txtSDT.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtSDT.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSDT.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtSDT.DefaultText = "";
            this.txtSDT.FillColor = System.Drawing.Color.White;
            this.txtSDT.HideSelection = true;
            this.txtSDT.IconLeft = null;
            this.txtSDT.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSDT.IconPadding = 10;
            this.txtSDT.IconRight = null;
            this.txtSDT.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSDT.Lines = new string[0];
            this.txtSDT.Location = new System.Drawing.Point(93, 282);
            this.txtSDT.MaxLength = 32767;
            this.txtSDT.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtSDT.Modified = false;
            this.txtSDT.Multiline = false;
            this.txtSDT.Name = "txtSDT";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtSDT.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtSDT.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtSDT.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtSDT.OnIdleState = stateProperties4;
            this.txtSDT.Padding = new System.Windows.Forms.Padding(3);
            this.txtSDT.PasswordChar = '\0';
            this.txtSDT.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtSDT.PlaceholderText = "SDT";
            this.txtSDT.ReadOnly = false;
            this.txtSDT.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtSDT.SelectedText = "";
            this.txtSDT.SelectionLength = 0;
            this.txtSDT.SelectionStart = 0;
            this.txtSDT.ShortcutsEnabled = true;
            this.txtSDT.Size = new System.Drawing.Size(260, 43);
            this.txtSDT.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtSDT.TabIndex = 13;
            this.txtSDT.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtSDT.TextMarginBottom = 0;
            this.txtSDT.TextMarginLeft = 3;
            this.txtSDT.TextMarginTop = 1;
            this.txtSDT.TextPlaceholder = "SDT";
            this.txtSDT.UseSystemPasswordChar = false;
            this.txtSDT.WordWrap = true;
            // 
            // txtDiaChi
            // 
            this.txtDiaChi.AcceptsReturn = false;
            this.txtDiaChi.AcceptsTab = false;
            this.txtDiaChi.AnimationSpeed = 200;
            this.txtDiaChi.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtDiaChi.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtDiaChi.AutoSizeHeight = true;
            this.txtDiaChi.BackColor = System.Drawing.Color.White;
            this.txtDiaChi.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtDiaChi.BackgroundImage")));
            this.txtDiaChi.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtDiaChi.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtDiaChi.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtDiaChi.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtDiaChi.BorderRadius = 10;
            this.txtDiaChi.BorderThickness = 1;
            this.txtDiaChi.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtDiaChi.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDiaChi.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtDiaChi.DefaultText = "";
            this.txtDiaChi.FillColor = System.Drawing.Color.White;
            this.txtDiaChi.HideSelection = true;
            this.txtDiaChi.IconLeft = null;
            this.txtDiaChi.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDiaChi.IconPadding = 10;
            this.txtDiaChi.IconRight = null;
            this.txtDiaChi.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDiaChi.Lines = new string[0];
            this.txtDiaChi.Location = new System.Drawing.Point(93, 353);
            this.txtDiaChi.MaxLength = 32767;
            this.txtDiaChi.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtDiaChi.Modified = false;
            this.txtDiaChi.Multiline = false;
            this.txtDiaChi.Name = "txtDiaChi";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDiaChi.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtDiaChi.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDiaChi.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDiaChi.OnIdleState = stateProperties8;
            this.txtDiaChi.Padding = new System.Windows.Forms.Padding(3);
            this.txtDiaChi.PasswordChar = '\0';
            this.txtDiaChi.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtDiaChi.PlaceholderText = "Địa chỉ";
            this.txtDiaChi.ReadOnly = false;
            this.txtDiaChi.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtDiaChi.SelectedText = "";
            this.txtDiaChi.SelectionLength = 0;
            this.txtDiaChi.SelectionStart = 0;
            this.txtDiaChi.ShortcutsEnabled = true;
            this.txtDiaChi.Size = new System.Drawing.Size(260, 43);
            this.txtDiaChi.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtDiaChi.TabIndex = 12;
            this.txtDiaChi.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtDiaChi.TextMarginBottom = 0;
            this.txtDiaChi.TextMarginLeft = 3;
            this.txtDiaChi.TextMarginTop = 1;
            this.txtDiaChi.TextPlaceholder = "Địa chỉ";
            this.txtDiaChi.UseSystemPasswordChar = false;
            this.txtDiaChi.WordWrap = true;
            // 
            // txtTenNhanVien
            // 
            this.txtTenNhanVien.AcceptsReturn = false;
            this.txtTenNhanVien.AcceptsTab = false;
            this.txtTenNhanVien.AnimationSpeed = 200;
            this.txtTenNhanVien.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtTenNhanVien.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtTenNhanVien.AutoSizeHeight = true;
            this.txtTenNhanVien.BackColor = System.Drawing.Color.White;
            this.txtTenNhanVien.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtTenNhanVien.BackgroundImage")));
            this.txtTenNhanVien.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtTenNhanVien.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtTenNhanVien.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtTenNhanVien.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtTenNhanVien.BorderRadius = 10;
            this.txtTenNhanVien.BorderThickness = 1;
            this.txtTenNhanVien.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtTenNhanVien.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtTenNhanVien.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtTenNhanVien.DefaultText = "";
            this.txtTenNhanVien.FillColor = System.Drawing.Color.White;
            this.txtTenNhanVien.HideSelection = true;
            this.txtTenNhanVien.IconLeft = null;
            this.txtTenNhanVien.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtTenNhanVien.IconPadding = 10;
            this.txtTenNhanVien.IconRight = null;
            this.txtTenNhanVien.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtTenNhanVien.Lines = new string[0];
            this.txtTenNhanVien.Location = new System.Drawing.Point(93, 210);
            this.txtTenNhanVien.MaxLength = 32767;
            this.txtTenNhanVien.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtTenNhanVien.Modified = false;
            this.txtTenNhanVien.Multiline = false;
            this.txtTenNhanVien.Name = "txtTenNhanVien";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtTenNhanVien.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtTenNhanVien.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtTenNhanVien.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtTenNhanVien.OnIdleState = stateProperties12;
            this.txtTenNhanVien.Padding = new System.Windows.Forms.Padding(3);
            this.txtTenNhanVien.PasswordChar = '\0';
            this.txtTenNhanVien.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtTenNhanVien.PlaceholderText = "Tên nhân viên";
            this.txtTenNhanVien.ReadOnly = false;
            this.txtTenNhanVien.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtTenNhanVien.SelectedText = "";
            this.txtTenNhanVien.SelectionLength = 0;
            this.txtTenNhanVien.SelectionStart = 0;
            this.txtTenNhanVien.ShortcutsEnabled = true;
            this.txtTenNhanVien.Size = new System.Drawing.Size(260, 43);
            this.txtTenNhanVien.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtTenNhanVien.TabIndex = 11;
            this.txtTenNhanVien.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtTenNhanVien.TextMarginBottom = 0;
            this.txtTenNhanVien.TextMarginLeft = 3;
            this.txtTenNhanVien.TextMarginTop = 1;
            this.txtTenNhanVien.TextPlaceholder = "Tên nhân viên";
            this.txtTenNhanVien.UseSystemPasswordChar = false;
            this.txtTenNhanVien.WordWrap = true;
            // 
            // txtMaNhanVien
            // 
            this.txtMaNhanVien.AcceptsReturn = false;
            this.txtMaNhanVien.AcceptsTab = false;
            this.txtMaNhanVien.AnimationSpeed = 200;
            this.txtMaNhanVien.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtMaNhanVien.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtMaNhanVien.AutoSizeHeight = true;
            this.txtMaNhanVien.BackColor = System.Drawing.Color.White;
            this.txtMaNhanVien.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtMaNhanVien.BackgroundImage")));
            this.txtMaNhanVien.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtMaNhanVien.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtMaNhanVien.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtMaNhanVien.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtMaNhanVien.BorderRadius = 10;
            this.txtMaNhanVien.BorderThickness = 1;
            this.txtMaNhanVien.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtMaNhanVien.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtMaNhanVien.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtMaNhanVien.DefaultText = "";
            this.txtMaNhanVien.FillColor = System.Drawing.Color.White;
            this.txtMaNhanVien.HideSelection = true;
            this.txtMaNhanVien.IconLeft = null;
            this.txtMaNhanVien.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtMaNhanVien.IconPadding = 10;
            this.txtMaNhanVien.IconRight = null;
            this.txtMaNhanVien.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtMaNhanVien.Lines = new string[0];
            this.txtMaNhanVien.Location = new System.Drawing.Point(93, 141);
            this.txtMaNhanVien.MaxLength = 32767;
            this.txtMaNhanVien.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtMaNhanVien.Modified = false;
            this.txtMaNhanVien.Multiline = false;
            this.txtMaNhanVien.Name = "txtMaNhanVien";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtMaNhanVien.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtMaNhanVien.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtMaNhanVien.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtMaNhanVien.OnIdleState = stateProperties16;
            this.txtMaNhanVien.Padding = new System.Windows.Forms.Padding(3);
            this.txtMaNhanVien.PasswordChar = '\0';
            this.txtMaNhanVien.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtMaNhanVien.PlaceholderText = "Mã nhân viên";
            this.txtMaNhanVien.ReadOnly = false;
            this.txtMaNhanVien.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtMaNhanVien.SelectedText = "";
            this.txtMaNhanVien.SelectionLength = 0;
            this.txtMaNhanVien.SelectionStart = 0;
            this.txtMaNhanVien.ShortcutsEnabled = true;
            this.txtMaNhanVien.Size = new System.Drawing.Size(260, 43);
            this.txtMaNhanVien.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtMaNhanVien.TabIndex = 10;
            this.txtMaNhanVien.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtMaNhanVien.TextMarginBottom = 0;
            this.txtMaNhanVien.TextMarginLeft = 3;
            this.txtMaNhanVien.TextMarginTop = 1;
            this.txtMaNhanVien.TextPlaceholder = "Mã nhân viên";
            this.txtMaNhanVien.UseSystemPasswordChar = false;
            this.txtMaNhanVien.WordWrap = true;
            // 
            // nhanvienBtnUpdate
            // 
            this.nhanvienBtnUpdate.AllowAnimations = true;
            this.nhanvienBtnUpdate.AllowMouseEffects = true;
            this.nhanvienBtnUpdate.AllowToggling = false;
            this.nhanvienBtnUpdate.AnimationSpeed = 200;
            this.nhanvienBtnUpdate.AutoGenerateColors = false;
            this.nhanvienBtnUpdate.AutoRoundBorders = false;
            this.nhanvienBtnUpdate.AutoSizeLeftIcon = true;
            this.nhanvienBtnUpdate.AutoSizeRightIcon = true;
            this.nhanvienBtnUpdate.BackColor = System.Drawing.Color.Transparent;
            this.nhanvienBtnUpdate.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.nhanvienBtnUpdate.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("nhanvienBtnUpdate.BackgroundImage")));
            this.nhanvienBtnUpdate.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.nhanvienBtnUpdate.ButtonText = "Cập nhật";
            this.nhanvienBtnUpdate.ButtonTextMarginLeft = 0;
            this.nhanvienBtnUpdate.ColorContrastOnClick = 45;
            this.nhanvienBtnUpdate.ColorContrastOnHover = 45;
            this.nhanvienBtnUpdate.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.nhanvienBtnUpdate.CustomizableEdges = borderEdges2;
            this.nhanvienBtnUpdate.DialogResult = System.Windows.Forms.DialogResult.None;
            this.nhanvienBtnUpdate.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.nhanvienBtnUpdate.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.nhanvienBtnUpdate.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.nhanvienBtnUpdate.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.nhanvienBtnUpdate.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.nhanvienBtnUpdate.ForeColor = System.Drawing.Color.White;
            this.nhanvienBtnUpdate.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.nhanvienBtnUpdate.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.nhanvienBtnUpdate.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.nhanvienBtnUpdate.IconMarginLeft = 11;
            this.nhanvienBtnUpdate.IconPadding = 10;
            this.nhanvienBtnUpdate.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.nhanvienBtnUpdate.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.nhanvienBtnUpdate.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.nhanvienBtnUpdate.IconSize = 25;
            this.nhanvienBtnUpdate.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.nhanvienBtnUpdate.IdleBorderRadius = 15;
            this.nhanvienBtnUpdate.IdleBorderThickness = 1;
            this.nhanvienBtnUpdate.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.nhanvienBtnUpdate.IdleIconLeftImage = null;
            this.nhanvienBtnUpdate.IdleIconRightImage = null;
            this.nhanvienBtnUpdate.IndicateFocus = false;
            this.nhanvienBtnUpdate.Location = new System.Drawing.Point(93, 438);
            this.nhanvienBtnUpdate.Name = "nhanvienBtnUpdate";
            this.nhanvienBtnUpdate.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.nhanvienBtnUpdate.OnDisabledState.BorderRadius = 15;
            this.nhanvienBtnUpdate.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.nhanvienBtnUpdate.OnDisabledState.BorderThickness = 1;
            this.nhanvienBtnUpdate.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.nhanvienBtnUpdate.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.nhanvienBtnUpdate.OnDisabledState.IconLeftImage = null;
            this.nhanvienBtnUpdate.OnDisabledState.IconRightImage = null;
            this.nhanvienBtnUpdate.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.nhanvienBtnUpdate.onHoverState.BorderRadius = 15;
            this.nhanvienBtnUpdate.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.nhanvienBtnUpdate.onHoverState.BorderThickness = 1;
            this.nhanvienBtnUpdate.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.nhanvienBtnUpdate.onHoverState.ForeColor = System.Drawing.Color.White;
            this.nhanvienBtnUpdate.onHoverState.IconLeftImage = null;
            this.nhanvienBtnUpdate.onHoverState.IconRightImage = null;
            this.nhanvienBtnUpdate.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.nhanvienBtnUpdate.OnIdleState.BorderRadius = 15;
            this.nhanvienBtnUpdate.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.nhanvienBtnUpdate.OnIdleState.BorderThickness = 1;
            this.nhanvienBtnUpdate.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.nhanvienBtnUpdate.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.nhanvienBtnUpdate.OnIdleState.IconLeftImage = null;
            this.nhanvienBtnUpdate.OnIdleState.IconRightImage = null;
            this.nhanvienBtnUpdate.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.nhanvienBtnUpdate.OnPressedState.BorderRadius = 15;
            this.nhanvienBtnUpdate.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.nhanvienBtnUpdate.OnPressedState.BorderThickness = 1;
            this.nhanvienBtnUpdate.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.nhanvienBtnUpdate.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.nhanvienBtnUpdate.OnPressedState.IconLeftImage = null;
            this.nhanvienBtnUpdate.OnPressedState.IconRightImage = null;
            this.nhanvienBtnUpdate.Size = new System.Drawing.Size(117, 44);
            this.nhanvienBtnUpdate.TabIndex = 18;
            this.nhanvienBtnUpdate.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.nhanvienBtnUpdate.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.nhanvienBtnUpdate.TextMarginLeft = 0;
            this.nhanvienBtnUpdate.TextPadding = new System.Windows.Forms.Padding(0);
            this.nhanvienBtnUpdate.UseDefaultRadiusAndThickness = true;
            this.nhanvienBtnUpdate.Click += new System.EventHandler(this.nhanvienBtnUpdate_Click);
            // 
            // isrNhanVien
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.White;
            this.ClientSize = new System.Drawing.Size(429, 537);
            this.Controls.Add(this.nhanvienBtnUpdate);
            this.Controls.Add(this.bunifuLabel1);
            this.Controls.Add(this.nhanvienBtnAdd);
            this.Controls.Add(this.txtSDT);
            this.Controls.Add(this.txtDiaChi);
            this.Controls.Add(this.txtTenNhanVien);
            this.Controls.Add(this.txtMaNhanVien);
            this.Name = "isrNhanVien";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "isrNhanVien";
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 nhanvienBtnAdd;
        private Bunifu.UI.WinForms.BunifuTextBox txtSDT;
        private Bunifu.UI.WinForms.BunifuTextBox txtDiaChi;
        private Bunifu.UI.WinForms.BunifuTextBox txtTenNhanVien;
        private Bunifu.UI.WinForms.BunifuTextBox txtMaNhanVien;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 nhanvienBtnUpdate;
    }
}