namespace BTL.GUI
{
    partial class formHangHoa
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(formHangHoa));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle1 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle3 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle4 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle5 = new System.Windows.Forms.DataGridViewCellStyle();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            this.hanghoaTitle = new Bunifu.UI.WinForms.BunifuLabel();
            this.hanghoaSearch = new Bunifu.UI.WinForms.BunifuTextBox();
            this.hanghoaSearchBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.hanghoaPanel = new Bunifu.UI.WinForms.BunifuPanel();
            this.hanghoaTable = new Guna.UI2.WinForms.Guna2DataGridView();
            this.xuatHangHoa = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.nhanvienPanelSub = new Bunifu.UI.WinForms.BunifuLabel();
            this.nhanvienPanelTitle = new Bunifu.UI.WinForms.BunifuLabel();
            this.hanghoaSuaBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.hanghoaThemBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.hanghoaXoaBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.bunifuPanel2 = new Bunifu.UI.WinForms.BunifuPanel();
            this.hanghoaPanel.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.hanghoaTable)).BeginInit();
            this.SuspendLayout();
            // 
            // hanghoaTitle
            // 
            this.hanghoaTitle.AllowParentOverrides = false;
            this.hanghoaTitle.AutoEllipsis = false;
            this.hanghoaTitle.Cursor = System.Windows.Forms.Cursors.Default;
            this.hanghoaTitle.CursorType = System.Windows.Forms.Cursors.Default;
            this.hanghoaTitle.Font = new System.Drawing.Font("Segoe UI Semibold", 13F, System.Drawing.FontStyle.Bold);
            this.hanghoaTitle.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(79)))), ((int)(((byte)(79)))), ((int)(((byte)(79)))));
            this.hanghoaTitle.Location = new System.Drawing.Point(134, 23);
            this.hanghoaTitle.Name = "hanghoaTitle";
            this.hanghoaTitle.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.hanghoaTitle.Size = new System.Drawing.Size(92, 30);
            this.hanghoaTitle.TabIndex = 0;
            this.hanghoaTitle.Text = "Máy Tính";
            this.hanghoaTitle.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.hanghoaTitle.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // hanghoaSearch
            // 
            this.hanghoaSearch.AcceptsReturn = false;
            this.hanghoaSearch.AcceptsTab = false;
            this.hanghoaSearch.AnimationSpeed = 200;
            this.hanghoaSearch.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.hanghoaSearch.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.hanghoaSearch.AutoSizeHeight = true;
            this.hanghoaSearch.BackColor = System.Drawing.Color.Transparent;
            this.hanghoaSearch.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("hanghoaSearch.BackgroundImage")));
            this.hanghoaSearch.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.hanghoaSearch.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.hanghoaSearch.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.hanghoaSearch.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(235)))), ((int)(((byte)(235)))), ((int)(((byte)(235)))));
            this.hanghoaSearch.BorderRadius = 20;
            this.hanghoaSearch.BorderThickness = 1;
            this.hanghoaSearch.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.hanghoaSearch.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.hanghoaSearch.DefaultFont = new System.Drawing.Font("Segoe UI", 10F);
            this.hanghoaSearch.DefaultText = "";
            this.hanghoaSearch.FillColor = System.Drawing.Color.White;
            this.hanghoaSearch.HideSelection = true;
            this.hanghoaSearch.IconLeft = ((System.Drawing.Image)(resources.GetObject("hanghoaSearch.IconLeft")));
            this.hanghoaSearch.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.hanghoaSearch.IconPadding = 10;
            this.hanghoaSearch.IconRight = null;
            this.hanghoaSearch.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.hanghoaSearch.Lines = new string[0];
            this.hanghoaSearch.Location = new System.Drawing.Point(271, 21);
            this.hanghoaSearch.Margin = new System.Windows.Forms.Padding(20, 3, 3, 3);
            this.hanghoaSearch.MaxLength = 32767;
            this.hanghoaSearch.MinimumSize = new System.Drawing.Size(1, 1);
            this.hanghoaSearch.Modified = false;
            this.hanghoaSearch.Multiline = false;
            this.hanghoaSearch.Name = "hanghoaSearch";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.hanghoaSearch.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.hanghoaSearch.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.hanghoaSearch.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(235)))), ((int)(((byte)(235)))), ((int)(((byte)(235)))));
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.hanghoaSearch.OnIdleState = stateProperties4;
            this.hanghoaSearch.Padding = new System.Windows.Forms.Padding(40, 3, 3, 3);
            this.hanghoaSearch.PasswordChar = '\0';
            this.hanghoaSearch.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.hanghoaSearch.PlaceholderText = "Tìm kiếm";
            this.hanghoaSearch.ReadOnly = false;
            this.hanghoaSearch.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.hanghoaSearch.SelectedText = "";
            this.hanghoaSearch.SelectionLength = 0;
            this.hanghoaSearch.SelectionStart = 0;
            this.hanghoaSearch.ShortcutsEnabled = true;
            this.hanghoaSearch.Size = new System.Drawing.Size(367, 41);
            this.hanghoaSearch.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.hanghoaSearch.TabIndex = 12;
            this.hanghoaSearch.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.hanghoaSearch.TextMarginBottom = 0;
            this.hanghoaSearch.TextMarginLeft = 15;
            this.hanghoaSearch.TextMarginTop = 0;
            this.hanghoaSearch.TextPlaceholder = "Tìm kiếm";
            this.hanghoaSearch.UseSystemPasswordChar = false;
            this.hanghoaSearch.WordWrap = true;
            this.hanghoaSearch.KeyDown += new System.Windows.Forms.KeyEventHandler(this.hanghoaSearch_KeyDown);
            // 
            // hanghoaSearchBtn
            // 
            this.hanghoaSearchBtn.AllowAnimations = true;
            this.hanghoaSearchBtn.AllowMouseEffects = true;
            this.hanghoaSearchBtn.AllowToggling = false;
            this.hanghoaSearchBtn.AnimationSpeed = 200;
            this.hanghoaSearchBtn.AutoGenerateColors = false;
            this.hanghoaSearchBtn.AutoRoundBorders = false;
            this.hanghoaSearchBtn.AutoSizeLeftIcon = true;
            this.hanghoaSearchBtn.AutoSizeRightIcon = true;
            this.hanghoaSearchBtn.BackColor = System.Drawing.Color.Transparent;
            this.hanghoaSearchBtn.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.hanghoaSearchBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("hanghoaSearchBtn.BackgroundImage")));
            this.hanghoaSearchBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.hanghoaSearchBtn.ButtonText = "";
            this.hanghoaSearchBtn.ButtonTextMarginLeft = 0;
            this.hanghoaSearchBtn.ColorContrastOnClick = 45;
            this.hanghoaSearchBtn.ColorContrastOnHover = 45;
            this.hanghoaSearchBtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.hanghoaSearchBtn.CustomizableEdges = borderEdges1;
            this.hanghoaSearchBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.hanghoaSearchBtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.hanghoaSearchBtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.hanghoaSearchBtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.hanghoaSearchBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.hanghoaSearchBtn.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.hanghoaSearchBtn.ForeColor = System.Drawing.Color.White;
            this.hanghoaSearchBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.hanghoaSearchBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.hanghoaSearchBtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.hanghoaSearchBtn.IconMarginLeft = 11;
            this.hanghoaSearchBtn.IconPadding = 10;
            this.hanghoaSearchBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.hanghoaSearchBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.hanghoaSearchBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.hanghoaSearchBtn.IconSize = 25;
            this.hanghoaSearchBtn.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.hanghoaSearchBtn.IdleBorderRadius = 25;
            this.hanghoaSearchBtn.IdleBorderThickness = 1;
            this.hanghoaSearchBtn.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.hanghoaSearchBtn.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("hanghoaSearchBtn.IdleIconLeftImage")));
            this.hanghoaSearchBtn.IdleIconRightImage = null;
            this.hanghoaSearchBtn.IndicateFocus = false;
            this.hanghoaSearchBtn.Location = new System.Drawing.Point(644, 23);
            this.hanghoaSearchBtn.Name = "hanghoaSearchBtn";
            this.hanghoaSearchBtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.hanghoaSearchBtn.OnDisabledState.BorderRadius = 25;
            this.hanghoaSearchBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.hanghoaSearchBtn.OnDisabledState.BorderThickness = 1;
            this.hanghoaSearchBtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.hanghoaSearchBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.hanghoaSearchBtn.OnDisabledState.IconLeftImage = null;
            this.hanghoaSearchBtn.OnDisabledState.IconRightImage = null;
            this.hanghoaSearchBtn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.hanghoaSearchBtn.onHoverState.BorderRadius = 25;
            this.hanghoaSearchBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.hanghoaSearchBtn.onHoverState.BorderThickness = 1;
            this.hanghoaSearchBtn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.hanghoaSearchBtn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.hanghoaSearchBtn.onHoverState.IconLeftImage = null;
            this.hanghoaSearchBtn.onHoverState.IconRightImage = null;
            this.hanghoaSearchBtn.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.hanghoaSearchBtn.OnIdleState.BorderRadius = 25;
            this.hanghoaSearchBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.hanghoaSearchBtn.OnIdleState.BorderThickness = 1;
            this.hanghoaSearchBtn.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.hanghoaSearchBtn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.hanghoaSearchBtn.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("hanghoaSearchBtn.OnIdleState.IconLeftImage")));
            this.hanghoaSearchBtn.OnIdleState.IconRightImage = null;
            this.hanghoaSearchBtn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.hanghoaSearchBtn.OnPressedState.BorderRadius = 25;
            this.hanghoaSearchBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.hanghoaSearchBtn.OnPressedState.BorderThickness = 1;
            this.hanghoaSearchBtn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.hanghoaSearchBtn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.hanghoaSearchBtn.OnPressedState.IconLeftImage = null;
            this.hanghoaSearchBtn.OnPressedState.IconRightImage = null;
            this.hanghoaSearchBtn.Size = new System.Drawing.Size(42, 39);
            this.hanghoaSearchBtn.TabIndex = 13;
            this.hanghoaSearchBtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.hanghoaSearchBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.hanghoaSearchBtn.TextMarginLeft = 0;
            this.hanghoaSearchBtn.TextPadding = new System.Windows.Forms.Padding(0);
            this.hanghoaSearchBtn.UseDefaultRadiusAndThickness = true;
            this.hanghoaSearchBtn.Click += new System.EventHandler(this.hanghoaSearchBtn_Click);
            // 
            // hanghoaPanel
            // 
            this.hanghoaPanel.BackgroundColor = System.Drawing.Color.White;
            this.hanghoaPanel.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("hanghoaPanel.BackgroundImage")));
            this.hanghoaPanel.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.hanghoaPanel.BorderColor = System.Drawing.Color.Gainsboro;
            this.hanghoaPanel.BorderRadius = 25;
            this.hanghoaPanel.BorderThickness = 1;
            this.hanghoaPanel.Controls.Add(this.hanghoaTable);
            this.hanghoaPanel.Controls.Add(this.xuatHangHoa);
            this.hanghoaPanel.Controls.Add(this.nhanvienPanelSub);
            this.hanghoaPanel.Controls.Add(this.nhanvienPanelTitle);
            this.hanghoaPanel.Controls.Add(this.hanghoaSuaBtn);
            this.hanghoaPanel.Controls.Add(this.hanghoaThemBtn);
            this.hanghoaPanel.Controls.Add(this.hanghoaXoaBtn);
            this.hanghoaPanel.Location = new System.Drawing.Point(134, 127);
            this.hanghoaPanel.Name = "hanghoaPanel";
            this.hanghoaPanel.ShowBorders = true;
            this.hanghoaPanel.Size = new System.Drawing.Size(1107, 630);
            this.hanghoaPanel.TabIndex = 24;
            // 
            // hanghoaTable
            // 
            this.hanghoaTable.AllowUserToAddRows = false;
            this.hanghoaTable.AllowUserToDeleteRows = false;
            dataGridViewCellStyle1.BackColor = System.Drawing.Color.White;
            this.hanghoaTable.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle1;
            this.hanghoaTable.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.hanghoaTable.BackgroundColor = System.Drawing.Color.White;
            this.hanghoaTable.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.hanghoaTable.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.hanghoaTable.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle2.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle2.BackColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.Font = new System.Drawing.Font("Segoe UI Semibold", 10.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            dataGridViewCellStyle2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(33)))), ((int)(((byte)(35)))), ((int)(((byte)(74)))));
            dataGridViewCellStyle2.Padding = new System.Windows.Forms.Padding(15, 0, 15, 0);
            dataGridViewCellStyle2.SelectionBackColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.SelectionForeColor = System.Drawing.SystemColors.HighlightText;
            dataGridViewCellStyle2.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.hanghoaTable.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2;
            this.hanghoaTable.ColumnHeadersHeight = 55;
            this.hanghoaTable.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.DisableResizing;
            dataGridViewCellStyle3.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle3.BackColor = System.Drawing.Color.White;
            dataGridViewCellStyle3.Font = new System.Drawing.Font("Segoe UI Semibold", 9F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle3.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(71)))), ((int)(((byte)(69)))), ((int)(((byte)(94)))));
            dataGridViewCellStyle3.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(231)))), ((int)(((byte)(229)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle3.SelectionForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(71)))), ((int)(((byte)(69)))), ((int)(((byte)(94)))));
            dataGridViewCellStyle3.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.hanghoaTable.DefaultCellStyle = dataGridViewCellStyle3;
            this.hanghoaTable.EnableHeadersVisualStyles = false;
            this.hanghoaTable.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(231)))), ((int)(((byte)(229)))), ((int)(((byte)(255)))));
            this.hanghoaTable.Location = new System.Drawing.Point(42, 122);
            this.hanghoaTable.Name = "hanghoaTable";
            this.hanghoaTable.ReadOnly = true;
            this.hanghoaTable.RowHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.Single;
            dataGridViewCellStyle4.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleCenter;
            dataGridViewCellStyle4.BackColor = System.Drawing.SystemColors.Control;
            dataGridViewCellStyle4.Font = new System.Drawing.Font("Microsoft Sans Serif", 7.8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            dataGridViewCellStyle4.ForeColor = System.Drawing.SystemColors.WindowText;
            dataGridViewCellStyle4.Padding = new System.Windows.Forms.Padding(0, 0, 0, 10);
            dataGridViewCellStyle4.SelectionBackColor = System.Drawing.Color.White;
            dataGridViewCellStyle4.SelectionForeColor = System.Drawing.SystemColors.HighlightText;
            dataGridViewCellStyle4.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.hanghoaTable.RowHeadersDefaultCellStyle = dataGridViewCellStyle4;
            this.hanghoaTable.RowHeadersVisible = false;
            this.hanghoaTable.RowHeadersWidth = 51;
            this.hanghoaTable.RowHeadersWidthSizeMode = System.Windows.Forms.DataGridViewRowHeadersWidthSizeMode.DisableResizing;
            dataGridViewCellStyle5.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle5.Padding = new System.Windows.Forms.Padding(15, 0, 0, 5);
            dataGridViewCellStyle5.SelectionBackColor = System.Drawing.Color.AliceBlue;
            this.hanghoaTable.RowsDefaultCellStyle = dataGridViewCellStyle5;
            this.hanghoaTable.RowTemplate.Height = 55;
            this.hanghoaTable.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.hanghoaTable.Size = new System.Drawing.Size(1029, 470);
            this.hanghoaTable.TabIndex = 45;
            this.hanghoaTable.ThemeStyle.AlternatingRowsStyle.BackColor = System.Drawing.Color.White;
            this.hanghoaTable.ThemeStyle.AlternatingRowsStyle.Font = null;
            this.hanghoaTable.ThemeStyle.AlternatingRowsStyle.ForeColor = System.Drawing.Color.Empty;
            this.hanghoaTable.ThemeStyle.AlternatingRowsStyle.SelectionBackColor = System.Drawing.Color.Empty;
            this.hanghoaTable.ThemeStyle.AlternatingRowsStyle.SelectionForeColor = System.Drawing.Color.Empty;
            this.hanghoaTable.ThemeStyle.BackColor = System.Drawing.Color.White;
            this.hanghoaTable.ThemeStyle.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(231)))), ((int)(((byte)(229)))), ((int)(((byte)(255)))));
            this.hanghoaTable.ThemeStyle.HeaderStyle.BackColor = System.Drawing.Color.White;
            this.hanghoaTable.ThemeStyle.HeaderStyle.BorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            this.hanghoaTable.ThemeStyle.HeaderStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 10.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            this.hanghoaTable.ThemeStyle.HeaderStyle.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(33)))), ((int)(((byte)(35)))), ((int)(((byte)(74)))));
            this.hanghoaTable.ThemeStyle.HeaderStyle.HeaightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.DisableResizing;
            this.hanghoaTable.ThemeStyle.HeaderStyle.Height = 55;
            this.hanghoaTable.ThemeStyle.ReadOnly = true;
            this.hanghoaTable.ThemeStyle.RowsStyle.BackColor = System.Drawing.Color.White;
            this.hanghoaTable.ThemeStyle.RowsStyle.BorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.hanghoaTable.ThemeStyle.RowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9F, System.Drawing.FontStyle.Bold);
            this.hanghoaTable.ThemeStyle.RowsStyle.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(71)))), ((int)(((byte)(69)))), ((int)(((byte)(94)))));
            this.hanghoaTable.ThemeStyle.RowsStyle.Height = 55;
            this.hanghoaTable.ThemeStyle.RowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(231)))), ((int)(((byte)(229)))), ((int)(((byte)(255)))));
            this.hanghoaTable.ThemeStyle.RowsStyle.SelectionForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(71)))), ((int)(((byte)(69)))), ((int)(((byte)(94)))));
            // 
            // xuatHangHoa
            // 
            this.xuatHangHoa.AllowAnimations = true;
            this.xuatHangHoa.AllowMouseEffects = true;
            this.xuatHangHoa.AllowToggling = false;
            this.xuatHangHoa.AnimationSpeed = 200;
            this.xuatHangHoa.AutoGenerateColors = false;
            this.xuatHangHoa.AutoRoundBorders = false;
            this.xuatHangHoa.AutoSizeLeftIcon = true;
            this.xuatHangHoa.AutoSizeRightIcon = true;
            this.xuatHangHoa.BackColor = System.Drawing.Color.Transparent;
            this.xuatHangHoa.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(127)))), ((int)(((byte)(127)))), ((int)(((byte)(213)))));
            this.xuatHangHoa.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("xuatHangHoa.BackgroundImage")));
            this.xuatHangHoa.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.xuatHangHoa.ButtonText = "Xuất File";
            this.xuatHangHoa.ButtonTextMarginLeft = 0;
            this.xuatHangHoa.ColorContrastOnClick = 45;
            this.xuatHangHoa.ColorContrastOnHover = 45;
            this.xuatHangHoa.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.xuatHangHoa.CustomizableEdges = borderEdges2;
            this.xuatHangHoa.DialogResult = System.Windows.Forms.DialogResult.None;
            this.xuatHangHoa.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.xuatHangHoa.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.xuatHangHoa.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.xuatHangHoa.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.xuatHangHoa.Font = new System.Drawing.Font("Segoe UI Semibold", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            this.xuatHangHoa.ForeColor = System.Drawing.Color.White;
            this.xuatHangHoa.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.xuatHangHoa.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.xuatHangHoa.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.xuatHangHoa.IconMarginLeft = 11;
            this.xuatHangHoa.IconPadding = 10;
            this.xuatHangHoa.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.xuatHangHoa.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.xuatHangHoa.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.xuatHangHoa.IconSize = 25;
            this.xuatHangHoa.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(127)))), ((int)(((byte)(127)))), ((int)(((byte)(213)))));
            this.xuatHangHoa.IdleBorderRadius = 10;
            this.xuatHangHoa.IdleBorderThickness = 1;
            this.xuatHangHoa.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(127)))), ((int)(((byte)(127)))), ((int)(((byte)(213)))));
            this.xuatHangHoa.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("xuatHangHoa.IdleIconLeftImage")));
            this.xuatHangHoa.IdleIconRightImage = null;
            this.xuatHangHoa.IndicateFocus = false;
            this.xuatHangHoa.Location = new System.Drawing.Point(911, 35);
            this.xuatHangHoa.Name = "xuatHangHoa";
            this.xuatHangHoa.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.xuatHangHoa.OnDisabledState.BorderRadius = 10;
            this.xuatHangHoa.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.xuatHangHoa.OnDisabledState.BorderThickness = 1;
            this.xuatHangHoa.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.xuatHangHoa.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.xuatHangHoa.OnDisabledState.IconLeftImage = null;
            this.xuatHangHoa.OnDisabledState.IconRightImage = null;
            this.xuatHangHoa.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.xuatHangHoa.onHoverState.BorderRadius = 10;
            this.xuatHangHoa.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.xuatHangHoa.onHoverState.BorderThickness = 1;
            this.xuatHangHoa.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.xuatHangHoa.onHoverState.ForeColor = System.Drawing.Color.White;
            this.xuatHangHoa.onHoverState.IconLeftImage = null;
            this.xuatHangHoa.onHoverState.IconRightImage = null;
            this.xuatHangHoa.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(127)))), ((int)(((byte)(127)))), ((int)(((byte)(213)))));
            this.xuatHangHoa.OnIdleState.BorderRadius = 10;
            this.xuatHangHoa.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.xuatHangHoa.OnIdleState.BorderThickness = 1;
            this.xuatHangHoa.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(127)))), ((int)(((byte)(127)))), ((int)(((byte)(213)))));
            this.xuatHangHoa.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.xuatHangHoa.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("xuatHangHoa.OnIdleState.IconLeftImage")));
            this.xuatHangHoa.OnIdleState.IconRightImage = null;
            this.xuatHangHoa.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.xuatHangHoa.OnPressedState.BorderRadius = 10;
            this.xuatHangHoa.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.xuatHangHoa.OnPressedState.BorderThickness = 1;
            this.xuatHangHoa.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.xuatHangHoa.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.xuatHangHoa.OnPressedState.IconLeftImage = null;
            this.xuatHangHoa.OnPressedState.IconRightImage = null;
            this.xuatHangHoa.Size = new System.Drawing.Size(161, 40);
            this.xuatHangHoa.TabIndex = 44;
            this.xuatHangHoa.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.xuatHangHoa.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.xuatHangHoa.TextMarginLeft = 0;
            this.xuatHangHoa.TextPadding = new System.Windows.Forms.Padding(15, 0, 0, 0);
            this.xuatHangHoa.UseDefaultRadiusAndThickness = true;
            this.xuatHangHoa.Click += new System.EventHandler(this.xuatHangHoa_Click);
            // 
            // nhanvienPanelSub
            // 
            this.nhanvienPanelSub.AllowParentOverrides = false;
            this.nhanvienPanelSub.AutoEllipsis = false;
            this.nhanvienPanelSub.CursorType = null;
            this.nhanvienPanelSub.Font = new System.Drawing.Font("Segoe UI", 7F);
            this.nhanvienPanelSub.ForeColor = System.Drawing.SystemColors.ActiveBorder;
            this.nhanvienPanelSub.Location = new System.Drawing.Point(43, 60);
            this.nhanvienPanelSub.Name = "nhanvienPanelSub";
            this.nhanvienPanelSub.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.nhanvienPanelSub.Size = new System.Drawing.Size(128, 15);
            this.nhanvienPanelSub.TabIndex = 36;
            this.nhanvienPanelSub.Text = "Tìm thấy một số kết quả";
            this.nhanvienPanelSub.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.nhanvienPanelSub.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // nhanvienPanelTitle
            // 
            this.nhanvienPanelTitle.AllowParentOverrides = false;
            this.nhanvienPanelTitle.AutoEllipsis = false;
            this.nhanvienPanelTitle.CursorType = null;
            this.nhanvienPanelTitle.Font = new System.Drawing.Font("Segoe UI Semibold", 13F, System.Drawing.FontStyle.Bold);
            this.nhanvienPanelTitle.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(79)))), ((int)(((byte)(79)))), ((int)(((byte)(79)))));
            this.nhanvienPanelTitle.Location = new System.Drawing.Point(43, 24);
            this.nhanvienPanelTitle.Name = "nhanvienPanelTitle";
            this.nhanvienPanelTitle.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.nhanvienPanelTitle.Size = new System.Drawing.Size(199, 30);
            this.nhanvienPanelTitle.TabIndex = 37;
            this.nhanvienPanelTitle.Text = "Thông Tin Máy Tính";
            this.nhanvienPanelTitle.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.nhanvienPanelTitle.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // hanghoaSuaBtn
            // 
            this.hanghoaSuaBtn.AllowAnimations = true;
            this.hanghoaSuaBtn.AllowMouseEffects = true;
            this.hanghoaSuaBtn.AllowToggling = false;
            this.hanghoaSuaBtn.AnimationSpeed = 200;
            this.hanghoaSuaBtn.AutoGenerateColors = false;
            this.hanghoaSuaBtn.AutoRoundBorders = false;
            this.hanghoaSuaBtn.AutoSizeLeftIcon = true;
            this.hanghoaSuaBtn.AutoSizeRightIcon = true;
            this.hanghoaSuaBtn.BackColor = System.Drawing.Color.Transparent;
            this.hanghoaSuaBtn.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.hanghoaSuaBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("hanghoaSuaBtn.BackgroundImage")));
            this.hanghoaSuaBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.hanghoaSuaBtn.ButtonText = "Sửa";
            this.hanghoaSuaBtn.ButtonTextMarginLeft = 0;
            this.hanghoaSuaBtn.ColorContrastOnClick = 45;
            this.hanghoaSuaBtn.ColorContrastOnHover = 45;
            this.hanghoaSuaBtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.hanghoaSuaBtn.CustomizableEdges = borderEdges3;
            this.hanghoaSuaBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.hanghoaSuaBtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.hanghoaSuaBtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.hanghoaSuaBtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.hanghoaSuaBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.hanghoaSuaBtn.Font = new System.Drawing.Font("Segoe UI Semibold", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            this.hanghoaSuaBtn.ForeColor = System.Drawing.Color.White;
            this.hanghoaSuaBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.hanghoaSuaBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.hanghoaSuaBtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.hanghoaSuaBtn.IconMarginLeft = 11;
            this.hanghoaSuaBtn.IconPadding = 10;
            this.hanghoaSuaBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.hanghoaSuaBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.hanghoaSuaBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.hanghoaSuaBtn.IconSize = 25;
            this.hanghoaSuaBtn.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.hanghoaSuaBtn.IdleBorderRadius = 10;
            this.hanghoaSuaBtn.IdleBorderThickness = 1;
            this.hanghoaSuaBtn.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.hanghoaSuaBtn.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("hanghoaSuaBtn.IdleIconLeftImage")));
            this.hanghoaSuaBtn.IdleIconRightImage = null;
            this.hanghoaSuaBtn.IndicateFocus = false;
            this.hanghoaSuaBtn.Location = new System.Drawing.Point(800, 35);
            this.hanghoaSuaBtn.Name = "hanghoaSuaBtn";
            this.hanghoaSuaBtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.hanghoaSuaBtn.OnDisabledState.BorderRadius = 10;
            this.hanghoaSuaBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.hanghoaSuaBtn.OnDisabledState.BorderThickness = 1;
            this.hanghoaSuaBtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.hanghoaSuaBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.hanghoaSuaBtn.OnDisabledState.IconLeftImage = null;
            this.hanghoaSuaBtn.OnDisabledState.IconRightImage = null;
            this.hanghoaSuaBtn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.hanghoaSuaBtn.onHoverState.BorderRadius = 10;
            this.hanghoaSuaBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.hanghoaSuaBtn.onHoverState.BorderThickness = 1;
            this.hanghoaSuaBtn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.hanghoaSuaBtn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.hanghoaSuaBtn.onHoverState.IconLeftImage = null;
            this.hanghoaSuaBtn.onHoverState.IconRightImage = null;
            this.hanghoaSuaBtn.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.hanghoaSuaBtn.OnIdleState.BorderRadius = 10;
            this.hanghoaSuaBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.hanghoaSuaBtn.OnIdleState.BorderThickness = 1;
            this.hanghoaSuaBtn.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.hanghoaSuaBtn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.hanghoaSuaBtn.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("hanghoaSuaBtn.OnIdleState.IconLeftImage")));
            this.hanghoaSuaBtn.OnIdleState.IconRightImage = null;
            this.hanghoaSuaBtn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.hanghoaSuaBtn.OnPressedState.BorderRadius = 10;
            this.hanghoaSuaBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.hanghoaSuaBtn.OnPressedState.BorderThickness = 1;
            this.hanghoaSuaBtn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.hanghoaSuaBtn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.hanghoaSuaBtn.OnPressedState.IconLeftImage = null;
            this.hanghoaSuaBtn.OnPressedState.IconRightImage = null;
            this.hanghoaSuaBtn.Size = new System.Drawing.Size(96, 40);
            this.hanghoaSuaBtn.TabIndex = 2;
            this.hanghoaSuaBtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.hanghoaSuaBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.hanghoaSuaBtn.TextMarginLeft = 0;
            this.hanghoaSuaBtn.TextPadding = new System.Windows.Forms.Padding(15, 0, 0, 0);
            this.hanghoaSuaBtn.UseDefaultRadiusAndThickness = true;
            this.hanghoaSuaBtn.Click += new System.EventHandler(this.hanghoaSuaBtn_Click);
            // 
            // hanghoaThemBtn
            // 
            this.hanghoaThemBtn.AllowAnimations = true;
            this.hanghoaThemBtn.AllowMouseEffects = true;
            this.hanghoaThemBtn.AllowToggling = false;
            this.hanghoaThemBtn.AnimationSpeed = 200;
            this.hanghoaThemBtn.AutoGenerateColors = false;
            this.hanghoaThemBtn.AutoRoundBorders = false;
            this.hanghoaThemBtn.AutoSizeLeftIcon = true;
            this.hanghoaThemBtn.AutoSizeRightIcon = true;
            this.hanghoaThemBtn.BackColor = System.Drawing.Color.Transparent;
            this.hanghoaThemBtn.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(95)))), ((int)(((byte)(210)))), ((int)(((byte)(143)))));
            this.hanghoaThemBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("hanghoaThemBtn.BackgroundImage")));
            this.hanghoaThemBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.hanghoaThemBtn.ButtonText = "Thêm";
            this.hanghoaThemBtn.ButtonTextMarginLeft = 0;
            this.hanghoaThemBtn.ColorContrastOnClick = 45;
            this.hanghoaThemBtn.ColorContrastOnHover = 45;
            this.hanghoaThemBtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.hanghoaThemBtn.CustomizableEdges = borderEdges4;
            this.hanghoaThemBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.hanghoaThemBtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.hanghoaThemBtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.hanghoaThemBtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.hanghoaThemBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.hanghoaThemBtn.Font = new System.Drawing.Font("Segoe UI Semibold", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            this.hanghoaThemBtn.ForeColor = System.Drawing.Color.White;
            this.hanghoaThemBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.hanghoaThemBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.hanghoaThemBtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.hanghoaThemBtn.IconMarginLeft = 11;
            this.hanghoaThemBtn.IconPadding = 10;
            this.hanghoaThemBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.hanghoaThemBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.hanghoaThemBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.hanghoaThemBtn.IconSize = 25;
            this.hanghoaThemBtn.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(80)))), ((int)(((byte)(223)))), ((int)(((byte)(178)))));
            this.hanghoaThemBtn.IdleBorderRadius = 10;
            this.hanghoaThemBtn.IdleBorderThickness = 1;
            this.hanghoaThemBtn.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(95)))), ((int)(((byte)(210)))), ((int)(((byte)(143)))));
            this.hanghoaThemBtn.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("hanghoaThemBtn.IdleIconLeftImage")));
            this.hanghoaThemBtn.IdleIconRightImage = null;
            this.hanghoaThemBtn.IndicateFocus = false;
            this.hanghoaThemBtn.Location = new System.Drawing.Point(566, 35);
            this.hanghoaThemBtn.Name = "hanghoaThemBtn";
            this.hanghoaThemBtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.hanghoaThemBtn.OnDisabledState.BorderRadius = 10;
            this.hanghoaThemBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.hanghoaThemBtn.OnDisabledState.BorderThickness = 1;
            this.hanghoaThemBtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.hanghoaThemBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.hanghoaThemBtn.OnDisabledState.IconLeftImage = null;
            this.hanghoaThemBtn.OnDisabledState.IconRightImage = null;
            this.hanghoaThemBtn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.hanghoaThemBtn.onHoverState.BorderRadius = 10;
            this.hanghoaThemBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.hanghoaThemBtn.onHoverState.BorderThickness = 1;
            this.hanghoaThemBtn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.hanghoaThemBtn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.hanghoaThemBtn.onHoverState.IconLeftImage = null;
            this.hanghoaThemBtn.onHoverState.IconRightImage = null;
            this.hanghoaThemBtn.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(80)))), ((int)(((byte)(223)))), ((int)(((byte)(178)))));
            this.hanghoaThemBtn.OnIdleState.BorderRadius = 10;
            this.hanghoaThemBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.hanghoaThemBtn.OnIdleState.BorderThickness = 1;
            this.hanghoaThemBtn.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(95)))), ((int)(((byte)(210)))), ((int)(((byte)(143)))));
            this.hanghoaThemBtn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.hanghoaThemBtn.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("hanghoaThemBtn.OnIdleState.IconLeftImage")));
            this.hanghoaThemBtn.OnIdleState.IconRightImage = null;
            this.hanghoaThemBtn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.hanghoaThemBtn.OnPressedState.BorderRadius = 10;
            this.hanghoaThemBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.hanghoaThemBtn.OnPressedState.BorderThickness = 1;
            this.hanghoaThemBtn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.hanghoaThemBtn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.hanghoaThemBtn.OnPressedState.IconLeftImage = null;
            this.hanghoaThemBtn.OnPressedState.IconRightImage = null;
            this.hanghoaThemBtn.Size = new System.Drawing.Size(96, 40);
            this.hanghoaThemBtn.TabIndex = 1;
            this.hanghoaThemBtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.hanghoaThemBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.hanghoaThemBtn.TextMarginLeft = 0;
            this.hanghoaThemBtn.TextPadding = new System.Windows.Forms.Padding(15, 0, 0, 0);
            this.hanghoaThemBtn.UseDefaultRadiusAndThickness = true;
            this.hanghoaThemBtn.Click += new System.EventHandler(this.hanghoaThemBtn_Click);
            // 
            // hanghoaXoaBtn
            // 
            this.hanghoaXoaBtn.AllowAnimations = true;
            this.hanghoaXoaBtn.AllowMouseEffects = true;
            this.hanghoaXoaBtn.AllowToggling = false;
            this.hanghoaXoaBtn.AnimationSpeed = 200;
            this.hanghoaXoaBtn.AutoGenerateColors = false;
            this.hanghoaXoaBtn.AutoRoundBorders = false;
            this.hanghoaXoaBtn.AutoSizeLeftIcon = true;
            this.hanghoaXoaBtn.AutoSizeRightIcon = true;
            this.hanghoaXoaBtn.BackColor = System.Drawing.Color.Transparent;
            this.hanghoaXoaBtn.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(246)))), ((int)(((byte)(78)))), ((int)(((byte)(96)))));
            this.hanghoaXoaBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("hanghoaXoaBtn.BackgroundImage")));
            this.hanghoaXoaBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.hanghoaXoaBtn.ButtonText = "Xóa";
            this.hanghoaXoaBtn.ButtonTextMarginLeft = 0;
            this.hanghoaXoaBtn.ColorContrastOnClick = 45;
            this.hanghoaXoaBtn.ColorContrastOnHover = 45;
            this.hanghoaXoaBtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.hanghoaXoaBtn.CustomizableEdges = borderEdges5;
            this.hanghoaXoaBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.hanghoaXoaBtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.hanghoaXoaBtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.hanghoaXoaBtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.hanghoaXoaBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.hanghoaXoaBtn.Font = new System.Drawing.Font("Segoe UI Semibold", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            this.hanghoaXoaBtn.ForeColor = System.Drawing.Color.White;
            this.hanghoaXoaBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.hanghoaXoaBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.hanghoaXoaBtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.hanghoaXoaBtn.IconMarginLeft = 11;
            this.hanghoaXoaBtn.IconPadding = 10;
            this.hanghoaXoaBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.hanghoaXoaBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.hanghoaXoaBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.hanghoaXoaBtn.IconSize = 25;
            this.hanghoaXoaBtn.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(246)))), ((int)(((byte)(78)))), ((int)(((byte)(96)))));
            this.hanghoaXoaBtn.IdleBorderRadius = 10;
            this.hanghoaXoaBtn.IdleBorderThickness = 1;
            this.hanghoaXoaBtn.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(246)))), ((int)(((byte)(78)))), ((int)(((byte)(96)))));
            this.hanghoaXoaBtn.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("hanghoaXoaBtn.IdleIconLeftImage")));
            this.hanghoaXoaBtn.IdleIconRightImage = null;
            this.hanghoaXoaBtn.IndicateFocus = false;
            this.hanghoaXoaBtn.Location = new System.Drawing.Point(684, 35);
            this.hanghoaXoaBtn.Name = "hanghoaXoaBtn";
            this.hanghoaXoaBtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.hanghoaXoaBtn.OnDisabledState.BorderRadius = 10;
            this.hanghoaXoaBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.hanghoaXoaBtn.OnDisabledState.BorderThickness = 1;
            this.hanghoaXoaBtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.hanghoaXoaBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.hanghoaXoaBtn.OnDisabledState.IconLeftImage = null;
            this.hanghoaXoaBtn.OnDisabledState.IconRightImage = null;
            this.hanghoaXoaBtn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.hanghoaXoaBtn.onHoverState.BorderRadius = 10;
            this.hanghoaXoaBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.hanghoaXoaBtn.onHoverState.BorderThickness = 1;
            this.hanghoaXoaBtn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.hanghoaXoaBtn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.hanghoaXoaBtn.onHoverState.IconLeftImage = null;
            this.hanghoaXoaBtn.onHoverState.IconRightImage = null;
            this.hanghoaXoaBtn.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(246)))), ((int)(((byte)(78)))), ((int)(((byte)(96)))));
            this.hanghoaXoaBtn.OnIdleState.BorderRadius = 10;
            this.hanghoaXoaBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.hanghoaXoaBtn.OnIdleState.BorderThickness = 1;
            this.hanghoaXoaBtn.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(246)))), ((int)(((byte)(78)))), ((int)(((byte)(96)))));
            this.hanghoaXoaBtn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.hanghoaXoaBtn.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("hanghoaXoaBtn.OnIdleState.IconLeftImage")));
            this.hanghoaXoaBtn.OnIdleState.IconRightImage = null;
            this.hanghoaXoaBtn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.hanghoaXoaBtn.OnPressedState.BorderRadius = 10;
            this.hanghoaXoaBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.hanghoaXoaBtn.OnPressedState.BorderThickness = 1;
            this.hanghoaXoaBtn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.hanghoaXoaBtn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.hanghoaXoaBtn.OnPressedState.IconLeftImage = null;
            this.hanghoaXoaBtn.OnPressedState.IconRightImage = null;
            this.hanghoaXoaBtn.Size = new System.Drawing.Size(96, 40);
            this.hanghoaXoaBtn.TabIndex = 0;
            this.hanghoaXoaBtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.hanghoaXoaBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.hanghoaXoaBtn.TextMarginLeft = 0;
            this.hanghoaXoaBtn.TextPadding = new System.Windows.Forms.Padding(15, 0, 0, 0);
            this.hanghoaXoaBtn.UseDefaultRadiusAndThickness = true;
            this.hanghoaXoaBtn.Click += new System.EventHandler(this.hanghoaXoaBtn_Click);
            // 
            // bunifuPanel2
            // 
            this.bunifuPanel2.BackgroundColor = System.Drawing.Color.White;
            this.bunifuPanel2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel2.BackgroundImage")));
            this.bunifuPanel2.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel2.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuPanel2.BorderRadius = 20;
            this.bunifuPanel2.BorderThickness = 1;
            this.bunifuPanel2.Location = new System.Drawing.Point(1032, 12);
            this.bunifuPanel2.Name = "bunifuPanel2";
            this.bunifuPanel2.ShowBorders = true;
            this.bunifuPanel2.Size = new System.Drawing.Size(209, 65);
            this.bunifuPanel2.TabIndex = 28;
            // 
            // formHangHoa
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(239)))), ((int)(((byte)(243)))), ((int)(((byte)(249)))));
            this.ClientSize = new System.Drawing.Size(1271, 785);
            this.Controls.Add(this.bunifuPanel2);
            this.Controls.Add(this.hanghoaSearchBtn);
            this.Controls.Add(this.hanghoaSearch);
            this.Controls.Add(this.hanghoaTitle);
            this.Controls.Add(this.hanghoaPanel);
            this.Name = "formHangHoa";
            this.Text = "formHangHoa";
            this.hanghoaPanel.ResumeLayout(false);
            this.hanghoaPanel.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.hanghoaTable)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuLabel hanghoaTitle;
        private Bunifu.UI.WinForms.BunifuTextBox hanghoaSearch;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 hanghoaSearchBtn;
        private Bunifu.UI.WinForms.BunifuPanel hanghoaPanel;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 hanghoaSuaBtn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 hanghoaThemBtn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 hanghoaXoaBtn;
        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel2;
        private Bunifu.UI.WinForms.BunifuLabel nhanvienPanelSub;
        private Bunifu.UI.WinForms.BunifuLabel nhanvienPanelTitle;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 xuatHangHoa;
        private Guna.UI2.WinForms.Guna2DataGridView hanghoaTable;
    }
}