namespace BTL.GUI.InsertForm {
    partial class isrHangHoa {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing) {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent() {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(isrHangHoa));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties25 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties26 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties27 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties28 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties29 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties30 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties31 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties32 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            this.loaihangCbb = new Bunifu.UI.WinForms.BunifuDropdown();
            this.nhacungcapCbb = new Bunifu.UI.WinForms.BunifuDropdown();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.hanghoaBtnAdd = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.txtGia = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtSoLuong = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtTenHang = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtMaHang = new Bunifu.UI.WinForms.BunifuTextBox();
            this.hanghoaBtnUpdate = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.SuspendLayout();
            // 
            // loaihangCbb
            // 
            this.loaihangCbb.BackColor = System.Drawing.Color.Transparent;
            this.loaihangCbb.BackgroundColor = System.Drawing.Color.White;
            this.loaihangCbb.BorderColor = System.Drawing.Color.Silver;
            this.loaihangCbb.BorderRadius = 5;
            this.loaihangCbb.Color = System.Drawing.Color.Silver;
            this.loaihangCbb.Direction = Bunifu.UI.WinForms.BunifuDropdown.Directions.Down;
            this.loaihangCbb.DisabledBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.loaihangCbb.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.loaihangCbb.DisabledColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.loaihangCbb.DisabledForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            this.loaihangCbb.DisabledIndicatorColor = System.Drawing.Color.DarkGray;
            this.loaihangCbb.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.loaihangCbb.DropdownBorderThickness = Bunifu.UI.WinForms.BunifuDropdown.BorderThickness.Thin;
            this.loaihangCbb.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.loaihangCbb.DropDownTextAlign = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.loaihangCbb.FillDropDown = true;
            this.loaihangCbb.FillIndicator = false;
            this.loaihangCbb.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.loaihangCbb.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.loaihangCbb.ForeColor = System.Drawing.Color.Black;
            this.loaihangCbb.FormattingEnabled = true;
            this.loaihangCbb.Icon = null;
            this.loaihangCbb.IndicatorAlignment = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.loaihangCbb.IndicatorColor = System.Drawing.Color.DarkGray;
            this.loaihangCbb.IndicatorLocation = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.loaihangCbb.IndicatorThickness = 2;
            this.loaihangCbb.IsDropdownOpened = false;
            this.loaihangCbb.ItemBackColor = System.Drawing.Color.White;
            this.loaihangCbb.ItemBorderColor = System.Drawing.Color.White;
            this.loaihangCbb.ItemForeColor = System.Drawing.Color.Black;
            this.loaihangCbb.ItemHeight = 36;
            this.loaihangCbb.ItemHighLightColor = System.Drawing.Color.DodgerBlue;
            this.loaihangCbb.ItemHighLightForeColor = System.Drawing.Color.White;
            this.loaihangCbb.ItemTopMargin = 3;
            this.loaihangCbb.Location = new System.Drawing.Point(88, 375);
            this.loaihangCbb.Name = "loaihangCbb";
            this.loaihangCbb.Size = new System.Drawing.Size(260, 42);
            this.loaihangCbb.TabIndex = 6;
            this.loaihangCbb.Text = "Loại hàng";
            this.loaihangCbb.TextAlignment = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.loaihangCbb.TextLeftMargin = 5;
            // 
            // nhacungcapCbb
            // 
            this.nhacungcapCbb.BackColor = System.Drawing.Color.Transparent;
            this.nhacungcapCbb.BackgroundColor = System.Drawing.Color.White;
            this.nhacungcapCbb.BorderColor = System.Drawing.Color.Silver;
            this.nhacungcapCbb.BorderRadius = 5;
            this.nhacungcapCbb.Color = System.Drawing.Color.Silver;
            this.nhacungcapCbb.Direction = Bunifu.UI.WinForms.BunifuDropdown.Directions.Down;
            this.nhacungcapCbb.DisabledBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.nhacungcapCbb.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.nhacungcapCbb.DisabledColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.nhacungcapCbb.DisabledForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            this.nhacungcapCbb.DisabledIndicatorColor = System.Drawing.Color.DarkGray;
            this.nhacungcapCbb.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.nhacungcapCbb.DropdownBorderThickness = Bunifu.UI.WinForms.BunifuDropdown.BorderThickness.Thin;
            this.nhacungcapCbb.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.nhacungcapCbb.DropDownTextAlign = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.nhacungcapCbb.FillDropDown = true;
            this.nhacungcapCbb.FillIndicator = false;
            this.nhacungcapCbb.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.nhacungcapCbb.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.nhacungcapCbb.ForeColor = System.Drawing.Color.Black;
            this.nhacungcapCbb.FormattingEnabled = true;
            this.nhacungcapCbb.Icon = null;
            this.nhacungcapCbb.IndicatorAlignment = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.nhacungcapCbb.IndicatorColor = System.Drawing.Color.DarkGray;
            this.nhacungcapCbb.IndicatorLocation = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.nhacungcapCbb.IndicatorThickness = 2;
            this.nhacungcapCbb.IsDropdownOpened = false;
            this.nhacungcapCbb.ItemBackColor = System.Drawing.Color.White;
            this.nhacungcapCbb.ItemBorderColor = System.Drawing.Color.White;
            this.nhacungcapCbb.ItemForeColor = System.Drawing.Color.Black;
            this.nhacungcapCbb.ItemHeight = 36;
            this.nhacungcapCbb.ItemHighLightColor = System.Drawing.Color.DodgerBlue;
            this.nhacungcapCbb.ItemHighLightForeColor = System.Drawing.Color.White;
            this.nhacungcapCbb.ItemTopMargin = 3;
            this.nhacungcapCbb.Location = new System.Drawing.Point(88, 436);
            this.nhacungcapCbb.Name = "nhacungcapCbb";
            this.nhacungcapCbb.Size = new System.Drawing.Size(260, 42);
            this.nhacungcapCbb.TabIndex = 7;
            this.nhacungcapCbb.Text = "Nhà cung cấp";
            this.nhacungcapCbb.TextAlignment = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.nhacungcapCbb.TextLeftMargin = 5;
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.Font = new System.Drawing.Font("Segoe UI Semibold", 13F, System.Drawing.FontStyle.Bold);
            this.bunifuLabel1.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(79)))), ((int)(((byte)(79)))), ((int)(((byte)(79)))));
            this.bunifuLabel1.Location = new System.Drawing.Point(162, 36);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(92, 30);
            this.bunifuLabel1.TabIndex = 9;
            this.bunifuLabel1.Text = "Máy Tính";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // hanghoaBtnAdd
            // 
            this.hanghoaBtnAdd.AllowAnimations = true;
            this.hanghoaBtnAdd.AllowMouseEffects = true;
            this.hanghoaBtnAdd.AllowToggling = false;
            this.hanghoaBtnAdd.AnimationSpeed = 200;
            this.hanghoaBtnAdd.AutoGenerateColors = false;
            this.hanghoaBtnAdd.AutoRoundBorders = false;
            this.hanghoaBtnAdd.AutoSizeLeftIcon = true;
            this.hanghoaBtnAdd.AutoSizeRightIcon = true;
            this.hanghoaBtnAdd.BackColor = System.Drawing.Color.Transparent;
            this.hanghoaBtnAdd.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.hanghoaBtnAdd.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("hanghoaBtnAdd.BackgroundImage")));
            this.hanghoaBtnAdd.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.hanghoaBtnAdd.ButtonText = "Thêm";
            this.hanghoaBtnAdd.ButtonTextMarginLeft = 0;
            this.hanghoaBtnAdd.ColorContrastOnClick = 45;
            this.hanghoaBtnAdd.ColorContrastOnHover = 45;
            this.hanghoaBtnAdd.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.hanghoaBtnAdd.CustomizableEdges = borderEdges3;
            this.hanghoaBtnAdd.DialogResult = System.Windows.Forms.DialogResult.None;
            this.hanghoaBtnAdd.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.hanghoaBtnAdd.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.hanghoaBtnAdd.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.hanghoaBtnAdd.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.hanghoaBtnAdd.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.hanghoaBtnAdd.ForeColor = System.Drawing.Color.White;
            this.hanghoaBtnAdd.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.hanghoaBtnAdd.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.hanghoaBtnAdd.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.hanghoaBtnAdd.IconMarginLeft = 11;
            this.hanghoaBtnAdd.IconPadding = 10;
            this.hanghoaBtnAdd.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.hanghoaBtnAdd.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.hanghoaBtnAdd.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.hanghoaBtnAdd.IconSize = 25;
            this.hanghoaBtnAdd.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.hanghoaBtnAdd.IdleBorderRadius = 15;
            this.hanghoaBtnAdd.IdleBorderThickness = 1;
            this.hanghoaBtnAdd.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.hanghoaBtnAdd.IdleIconLeftImage = null;
            this.hanghoaBtnAdd.IdleIconRightImage = null;
            this.hanghoaBtnAdd.IndicateFocus = false;
            this.hanghoaBtnAdd.Location = new System.Drawing.Point(231, 500);
            this.hanghoaBtnAdd.Name = "hanghoaBtnAdd";
            this.hanghoaBtnAdd.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.hanghoaBtnAdd.OnDisabledState.BorderRadius = 15;
            this.hanghoaBtnAdd.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.hanghoaBtnAdd.OnDisabledState.BorderThickness = 1;
            this.hanghoaBtnAdd.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.hanghoaBtnAdd.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.hanghoaBtnAdd.OnDisabledState.IconLeftImage = null;
            this.hanghoaBtnAdd.OnDisabledState.IconRightImage = null;
            this.hanghoaBtnAdd.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.hanghoaBtnAdd.onHoverState.BorderRadius = 15;
            this.hanghoaBtnAdd.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.hanghoaBtnAdd.onHoverState.BorderThickness = 1;
            this.hanghoaBtnAdd.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.hanghoaBtnAdd.onHoverState.ForeColor = System.Drawing.Color.White;
            this.hanghoaBtnAdd.onHoverState.IconLeftImage = null;
            this.hanghoaBtnAdd.onHoverState.IconRightImage = null;
            this.hanghoaBtnAdd.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.hanghoaBtnAdd.OnIdleState.BorderRadius = 15;
            this.hanghoaBtnAdd.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.hanghoaBtnAdd.OnIdleState.BorderThickness = 1;
            this.hanghoaBtnAdd.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.hanghoaBtnAdd.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.hanghoaBtnAdd.OnIdleState.IconLeftImage = null;
            this.hanghoaBtnAdd.OnIdleState.IconRightImage = null;
            this.hanghoaBtnAdd.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.hanghoaBtnAdd.OnPressedState.BorderRadius = 15;
            this.hanghoaBtnAdd.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.hanghoaBtnAdd.OnPressedState.BorderThickness = 1;
            this.hanghoaBtnAdd.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.hanghoaBtnAdd.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.hanghoaBtnAdd.OnPressedState.IconLeftImage = null;
            this.hanghoaBtnAdd.OnPressedState.IconRightImage = null;
            this.hanghoaBtnAdd.Size = new System.Drawing.Size(117, 44);
            this.hanghoaBtnAdd.TabIndex = 8;
            this.hanghoaBtnAdd.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.hanghoaBtnAdd.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.hanghoaBtnAdd.TextMarginLeft = 0;
            this.hanghoaBtnAdd.TextPadding = new System.Windows.Forms.Padding(0);
            this.hanghoaBtnAdd.UseDefaultRadiusAndThickness = true;
            this.hanghoaBtnAdd.Click += new System.EventHandler(this.bunifuButton21_Click);
            // 
            // txtGia
            // 
            this.txtGia.AcceptsReturn = false;
            this.txtGia.AcceptsTab = false;
            this.txtGia.AnimationSpeed = 200;
            this.txtGia.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtGia.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtGia.AutoSizeHeight = true;
            this.txtGia.BackColor = System.Drawing.Color.White;
            this.txtGia.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtGia.BackgroundImage")));
            this.txtGia.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtGia.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtGia.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtGia.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtGia.BorderRadius = 10;
            this.txtGia.BorderThickness = 1;
            this.txtGia.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtGia.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtGia.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtGia.DefaultText = "";
            this.txtGia.FillColor = System.Drawing.Color.White;
            this.txtGia.HideSelection = true;
            this.txtGia.IconLeft = null;
            this.txtGia.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtGia.IconPadding = 10;
            this.txtGia.IconRight = null;
            this.txtGia.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtGia.Lines = new string[0];
            this.txtGia.Location = new System.Drawing.Point(88, 236);
            this.txtGia.MaxLength = 32767;
            this.txtGia.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtGia.Modified = false;
            this.txtGia.Multiline = false;
            this.txtGia.Name = "txtGia";
            stateProperties17.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtGia.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtGia.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtGia.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Silver;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtGia.OnIdleState = stateProperties20;
            this.txtGia.Padding = new System.Windows.Forms.Padding(3);
            this.txtGia.PasswordChar = '\0';
            this.txtGia.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtGia.PlaceholderText = "Giá";
            this.txtGia.ReadOnly = false;
            this.txtGia.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtGia.SelectedText = "";
            this.txtGia.SelectionLength = 0;
            this.txtGia.SelectionStart = 0;
            this.txtGia.ShortcutsEnabled = true;
            this.txtGia.Size = new System.Drawing.Size(260, 43);
            this.txtGia.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtGia.TabIndex = 5;
            this.txtGia.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtGia.TextMarginBottom = 0;
            this.txtGia.TextMarginLeft = 3;
            this.txtGia.TextMarginTop = 1;
            this.txtGia.TextPlaceholder = "Giá";
            this.txtGia.UseSystemPasswordChar = false;
            this.txtGia.WordWrap = true;
            // 
            // txtSoLuong
            // 
            this.txtSoLuong.AcceptsReturn = false;
            this.txtSoLuong.AcceptsTab = false;
            this.txtSoLuong.AnimationSpeed = 200;
            this.txtSoLuong.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtSoLuong.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtSoLuong.AutoSizeHeight = true;
            this.txtSoLuong.BackColor = System.Drawing.Color.White;
            this.txtSoLuong.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtSoLuong.BackgroundImage")));
            this.txtSoLuong.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtSoLuong.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtSoLuong.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtSoLuong.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtSoLuong.BorderRadius = 10;
            this.txtSoLuong.BorderThickness = 1;
            this.txtSoLuong.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtSoLuong.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSoLuong.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtSoLuong.DefaultText = "";
            this.txtSoLuong.FillColor = System.Drawing.Color.White;
            this.txtSoLuong.HideSelection = true;
            this.txtSoLuong.IconLeft = null;
            this.txtSoLuong.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSoLuong.IconPadding = 10;
            this.txtSoLuong.IconRight = null;
            this.txtSoLuong.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSoLuong.Lines = new string[0];
            this.txtSoLuong.Location = new System.Drawing.Point(88, 307);
            this.txtSoLuong.MaxLength = 32767;
            this.txtSoLuong.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtSoLuong.Modified = false;
            this.txtSoLuong.Multiline = false;
            this.txtSoLuong.Name = "txtSoLuong";
            stateProperties21.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtSoLuong.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties22.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties22.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtSoLuong.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtSoLuong.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.Silver;
            stateProperties24.FillColor = System.Drawing.Color.White;
            stateProperties24.ForeColor = System.Drawing.Color.Empty;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtSoLuong.OnIdleState = stateProperties24;
            this.txtSoLuong.Padding = new System.Windows.Forms.Padding(3);
            this.txtSoLuong.PasswordChar = '\0';
            this.txtSoLuong.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtSoLuong.PlaceholderText = "Số lượng";
            this.txtSoLuong.ReadOnly = false;
            this.txtSoLuong.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtSoLuong.SelectedText = "";
            this.txtSoLuong.SelectionLength = 0;
            this.txtSoLuong.SelectionStart = 0;
            this.txtSoLuong.ShortcutsEnabled = true;
            this.txtSoLuong.Size = new System.Drawing.Size(260, 43);
            this.txtSoLuong.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtSoLuong.TabIndex = 4;
            this.txtSoLuong.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtSoLuong.TextMarginBottom = 0;
            this.txtSoLuong.TextMarginLeft = 3;
            this.txtSoLuong.TextMarginTop = 1;
            this.txtSoLuong.TextPlaceholder = "Số lượng";
            this.txtSoLuong.UseSystemPasswordChar = false;
            this.txtSoLuong.WordWrap = true;
            // 
            // txtTenHang
            // 
            this.txtTenHang.AcceptsReturn = false;
            this.txtTenHang.AcceptsTab = false;
            this.txtTenHang.AnimationSpeed = 200;
            this.txtTenHang.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtTenHang.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtTenHang.AutoSizeHeight = true;
            this.txtTenHang.BackColor = System.Drawing.Color.White;
            this.txtTenHang.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtTenHang.BackgroundImage")));
            this.txtTenHang.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtTenHang.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtTenHang.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtTenHang.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtTenHang.BorderRadius = 10;
            this.txtTenHang.BorderThickness = 1;
            this.txtTenHang.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtTenHang.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtTenHang.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtTenHang.DefaultText = "";
            this.txtTenHang.FillColor = System.Drawing.Color.White;
            this.txtTenHang.HideSelection = true;
            this.txtTenHang.IconLeft = null;
            this.txtTenHang.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtTenHang.IconPadding = 10;
            this.txtTenHang.IconRight = null;
            this.txtTenHang.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtTenHang.Lines = new string[0];
            this.txtTenHang.Location = new System.Drawing.Point(88, 164);
            this.txtTenHang.MaxLength = 32767;
            this.txtTenHang.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtTenHang.Modified = false;
            this.txtTenHang.Multiline = false;
            this.txtTenHang.Name = "txtTenHang";
            stateProperties25.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties25.FillColor = System.Drawing.Color.Empty;
            stateProperties25.ForeColor = System.Drawing.Color.Empty;
            stateProperties25.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtTenHang.OnActiveState = stateProperties25;
            stateProperties26.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties26.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties26.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties26.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtTenHang.OnDisabledState = stateProperties26;
            stateProperties27.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties27.FillColor = System.Drawing.Color.Empty;
            stateProperties27.ForeColor = System.Drawing.Color.Empty;
            stateProperties27.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtTenHang.OnHoverState = stateProperties27;
            stateProperties28.BorderColor = System.Drawing.Color.Silver;
            stateProperties28.FillColor = System.Drawing.Color.White;
            stateProperties28.ForeColor = System.Drawing.Color.Empty;
            stateProperties28.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtTenHang.OnIdleState = stateProperties28;
            this.txtTenHang.Padding = new System.Windows.Forms.Padding(3);
            this.txtTenHang.PasswordChar = '\0';
            this.txtTenHang.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtTenHang.PlaceholderText = "Tên hàng";
            this.txtTenHang.ReadOnly = false;
            this.txtTenHang.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtTenHang.SelectedText = "";
            this.txtTenHang.SelectionLength = 0;
            this.txtTenHang.SelectionStart = 0;
            this.txtTenHang.ShortcutsEnabled = true;
            this.txtTenHang.Size = new System.Drawing.Size(260, 43);
            this.txtTenHang.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtTenHang.TabIndex = 1;
            this.txtTenHang.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtTenHang.TextMarginBottom = 0;
            this.txtTenHang.TextMarginLeft = 3;
            this.txtTenHang.TextMarginTop = 1;
            this.txtTenHang.TextPlaceholder = "Tên hàng";
            this.txtTenHang.UseSystemPasswordChar = false;
            this.txtTenHang.WordWrap = true;
            // 
            // txtMaHang
            // 
            this.txtMaHang.AcceptsReturn = false;
            this.txtMaHang.AcceptsTab = false;
            this.txtMaHang.AnimationSpeed = 200;
            this.txtMaHang.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtMaHang.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtMaHang.AutoSizeHeight = true;
            this.txtMaHang.BackColor = System.Drawing.Color.White;
            this.txtMaHang.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtMaHang.BackgroundImage")));
            this.txtMaHang.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtMaHang.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtMaHang.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtMaHang.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtMaHang.BorderRadius = 10;
            this.txtMaHang.BorderThickness = 1;
            this.txtMaHang.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtMaHang.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtMaHang.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtMaHang.DefaultText = "";
            this.txtMaHang.FillColor = System.Drawing.Color.White;
            this.txtMaHang.HideSelection = true;
            this.txtMaHang.IconLeft = null;
            this.txtMaHang.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtMaHang.IconPadding = 10;
            this.txtMaHang.IconRight = null;
            this.txtMaHang.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtMaHang.Lines = new string[0];
            this.txtMaHang.Location = new System.Drawing.Point(88, 95);
            this.txtMaHang.MaxLength = 32767;
            this.txtMaHang.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtMaHang.Modified = false;
            this.txtMaHang.Multiline = false;
            this.txtMaHang.Name = "txtMaHang";
            stateProperties29.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties29.FillColor = System.Drawing.Color.Empty;
            stateProperties29.ForeColor = System.Drawing.Color.Empty;
            stateProperties29.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtMaHang.OnActiveState = stateProperties29;
            stateProperties30.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties30.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties30.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties30.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtMaHang.OnDisabledState = stateProperties30;
            stateProperties31.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties31.FillColor = System.Drawing.Color.Empty;
            stateProperties31.ForeColor = System.Drawing.Color.Empty;
            stateProperties31.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtMaHang.OnHoverState = stateProperties31;
            stateProperties32.BorderColor = System.Drawing.Color.Silver;
            stateProperties32.FillColor = System.Drawing.Color.White;
            stateProperties32.ForeColor = System.Drawing.Color.Empty;
            stateProperties32.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtMaHang.OnIdleState = stateProperties32;
            this.txtMaHang.Padding = new System.Windows.Forms.Padding(3);
            this.txtMaHang.PasswordChar = '\0';
            this.txtMaHang.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtMaHang.PlaceholderText = "Mã hàng";
            this.txtMaHang.ReadOnly = false;
            this.txtMaHang.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtMaHang.SelectedText = "";
            this.txtMaHang.SelectionLength = 0;
            this.txtMaHang.SelectionStart = 0;
            this.txtMaHang.ShortcutsEnabled = true;
            this.txtMaHang.Size = new System.Drawing.Size(260, 43);
            this.txtMaHang.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtMaHang.TabIndex = 0;
            this.txtMaHang.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtMaHang.TextMarginBottom = 0;
            this.txtMaHang.TextMarginLeft = 3;
            this.txtMaHang.TextMarginTop = 1;
            this.txtMaHang.TextPlaceholder = "Mã hàng";
            this.txtMaHang.UseSystemPasswordChar = false;
            this.txtMaHang.WordWrap = true;
            // 
            // hanghoaBtnUpdate
            // 
            this.hanghoaBtnUpdate.AllowAnimations = true;
            this.hanghoaBtnUpdate.AllowMouseEffects = true;
            this.hanghoaBtnUpdate.AllowToggling = false;
            this.hanghoaBtnUpdate.AnimationSpeed = 200;
            this.hanghoaBtnUpdate.AutoGenerateColors = false;
            this.hanghoaBtnUpdate.AutoRoundBorders = false;
            this.hanghoaBtnUpdate.AutoSizeLeftIcon = true;
            this.hanghoaBtnUpdate.AutoSizeRightIcon = true;
            this.hanghoaBtnUpdate.BackColor = System.Drawing.Color.Transparent;
            this.hanghoaBtnUpdate.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.hanghoaBtnUpdate.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("hanghoaBtnUpdate.BackgroundImage")));
            this.hanghoaBtnUpdate.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.hanghoaBtnUpdate.ButtonText = "Cập nhật";
            this.hanghoaBtnUpdate.ButtonTextMarginLeft = 0;
            this.hanghoaBtnUpdate.ColorContrastOnClick = 45;
            this.hanghoaBtnUpdate.ColorContrastOnHover = 45;
            this.hanghoaBtnUpdate.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.hanghoaBtnUpdate.CustomizableEdges = borderEdges4;
            this.hanghoaBtnUpdate.DialogResult = System.Windows.Forms.DialogResult.None;
            this.hanghoaBtnUpdate.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.hanghoaBtnUpdate.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.hanghoaBtnUpdate.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.hanghoaBtnUpdate.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.hanghoaBtnUpdate.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.hanghoaBtnUpdate.ForeColor = System.Drawing.Color.White;
            this.hanghoaBtnUpdate.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.hanghoaBtnUpdate.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.hanghoaBtnUpdate.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.hanghoaBtnUpdate.IconMarginLeft = 11;
            this.hanghoaBtnUpdate.IconPadding = 10;
            this.hanghoaBtnUpdate.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.hanghoaBtnUpdate.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.hanghoaBtnUpdate.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.hanghoaBtnUpdate.IconSize = 25;
            this.hanghoaBtnUpdate.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.hanghoaBtnUpdate.IdleBorderRadius = 15;
            this.hanghoaBtnUpdate.IdleBorderThickness = 1;
            this.hanghoaBtnUpdate.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.hanghoaBtnUpdate.IdleIconLeftImage = null;
            this.hanghoaBtnUpdate.IdleIconRightImage = null;
            this.hanghoaBtnUpdate.IndicateFocus = false;
            this.hanghoaBtnUpdate.Location = new System.Drawing.Point(88, 500);
            this.hanghoaBtnUpdate.Name = "hanghoaBtnUpdate";
            this.hanghoaBtnUpdate.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.hanghoaBtnUpdate.OnDisabledState.BorderRadius = 15;
            this.hanghoaBtnUpdate.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.hanghoaBtnUpdate.OnDisabledState.BorderThickness = 1;
            this.hanghoaBtnUpdate.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.hanghoaBtnUpdate.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.hanghoaBtnUpdate.OnDisabledState.IconLeftImage = null;
            this.hanghoaBtnUpdate.OnDisabledState.IconRightImage = null;
            this.hanghoaBtnUpdate.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.hanghoaBtnUpdate.onHoverState.BorderRadius = 15;
            this.hanghoaBtnUpdate.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.hanghoaBtnUpdate.onHoverState.BorderThickness = 1;
            this.hanghoaBtnUpdate.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.hanghoaBtnUpdate.onHoverState.ForeColor = System.Drawing.Color.White;
            this.hanghoaBtnUpdate.onHoverState.IconLeftImage = null;
            this.hanghoaBtnUpdate.onHoverState.IconRightImage = null;
            this.hanghoaBtnUpdate.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.hanghoaBtnUpdate.OnIdleState.BorderRadius = 15;
            this.hanghoaBtnUpdate.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.hanghoaBtnUpdate.OnIdleState.BorderThickness = 1;
            this.hanghoaBtnUpdate.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.hanghoaBtnUpdate.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.hanghoaBtnUpdate.OnIdleState.IconLeftImage = null;
            this.hanghoaBtnUpdate.OnIdleState.IconRightImage = null;
            this.hanghoaBtnUpdate.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.hanghoaBtnUpdate.OnPressedState.BorderRadius = 15;
            this.hanghoaBtnUpdate.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.hanghoaBtnUpdate.OnPressedState.BorderThickness = 1;
            this.hanghoaBtnUpdate.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.hanghoaBtnUpdate.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.hanghoaBtnUpdate.OnPressedState.IconLeftImage = null;
            this.hanghoaBtnUpdate.OnPressedState.IconRightImage = null;
            this.hanghoaBtnUpdate.Size = new System.Drawing.Size(117, 44);
            this.hanghoaBtnUpdate.TabIndex = 10;
            this.hanghoaBtnUpdate.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.hanghoaBtnUpdate.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.hanghoaBtnUpdate.TextMarginLeft = 0;
            this.hanghoaBtnUpdate.TextPadding = new System.Windows.Forms.Padding(0);
            this.hanghoaBtnUpdate.UseDefaultRadiusAndThickness = true;
            this.hanghoaBtnUpdate.Click += new System.EventHandler(this.hanghoaBtnUpdate_Click);
            // 
            // isrHangHoa
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.White;
            this.ClientSize = new System.Drawing.Size(429, 577);
            this.Controls.Add(this.hanghoaBtnUpdate);
            this.Controls.Add(this.bunifuLabel1);
            this.Controls.Add(this.hanghoaBtnAdd);
            this.Controls.Add(this.nhacungcapCbb);
            this.Controls.Add(this.loaihangCbb);
            this.Controls.Add(this.txtGia);
            this.Controls.Add(this.txtSoLuong);
            this.Controls.Add(this.txtTenHang);
            this.Controls.Add(this.txtMaHang);
            this.Name = "isrHangHoa";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Máy Tính";
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuTextBox txtMaHang;
        private Bunifu.UI.WinForms.BunifuTextBox txtTenHang;
        private Bunifu.UI.WinForms.BunifuTextBox txtSoLuong;
        private Bunifu.UI.WinForms.BunifuTextBox txtGia;
        private Bunifu.UI.WinForms.BunifuDropdown loaihangCbb;
        private Bunifu.UI.WinForms.BunifuDropdown nhacungcapCbb;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 hanghoaBtnAdd;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 hanghoaBtnUpdate;
    }
}