namespace BTL.GUI
{
    partial class nhanvienPanel
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(nhanvienPanel));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle1 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle3 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle4 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle5 = new System.Windows.Forms.DataGridViewCellStyle();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            this.nhanvienSearchBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.nhanvienSearch = new Bunifu.UI.WinForms.BunifuTextBox();
            this.nhanvienTitle = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuPanel1 = new Bunifu.UI.WinForms.BunifuPanel();
            this.nhanvienTable = new Guna.UI2.WinForms.Guna2DataGridView();
            this.xuatNhanVien = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.nhanvienPanelSub = new Bunifu.UI.WinForms.BunifuLabel();
            this.nhanvienPanelTitle = new Bunifu.UI.WinForms.BunifuLabel();
            this.hanghoaLuuBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.hanghoaXoaBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.hanghoaThemBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.bunifuPanel2 = new Bunifu.UI.WinForms.BunifuPanel();
            this.bunifuPanel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.nhanvienTable)).BeginInit();
            this.SuspendLayout();
            // 
            // nhanvienSearchBtn
            // 
            this.nhanvienSearchBtn.AllowAnimations = true;
            this.nhanvienSearchBtn.AllowMouseEffects = true;
            this.nhanvienSearchBtn.AllowToggling = false;
            this.nhanvienSearchBtn.AnimationSpeed = 200;
            this.nhanvienSearchBtn.AutoGenerateColors = false;
            this.nhanvienSearchBtn.AutoRoundBorders = false;
            this.nhanvienSearchBtn.AutoSizeLeftIcon = true;
            this.nhanvienSearchBtn.AutoSizeRightIcon = true;
            this.nhanvienSearchBtn.BackColor = System.Drawing.Color.Transparent;
            this.nhanvienSearchBtn.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.nhanvienSearchBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("nhanvienSearchBtn.BackgroundImage")));
            this.nhanvienSearchBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.nhanvienSearchBtn.ButtonText = "";
            this.nhanvienSearchBtn.ButtonTextMarginLeft = 0;
            this.nhanvienSearchBtn.ColorContrastOnClick = 45;
            this.nhanvienSearchBtn.ColorContrastOnHover = 45;
            this.nhanvienSearchBtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.nhanvienSearchBtn.CustomizableEdges = borderEdges1;
            this.nhanvienSearchBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.nhanvienSearchBtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.nhanvienSearchBtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.nhanvienSearchBtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.nhanvienSearchBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.nhanvienSearchBtn.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.nhanvienSearchBtn.ForeColor = System.Drawing.Color.White;
            this.nhanvienSearchBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.nhanvienSearchBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.nhanvienSearchBtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.nhanvienSearchBtn.IconMarginLeft = 11;
            this.nhanvienSearchBtn.IconPadding = 10;
            this.nhanvienSearchBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.nhanvienSearchBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.nhanvienSearchBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.nhanvienSearchBtn.IconSize = 25;
            this.nhanvienSearchBtn.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.nhanvienSearchBtn.IdleBorderRadius = 25;
            this.nhanvienSearchBtn.IdleBorderThickness = 1;
            this.nhanvienSearchBtn.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.nhanvienSearchBtn.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("nhanvienSearchBtn.IdleIconLeftImage")));
            this.nhanvienSearchBtn.IdleIconRightImage = null;
            this.nhanvienSearchBtn.IndicateFocus = false;
            this.nhanvienSearchBtn.Location = new System.Drawing.Point(644, 23);
            this.nhanvienSearchBtn.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.nhanvienSearchBtn.Name = "nhanvienSearchBtn";
            this.nhanvienSearchBtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.nhanvienSearchBtn.OnDisabledState.BorderRadius = 25;
            this.nhanvienSearchBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.nhanvienSearchBtn.OnDisabledState.BorderThickness = 1;
            this.nhanvienSearchBtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.nhanvienSearchBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.nhanvienSearchBtn.OnDisabledState.IconLeftImage = null;
            this.nhanvienSearchBtn.OnDisabledState.IconRightImage = null;
            this.nhanvienSearchBtn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.nhanvienSearchBtn.onHoverState.BorderRadius = 25;
            this.nhanvienSearchBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.nhanvienSearchBtn.onHoverState.BorderThickness = 1;
            this.nhanvienSearchBtn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.nhanvienSearchBtn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.nhanvienSearchBtn.onHoverState.IconLeftImage = null;
            this.nhanvienSearchBtn.onHoverState.IconRightImage = null;
            this.nhanvienSearchBtn.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.nhanvienSearchBtn.OnIdleState.BorderRadius = 25;
            this.nhanvienSearchBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.nhanvienSearchBtn.OnIdleState.BorderThickness = 1;
            this.nhanvienSearchBtn.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.nhanvienSearchBtn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.nhanvienSearchBtn.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("nhanvienSearchBtn.OnIdleState.IconLeftImage")));
            this.nhanvienSearchBtn.OnIdleState.IconRightImage = null;
            this.nhanvienSearchBtn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.nhanvienSearchBtn.OnPressedState.BorderRadius = 25;
            this.nhanvienSearchBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.nhanvienSearchBtn.OnPressedState.BorderThickness = 1;
            this.nhanvienSearchBtn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.nhanvienSearchBtn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.nhanvienSearchBtn.OnPressedState.IconLeftImage = null;
            this.nhanvienSearchBtn.OnPressedState.IconRightImage = null;
            this.nhanvienSearchBtn.Size = new System.Drawing.Size(43, 39);
            this.nhanvienSearchBtn.TabIndex = 19;
            this.nhanvienSearchBtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.nhanvienSearchBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.nhanvienSearchBtn.TextMarginLeft = 0;
            this.nhanvienSearchBtn.TextPadding = new System.Windows.Forms.Padding(0);
            this.nhanvienSearchBtn.UseDefaultRadiusAndThickness = true;
            this.nhanvienSearchBtn.Click += new System.EventHandler(this.nhanvienSearchBtn_Click);
            // 
            // nhanvienSearch
            // 
            this.nhanvienSearch.AcceptsReturn = false;
            this.nhanvienSearch.AcceptsTab = false;
            this.nhanvienSearch.AnimationSpeed = 200;
            this.nhanvienSearch.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.nhanvienSearch.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.nhanvienSearch.AutoSizeHeight = true;
            this.nhanvienSearch.BackColor = System.Drawing.Color.Transparent;
            this.nhanvienSearch.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("nhanvienSearch.BackgroundImage")));
            this.nhanvienSearch.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.nhanvienSearch.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.nhanvienSearch.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.nhanvienSearch.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(235)))), ((int)(((byte)(235)))), ((int)(((byte)(235)))));
            this.nhanvienSearch.BorderRadius = 20;
            this.nhanvienSearch.BorderThickness = 1;
            this.nhanvienSearch.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.nhanvienSearch.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.nhanvienSearch.DefaultFont = new System.Drawing.Font("Segoe UI", 10F);
            this.nhanvienSearch.DefaultText = "";
            this.nhanvienSearch.FillColor = System.Drawing.Color.White;
            this.nhanvienSearch.HideSelection = true;
            this.nhanvienSearch.IconLeft = ((System.Drawing.Image)(resources.GetObject("nhanvienSearch.IconLeft")));
            this.nhanvienSearch.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.nhanvienSearch.IconPadding = 10;
            this.nhanvienSearch.IconRight = null;
            this.nhanvienSearch.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.nhanvienSearch.Lines = new string[0];
            this.nhanvienSearch.Location = new System.Drawing.Point(271, 21);
            this.nhanvienSearch.Margin = new System.Windows.Forms.Padding(20, 3, 3, 3);
            this.nhanvienSearch.MaxLength = 32767;
            this.nhanvienSearch.MinimumSize = new System.Drawing.Size(1, 1);
            this.nhanvienSearch.Modified = false;
            this.nhanvienSearch.Multiline = false;
            this.nhanvienSearch.Name = "nhanvienSearch";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.nhanvienSearch.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.nhanvienSearch.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.nhanvienSearch.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(235)))), ((int)(((byte)(235)))), ((int)(((byte)(235)))));
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.nhanvienSearch.OnIdleState = stateProperties4;
            this.nhanvienSearch.Padding = new System.Windows.Forms.Padding(40, 3, 3, 3);
            this.nhanvienSearch.PasswordChar = '\0';
            this.nhanvienSearch.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.nhanvienSearch.PlaceholderText = "Tìm kiếm";
            this.nhanvienSearch.ReadOnly = false;
            this.nhanvienSearch.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.nhanvienSearch.SelectedText = "";
            this.nhanvienSearch.SelectionLength = 0;
            this.nhanvienSearch.SelectionStart = 0;
            this.nhanvienSearch.ShortcutsEnabled = true;
            this.nhanvienSearch.Size = new System.Drawing.Size(367, 41);
            this.nhanvienSearch.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.nhanvienSearch.TabIndex = 18;
            this.nhanvienSearch.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.nhanvienSearch.TextMarginBottom = 0;
            this.nhanvienSearch.TextMarginLeft = 15;
            this.nhanvienSearch.TextMarginTop = 0;
            this.nhanvienSearch.TextPlaceholder = "Tìm kiếm";
            this.nhanvienSearch.UseSystemPasswordChar = false;
            this.nhanvienSearch.WordWrap = true;
            this.nhanvienSearch.KeyDown += new System.Windows.Forms.KeyEventHandler(this.nhanvienSearch_KeyDown);
            // 
            // nhanvienTitle
            // 
            this.nhanvienTitle.AllowParentOverrides = false;
            this.nhanvienTitle.AutoEllipsis = false;
            this.nhanvienTitle.Cursor = System.Windows.Forms.Cursors.Default;
            this.nhanvienTitle.CursorType = System.Windows.Forms.Cursors.Default;
            this.nhanvienTitle.Font = new System.Drawing.Font("Segoe UI Semibold", 13F, System.Drawing.FontStyle.Bold);
            this.nhanvienTitle.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(79)))), ((int)(((byte)(79)))), ((int)(((byte)(79)))));
            this.nhanvienTitle.Location = new System.Drawing.Point(133, 23);
            this.nhanvienTitle.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.nhanvienTitle.Name = "nhanvienTitle";
            this.nhanvienTitle.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.nhanvienTitle.Size = new System.Drawing.Size(105, 30);
            this.nhanvienTitle.TabIndex = 17;
            this.nhanvienTitle.Text = "Nhân Viên";
            this.nhanvienTitle.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.nhanvienTitle.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuPanel1
            // 
            this.bunifuPanel1.BackgroundColor = System.Drawing.Color.White;
            this.bunifuPanel1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel1.BackgroundImage")));
            this.bunifuPanel1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel1.BorderColor = System.Drawing.Color.Gainsboro;
            this.bunifuPanel1.BorderRadius = 25;
            this.bunifuPanel1.BorderThickness = 1;
            this.bunifuPanel1.Controls.Add(this.nhanvienTable);
            this.bunifuPanel1.Controls.Add(this.xuatNhanVien);
            this.bunifuPanel1.Controls.Add(this.nhanvienPanelSub);
            this.bunifuPanel1.Controls.Add(this.nhanvienPanelTitle);
            this.bunifuPanel1.Controls.Add(this.hanghoaLuuBtn);
            this.bunifuPanel1.Controls.Add(this.hanghoaXoaBtn);
            this.bunifuPanel1.Controls.Add(this.hanghoaThemBtn);
            this.bunifuPanel1.Location = new System.Drawing.Point(133, 127);
            this.bunifuPanel1.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.bunifuPanel1.Name = "bunifuPanel1";
            this.bunifuPanel1.ShowBorders = true;
            this.bunifuPanel1.Size = new System.Drawing.Size(1107, 630);
            this.bunifuPanel1.TabIndex = 25;
            // 
            // nhanvienTable
            // 
            this.nhanvienTable.AllowUserToAddRows = false;
            this.nhanvienTable.AllowUserToDeleteRows = false;
            dataGridViewCellStyle1.BackColor = System.Drawing.Color.White;
            this.nhanvienTable.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle1;
            this.nhanvienTable.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.nhanvienTable.BackgroundColor = System.Drawing.Color.White;
            this.nhanvienTable.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.nhanvienTable.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.nhanvienTable.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle2.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle2.BackColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.Font = new System.Drawing.Font("Segoe UI Semibold", 10.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            dataGridViewCellStyle2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(33)))), ((int)(((byte)(35)))), ((int)(((byte)(74)))));
            dataGridViewCellStyle2.Padding = new System.Windows.Forms.Padding(15, 0, 15, 0);
            dataGridViewCellStyle2.SelectionBackColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.SelectionForeColor = System.Drawing.SystemColors.HighlightText;
            dataGridViewCellStyle2.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.nhanvienTable.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2;
            this.nhanvienTable.ColumnHeadersHeight = 55;
            this.nhanvienTable.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.DisableResizing;
            dataGridViewCellStyle3.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle3.BackColor = System.Drawing.Color.White;
            dataGridViewCellStyle3.Font = new System.Drawing.Font("Segoe UI Semibold", 9F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle3.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(71)))), ((int)(((byte)(69)))), ((int)(((byte)(94)))));
            dataGridViewCellStyle3.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(231)))), ((int)(((byte)(229)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle3.SelectionForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(71)))), ((int)(((byte)(69)))), ((int)(((byte)(94)))));
            dataGridViewCellStyle3.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.nhanvienTable.DefaultCellStyle = dataGridViewCellStyle3;
            this.nhanvienTable.EnableHeadersVisualStyles = false;
            this.nhanvienTable.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(231)))), ((int)(((byte)(229)))), ((int)(((byte)(255)))));
            this.nhanvienTable.Location = new System.Drawing.Point(42, 122);
            this.nhanvienTable.Name = "nhanvienTable";
            this.nhanvienTable.ReadOnly = true;
            this.nhanvienTable.RowHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.Single;
            dataGridViewCellStyle4.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleCenter;
            dataGridViewCellStyle4.BackColor = System.Drawing.SystemColors.Control;
            dataGridViewCellStyle4.Font = new System.Drawing.Font("Microsoft Sans Serif", 7.8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            dataGridViewCellStyle4.ForeColor = System.Drawing.SystemColors.WindowText;
            dataGridViewCellStyle4.Padding = new System.Windows.Forms.Padding(0, 0, 0, 10);
            dataGridViewCellStyle4.SelectionBackColor = System.Drawing.Color.White;
            dataGridViewCellStyle4.SelectionForeColor = System.Drawing.SystemColors.HighlightText;
            dataGridViewCellStyle4.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.nhanvienTable.RowHeadersDefaultCellStyle = dataGridViewCellStyle4;
            this.nhanvienTable.RowHeadersVisible = false;
            this.nhanvienTable.RowHeadersWidth = 51;
            this.nhanvienTable.RowHeadersWidthSizeMode = System.Windows.Forms.DataGridViewRowHeadersWidthSizeMode.DisableResizing;
            dataGridViewCellStyle5.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle5.Padding = new System.Windows.Forms.Padding(15, 0, 0, 5);
            dataGridViewCellStyle5.SelectionBackColor = System.Drawing.Color.AliceBlue;
            this.nhanvienTable.RowsDefaultCellStyle = dataGridViewCellStyle5;
            this.nhanvienTable.RowTemplate.Height = 55;
            this.nhanvienTable.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.nhanvienTable.Size = new System.Drawing.Size(1029, 470);
            this.nhanvienTable.TabIndex = 48;
            this.nhanvienTable.ThemeStyle.AlternatingRowsStyle.BackColor = System.Drawing.Color.White;
            this.nhanvienTable.ThemeStyle.AlternatingRowsStyle.Font = null;
            this.nhanvienTable.ThemeStyle.AlternatingRowsStyle.ForeColor = System.Drawing.Color.Empty;
            this.nhanvienTable.ThemeStyle.AlternatingRowsStyle.SelectionBackColor = System.Drawing.Color.Empty;
            this.nhanvienTable.ThemeStyle.AlternatingRowsStyle.SelectionForeColor = System.Drawing.Color.Empty;
            this.nhanvienTable.ThemeStyle.BackColor = System.Drawing.Color.White;
            this.nhanvienTable.ThemeStyle.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(231)))), ((int)(((byte)(229)))), ((int)(((byte)(255)))));
            this.nhanvienTable.ThemeStyle.HeaderStyle.BackColor = System.Drawing.Color.White;
            this.nhanvienTable.ThemeStyle.HeaderStyle.BorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            this.nhanvienTable.ThemeStyle.HeaderStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 10.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            this.nhanvienTable.ThemeStyle.HeaderStyle.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(33)))), ((int)(((byte)(35)))), ((int)(((byte)(74)))));
            this.nhanvienTable.ThemeStyle.HeaderStyle.HeaightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.DisableResizing;
            this.nhanvienTable.ThemeStyle.HeaderStyle.Height = 55;
            this.nhanvienTable.ThemeStyle.ReadOnly = true;
            this.nhanvienTable.ThemeStyle.RowsStyle.BackColor = System.Drawing.Color.White;
            this.nhanvienTable.ThemeStyle.RowsStyle.BorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.nhanvienTable.ThemeStyle.RowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9F, System.Drawing.FontStyle.Bold);
            this.nhanvienTable.ThemeStyle.RowsStyle.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(71)))), ((int)(((byte)(69)))), ((int)(((byte)(94)))));
            this.nhanvienTable.ThemeStyle.RowsStyle.Height = 55;
            this.nhanvienTable.ThemeStyle.RowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(231)))), ((int)(((byte)(229)))), ((int)(((byte)(255)))));
            this.nhanvienTable.ThemeStyle.RowsStyle.SelectionForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(71)))), ((int)(((byte)(69)))), ((int)(((byte)(94)))));
            // 
            // xuatNhanVien
            // 
            this.xuatNhanVien.AllowAnimations = true;
            this.xuatNhanVien.AllowMouseEffects = true;
            this.xuatNhanVien.AllowToggling = false;
            this.xuatNhanVien.AnimationSpeed = 200;
            this.xuatNhanVien.AutoGenerateColors = false;
            this.xuatNhanVien.AutoRoundBorders = false;
            this.xuatNhanVien.AutoSizeLeftIcon = true;
            this.xuatNhanVien.AutoSizeRightIcon = true;
            this.xuatNhanVien.BackColor = System.Drawing.Color.Transparent;
            this.xuatNhanVien.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(127)))), ((int)(((byte)(127)))), ((int)(((byte)(213)))));
            this.xuatNhanVien.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("xuatNhanVien.BackgroundImage")));
            this.xuatNhanVien.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.xuatNhanVien.ButtonText = "Xuất File";
            this.xuatNhanVien.ButtonTextMarginLeft = 0;
            this.xuatNhanVien.ColorContrastOnClick = 45;
            this.xuatNhanVien.ColorContrastOnHover = 45;
            this.xuatNhanVien.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.xuatNhanVien.CustomizableEdges = borderEdges2;
            this.xuatNhanVien.DialogResult = System.Windows.Forms.DialogResult.None;
            this.xuatNhanVien.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.xuatNhanVien.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.xuatNhanVien.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.xuatNhanVien.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.xuatNhanVien.Font = new System.Drawing.Font("Segoe UI Semibold", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            this.xuatNhanVien.ForeColor = System.Drawing.Color.White;
            this.xuatNhanVien.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.xuatNhanVien.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.xuatNhanVien.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.xuatNhanVien.IconMarginLeft = 11;
            this.xuatNhanVien.IconPadding = 10;
            this.xuatNhanVien.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.xuatNhanVien.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.xuatNhanVien.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.xuatNhanVien.IconSize = 25;
            this.xuatNhanVien.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(127)))), ((int)(((byte)(127)))), ((int)(((byte)(213)))));
            this.xuatNhanVien.IdleBorderRadius = 10;
            this.xuatNhanVien.IdleBorderThickness = 1;
            this.xuatNhanVien.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(127)))), ((int)(((byte)(127)))), ((int)(((byte)(213)))));
            this.xuatNhanVien.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("xuatNhanVien.IdleIconLeftImage")));
            this.xuatNhanVien.IdleIconRightImage = null;
            this.xuatNhanVien.IndicateFocus = false;
            this.xuatNhanVien.Location = new System.Drawing.Point(911, 36);
            this.xuatNhanVien.Name = "xuatNhanVien";
            this.xuatNhanVien.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.xuatNhanVien.OnDisabledState.BorderRadius = 10;
            this.xuatNhanVien.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.xuatNhanVien.OnDisabledState.BorderThickness = 1;
            this.xuatNhanVien.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.xuatNhanVien.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.xuatNhanVien.OnDisabledState.IconLeftImage = null;
            this.xuatNhanVien.OnDisabledState.IconRightImage = null;
            this.xuatNhanVien.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.xuatNhanVien.onHoverState.BorderRadius = 10;
            this.xuatNhanVien.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.xuatNhanVien.onHoverState.BorderThickness = 1;
            this.xuatNhanVien.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.xuatNhanVien.onHoverState.ForeColor = System.Drawing.Color.White;
            this.xuatNhanVien.onHoverState.IconLeftImage = null;
            this.xuatNhanVien.onHoverState.IconRightImage = null;
            this.xuatNhanVien.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(127)))), ((int)(((byte)(127)))), ((int)(((byte)(213)))));
            this.xuatNhanVien.OnIdleState.BorderRadius = 10;
            this.xuatNhanVien.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.xuatNhanVien.OnIdleState.BorderThickness = 1;
            this.xuatNhanVien.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(127)))), ((int)(((byte)(127)))), ((int)(((byte)(213)))));
            this.xuatNhanVien.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.xuatNhanVien.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("xuatNhanVien.OnIdleState.IconLeftImage")));
            this.xuatNhanVien.OnIdleState.IconRightImage = null;
            this.xuatNhanVien.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.xuatNhanVien.OnPressedState.BorderRadius = 10;
            this.xuatNhanVien.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.xuatNhanVien.OnPressedState.BorderThickness = 1;
            this.xuatNhanVien.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.xuatNhanVien.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.xuatNhanVien.OnPressedState.IconLeftImage = null;
            this.xuatNhanVien.OnPressedState.IconRightImage = null;
            this.xuatNhanVien.Size = new System.Drawing.Size(161, 40);
            this.xuatNhanVien.TabIndex = 43;
            this.xuatNhanVien.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.xuatNhanVien.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.xuatNhanVien.TextMarginLeft = 0;
            this.xuatNhanVien.TextPadding = new System.Windows.Forms.Padding(15, 0, 0, 0);
            this.xuatNhanVien.UseDefaultRadiusAndThickness = true;
            this.xuatNhanVien.Click += new System.EventHandler(this.xuatNhanVien_Click);
            // 
            // nhanvienPanelSub
            // 
            this.nhanvienPanelSub.AllowParentOverrides = false;
            this.nhanvienPanelSub.AutoEllipsis = false;
            this.nhanvienPanelSub.Cursor = System.Windows.Forms.Cursors.Default;
            this.nhanvienPanelSub.CursorType = System.Windows.Forms.Cursors.Default;
            this.nhanvienPanelSub.Font = new System.Drawing.Font("Segoe UI", 7F);
            this.nhanvienPanelSub.ForeColor = System.Drawing.SystemColors.ActiveBorder;
            this.nhanvienPanelSub.Location = new System.Drawing.Point(43, 60);
            this.nhanvienPanelSub.Name = "nhanvienPanelSub";
            this.nhanvienPanelSub.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.nhanvienPanelSub.Size = new System.Drawing.Size(128, 15);
            this.nhanvienPanelSub.TabIndex = 27;
            this.nhanvienPanelSub.Text = "Tìm thấy một số kết quả";
            this.nhanvienPanelSub.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.nhanvienPanelSub.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // nhanvienPanelTitle
            // 
            this.nhanvienPanelTitle.AllowParentOverrides = false;
            this.nhanvienPanelTitle.AutoEllipsis = false;
            this.nhanvienPanelTitle.Cursor = System.Windows.Forms.Cursors.Default;
            this.nhanvienPanelTitle.CursorType = System.Windows.Forms.Cursors.Default;
            this.nhanvienPanelTitle.Font = new System.Drawing.Font("Segoe UI Semibold", 13F, System.Drawing.FontStyle.Bold);
            this.nhanvienPanelTitle.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(79)))), ((int)(((byte)(79)))), ((int)(((byte)(79)))));
            this.nhanvienPanelTitle.Location = new System.Drawing.Point(43, 24);
            this.nhanvienPanelTitle.Name = "nhanvienPanelTitle";
            this.nhanvienPanelTitle.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.nhanvienPanelTitle.Size = new System.Drawing.Size(212, 30);
            this.nhanvienPanelTitle.TabIndex = 35;
            this.nhanvienPanelTitle.Text = "Thông Tin Nhân Viên";
            this.nhanvienPanelTitle.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.nhanvienPanelTitle.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // hanghoaLuuBtn
            // 
            this.hanghoaLuuBtn.AllowAnimations = true;
            this.hanghoaLuuBtn.AllowMouseEffects = true;
            this.hanghoaLuuBtn.AllowToggling = false;
            this.hanghoaLuuBtn.AnimationSpeed = 200;
            this.hanghoaLuuBtn.AutoGenerateColors = false;
            this.hanghoaLuuBtn.AutoRoundBorders = false;
            this.hanghoaLuuBtn.AutoSizeLeftIcon = true;
            this.hanghoaLuuBtn.AutoSizeRightIcon = true;
            this.hanghoaLuuBtn.BackColor = System.Drawing.Color.Transparent;
            this.hanghoaLuuBtn.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.hanghoaLuuBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("hanghoaLuuBtn.BackgroundImage")));
            this.hanghoaLuuBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.hanghoaLuuBtn.ButtonText = "Sửa";
            this.hanghoaLuuBtn.ButtonTextMarginLeft = 0;
            this.hanghoaLuuBtn.ColorContrastOnClick = 45;
            this.hanghoaLuuBtn.ColorContrastOnHover = 45;
            this.hanghoaLuuBtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.hanghoaLuuBtn.CustomizableEdges = borderEdges3;
            this.hanghoaLuuBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.hanghoaLuuBtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.hanghoaLuuBtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.hanghoaLuuBtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.hanghoaLuuBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.hanghoaLuuBtn.Font = new System.Drawing.Font("Segoe UI Semibold", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            this.hanghoaLuuBtn.ForeColor = System.Drawing.Color.White;
            this.hanghoaLuuBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.hanghoaLuuBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.hanghoaLuuBtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.hanghoaLuuBtn.IconMarginLeft = 11;
            this.hanghoaLuuBtn.IconPadding = 10;
            this.hanghoaLuuBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.hanghoaLuuBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.hanghoaLuuBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.hanghoaLuuBtn.IconSize = 25;
            this.hanghoaLuuBtn.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.hanghoaLuuBtn.IdleBorderRadius = 10;
            this.hanghoaLuuBtn.IdleBorderThickness = 1;
            this.hanghoaLuuBtn.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.hanghoaLuuBtn.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("hanghoaLuuBtn.IdleIconLeftImage")));
            this.hanghoaLuuBtn.IdleIconRightImage = null;
            this.hanghoaLuuBtn.IndicateFocus = false;
            this.hanghoaLuuBtn.Location = new System.Drawing.Point(798, 36);
            this.hanghoaLuuBtn.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.hanghoaLuuBtn.Name = "hanghoaLuuBtn";
            this.hanghoaLuuBtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.hanghoaLuuBtn.OnDisabledState.BorderRadius = 10;
            this.hanghoaLuuBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.hanghoaLuuBtn.OnDisabledState.BorderThickness = 1;
            this.hanghoaLuuBtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.hanghoaLuuBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.hanghoaLuuBtn.OnDisabledState.IconLeftImage = null;
            this.hanghoaLuuBtn.OnDisabledState.IconRightImage = null;
            this.hanghoaLuuBtn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.hanghoaLuuBtn.onHoverState.BorderRadius = 10;
            this.hanghoaLuuBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.hanghoaLuuBtn.onHoverState.BorderThickness = 1;
            this.hanghoaLuuBtn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.hanghoaLuuBtn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.hanghoaLuuBtn.onHoverState.IconLeftImage = null;
            this.hanghoaLuuBtn.onHoverState.IconRightImage = null;
            this.hanghoaLuuBtn.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.hanghoaLuuBtn.OnIdleState.BorderRadius = 10;
            this.hanghoaLuuBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.hanghoaLuuBtn.OnIdleState.BorderThickness = 1;
            this.hanghoaLuuBtn.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.hanghoaLuuBtn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.hanghoaLuuBtn.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("hanghoaLuuBtn.OnIdleState.IconLeftImage")));
            this.hanghoaLuuBtn.OnIdleState.IconRightImage = null;
            this.hanghoaLuuBtn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.hanghoaLuuBtn.OnPressedState.BorderRadius = 10;
            this.hanghoaLuuBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.hanghoaLuuBtn.OnPressedState.BorderThickness = 1;
            this.hanghoaLuuBtn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.hanghoaLuuBtn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.hanghoaLuuBtn.OnPressedState.IconLeftImage = null;
            this.hanghoaLuuBtn.OnPressedState.IconRightImage = null;
            this.hanghoaLuuBtn.Size = new System.Drawing.Size(96, 39);
            this.hanghoaLuuBtn.TabIndex = 8;
            this.hanghoaLuuBtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.hanghoaLuuBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.hanghoaLuuBtn.TextMarginLeft = 0;
            this.hanghoaLuuBtn.TextPadding = new System.Windows.Forms.Padding(15, 0, 0, 0);
            this.hanghoaLuuBtn.UseDefaultRadiusAndThickness = true;
            this.hanghoaLuuBtn.Click += new System.EventHandler(this.hanghoaLuuBtn_Click);
            // 
            // hanghoaXoaBtn
            // 
            this.hanghoaXoaBtn.AllowAnimations = true;
            this.hanghoaXoaBtn.AllowMouseEffects = true;
            this.hanghoaXoaBtn.AllowToggling = false;
            this.hanghoaXoaBtn.AnimationSpeed = 200;
            this.hanghoaXoaBtn.AutoGenerateColors = false;
            this.hanghoaXoaBtn.AutoRoundBorders = false;
            this.hanghoaXoaBtn.AutoSizeLeftIcon = true;
            this.hanghoaXoaBtn.AutoSizeRightIcon = true;
            this.hanghoaXoaBtn.BackColor = System.Drawing.Color.Transparent;
            this.hanghoaXoaBtn.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(246)))), ((int)(((byte)(78)))), ((int)(((byte)(96)))));
            this.hanghoaXoaBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("hanghoaXoaBtn.BackgroundImage")));
            this.hanghoaXoaBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.hanghoaXoaBtn.ButtonText = "Xóa";
            this.hanghoaXoaBtn.ButtonTextMarginLeft = 0;
            this.hanghoaXoaBtn.ColorContrastOnClick = 45;
            this.hanghoaXoaBtn.ColorContrastOnHover = 45;
            this.hanghoaXoaBtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.hanghoaXoaBtn.CustomizableEdges = borderEdges4;
            this.hanghoaXoaBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.hanghoaXoaBtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.hanghoaXoaBtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.hanghoaXoaBtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.hanghoaXoaBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.hanghoaXoaBtn.Font = new System.Drawing.Font("Segoe UI Semibold", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            this.hanghoaXoaBtn.ForeColor = System.Drawing.Color.White;
            this.hanghoaXoaBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.hanghoaXoaBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.hanghoaXoaBtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.hanghoaXoaBtn.IconMarginLeft = 11;
            this.hanghoaXoaBtn.IconPadding = 10;
            this.hanghoaXoaBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.hanghoaXoaBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.hanghoaXoaBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.hanghoaXoaBtn.IconSize = 25;
            this.hanghoaXoaBtn.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(246)))), ((int)(((byte)(78)))), ((int)(((byte)(96)))));
            this.hanghoaXoaBtn.IdleBorderRadius = 10;
            this.hanghoaXoaBtn.IdleBorderThickness = 1;
            this.hanghoaXoaBtn.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(246)))), ((int)(((byte)(78)))), ((int)(((byte)(96)))));
            this.hanghoaXoaBtn.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("hanghoaXoaBtn.IdleIconLeftImage")));
            this.hanghoaXoaBtn.IdleIconRightImage = null;
            this.hanghoaXoaBtn.IndicateFocus = false;
            this.hanghoaXoaBtn.Location = new System.Drawing.Point(682, 36);
            this.hanghoaXoaBtn.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.hanghoaXoaBtn.Name = "hanghoaXoaBtn";
            this.hanghoaXoaBtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.hanghoaXoaBtn.OnDisabledState.BorderRadius = 10;
            this.hanghoaXoaBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.hanghoaXoaBtn.OnDisabledState.BorderThickness = 1;
            this.hanghoaXoaBtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.hanghoaXoaBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.hanghoaXoaBtn.OnDisabledState.IconLeftImage = null;
            this.hanghoaXoaBtn.OnDisabledState.IconRightImage = null;
            this.hanghoaXoaBtn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.hanghoaXoaBtn.onHoverState.BorderRadius = 10;
            this.hanghoaXoaBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.hanghoaXoaBtn.onHoverState.BorderThickness = 1;
            this.hanghoaXoaBtn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.hanghoaXoaBtn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.hanghoaXoaBtn.onHoverState.IconLeftImage = null;
            this.hanghoaXoaBtn.onHoverState.IconRightImage = null;
            this.hanghoaXoaBtn.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(246)))), ((int)(((byte)(78)))), ((int)(((byte)(96)))));
            this.hanghoaXoaBtn.OnIdleState.BorderRadius = 10;
            this.hanghoaXoaBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.hanghoaXoaBtn.OnIdleState.BorderThickness = 1;
            this.hanghoaXoaBtn.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(246)))), ((int)(((byte)(78)))), ((int)(((byte)(96)))));
            this.hanghoaXoaBtn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.hanghoaXoaBtn.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("hanghoaXoaBtn.OnIdleState.IconLeftImage")));
            this.hanghoaXoaBtn.OnIdleState.IconRightImage = null;
            this.hanghoaXoaBtn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.hanghoaXoaBtn.OnPressedState.BorderRadius = 10;
            this.hanghoaXoaBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.hanghoaXoaBtn.OnPressedState.BorderThickness = 1;
            this.hanghoaXoaBtn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.hanghoaXoaBtn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.hanghoaXoaBtn.OnPressedState.IconLeftImage = null;
            this.hanghoaXoaBtn.OnPressedState.IconRightImage = null;
            this.hanghoaXoaBtn.Size = new System.Drawing.Size(96, 39);
            this.hanghoaXoaBtn.TabIndex = 6;
            this.hanghoaXoaBtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.hanghoaXoaBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.hanghoaXoaBtn.TextMarginLeft = 0;
            this.hanghoaXoaBtn.TextPadding = new System.Windows.Forms.Padding(15, 0, 0, 0);
            this.hanghoaXoaBtn.UseDefaultRadiusAndThickness = true;
            this.hanghoaXoaBtn.Click += new System.EventHandler(this.hanghoaXoaBtn_Click);
            // 
            // hanghoaThemBtn
            // 
            this.hanghoaThemBtn.AllowAnimations = true;
            this.hanghoaThemBtn.AllowMouseEffects = true;
            this.hanghoaThemBtn.AllowToggling = false;
            this.hanghoaThemBtn.AnimationSpeed = 200;
            this.hanghoaThemBtn.AutoGenerateColors = false;
            this.hanghoaThemBtn.AutoRoundBorders = false;
            this.hanghoaThemBtn.AutoSizeLeftIcon = true;
            this.hanghoaThemBtn.AutoSizeRightIcon = true;
            this.hanghoaThemBtn.BackColor = System.Drawing.Color.Transparent;
            this.hanghoaThemBtn.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(95)))), ((int)(((byte)(210)))), ((int)(((byte)(143)))));
            this.hanghoaThemBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("hanghoaThemBtn.BackgroundImage")));
            this.hanghoaThemBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.hanghoaThemBtn.ButtonText = "Thêm";
            this.hanghoaThemBtn.ButtonTextMarginLeft = 0;
            this.hanghoaThemBtn.ColorContrastOnClick = 45;
            this.hanghoaThemBtn.ColorContrastOnHover = 45;
            this.hanghoaThemBtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.hanghoaThemBtn.CustomizableEdges = borderEdges5;
            this.hanghoaThemBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.hanghoaThemBtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.hanghoaThemBtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.hanghoaThemBtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.hanghoaThemBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.hanghoaThemBtn.Font = new System.Drawing.Font("Segoe UI Semibold", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            this.hanghoaThemBtn.ForeColor = System.Drawing.Color.White;
            this.hanghoaThemBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.hanghoaThemBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.hanghoaThemBtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.hanghoaThemBtn.IconMarginLeft = 11;
            this.hanghoaThemBtn.IconPadding = 10;
            this.hanghoaThemBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.hanghoaThemBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.hanghoaThemBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.hanghoaThemBtn.IconSize = 25;
            this.hanghoaThemBtn.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(95)))), ((int)(((byte)(210)))), ((int)(((byte)(143)))));
            this.hanghoaThemBtn.IdleBorderRadius = 10;
            this.hanghoaThemBtn.IdleBorderThickness = 1;
            this.hanghoaThemBtn.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(95)))), ((int)(((byte)(210)))), ((int)(((byte)(143)))));
            this.hanghoaThemBtn.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("hanghoaThemBtn.IdleIconLeftImage")));
            this.hanghoaThemBtn.IdleIconRightImage = null;
            this.hanghoaThemBtn.IndicateFocus = false;
            this.hanghoaThemBtn.Location = new System.Drawing.Point(563, 36);
            this.hanghoaThemBtn.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.hanghoaThemBtn.Name = "hanghoaThemBtn";
            this.hanghoaThemBtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.hanghoaThemBtn.OnDisabledState.BorderRadius = 10;
            this.hanghoaThemBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.hanghoaThemBtn.OnDisabledState.BorderThickness = 1;
            this.hanghoaThemBtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.hanghoaThemBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.hanghoaThemBtn.OnDisabledState.IconLeftImage = null;
            this.hanghoaThemBtn.OnDisabledState.IconRightImage = null;
            this.hanghoaThemBtn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.hanghoaThemBtn.onHoverState.BorderRadius = 10;
            this.hanghoaThemBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.hanghoaThemBtn.onHoverState.BorderThickness = 1;
            this.hanghoaThemBtn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.hanghoaThemBtn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.hanghoaThemBtn.onHoverState.IconLeftImage = null;
            this.hanghoaThemBtn.onHoverState.IconRightImage = null;
            this.hanghoaThemBtn.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(95)))), ((int)(((byte)(210)))), ((int)(((byte)(143)))));
            this.hanghoaThemBtn.OnIdleState.BorderRadius = 10;
            this.hanghoaThemBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.hanghoaThemBtn.OnIdleState.BorderThickness = 1;
            this.hanghoaThemBtn.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(95)))), ((int)(((byte)(210)))), ((int)(((byte)(143)))));
            this.hanghoaThemBtn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.hanghoaThemBtn.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("hanghoaThemBtn.OnIdleState.IconLeftImage")));
            this.hanghoaThemBtn.OnIdleState.IconRightImage = null;
            this.hanghoaThemBtn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.hanghoaThemBtn.OnPressedState.BorderRadius = 10;
            this.hanghoaThemBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.hanghoaThemBtn.OnPressedState.BorderThickness = 1;
            this.hanghoaThemBtn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.hanghoaThemBtn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.hanghoaThemBtn.OnPressedState.IconLeftImage = null;
            this.hanghoaThemBtn.OnPressedState.IconRightImage = null;
            this.hanghoaThemBtn.Size = new System.Drawing.Size(96, 39);
            this.hanghoaThemBtn.TabIndex = 7;
            this.hanghoaThemBtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.hanghoaThemBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.hanghoaThemBtn.TextMarginLeft = 0;
            this.hanghoaThemBtn.TextPadding = new System.Windows.Forms.Padding(15, 0, 0, 0);
            this.hanghoaThemBtn.UseDefaultRadiusAndThickness = true;
            this.hanghoaThemBtn.Click += new System.EventHandler(this.hanghoaThemBtn_Click);
            // 
            // bunifuPanel2
            // 
            this.bunifuPanel2.BackgroundColor = System.Drawing.Color.White;
            this.bunifuPanel2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel2.BackgroundImage")));
            this.bunifuPanel2.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel2.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuPanel2.BorderRadius = 20;
            this.bunifuPanel2.BorderThickness = 1;
            this.bunifuPanel2.Location = new System.Drawing.Point(1032, 12);
            this.bunifuPanel2.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.bunifuPanel2.Name = "bunifuPanel2";
            this.bunifuPanel2.ShowBorders = true;
            this.bunifuPanel2.Size = new System.Drawing.Size(209, 65);
            this.bunifuPanel2.TabIndex = 26;
            // 
            // nhanvienPanel
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(239)))), ((int)(((byte)(243)))), ((int)(((byte)(249)))));
            this.ClientSize = new System.Drawing.Size(1271, 785);
            this.Controls.Add(this.bunifuPanel2);
            this.Controls.Add(this.bunifuPanel1);
            this.Controls.Add(this.nhanvienSearchBtn);
            this.Controls.Add(this.nhanvienSearch);
            this.Controls.Add(this.nhanvienTitle);
            this.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.Name = "nhanvienPanel";
            this.Text = "formNhanVien";
            this.bunifuPanel1.ResumeLayout(false);
            this.bunifuPanel1.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.nhanvienTable)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 nhanvienSearchBtn;
        private Bunifu.UI.WinForms.BunifuTextBox nhanvienSearch;
        private Bunifu.UI.WinForms.BunifuLabel nhanvienTitle;
        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel1;
        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel2;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 hanghoaLuuBtn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 hanghoaXoaBtn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 hanghoaThemBtn;
        private Bunifu.UI.WinForms.BunifuLabel nhanvienPanelSub;
        private Bunifu.UI.WinForms.BunifuLabel nhanvienPanelTitle;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 xuatNhanVien;
        private Guna.UI2.WinForms.Guna2DataGridView nhanvienTable;
    }
}