namespace BTL.GUI
{
    partial class formDoanhThu
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(formDoanhThu));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            this.bunifuShadowPanel1 = new Bunifu.UI.WinForms.BunifuShadowPanel();
            this.indicatorLine = new System.Windows.Forms.PictureBox();
            this.lienheBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.trangchuBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.hanghoaBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.hoadonBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.nhanhvienBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.khachhangBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.bunifuPanel2 = new Bunifu.UI.WinForms.BunifuPanel();
            this.bunifuShadowPanel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.indicatorLine)).BeginInit();
            this.SuspendLayout();
            // 
            // bunifuShadowPanel1
            // 
            this.bunifuShadowPanel1.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left)));
            this.bunifuShadowPanel1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuShadowPanel1.BorderColor = System.Drawing.Color.WhiteSmoke;
            this.bunifuShadowPanel1.BorderRadius = 1;
            this.bunifuShadowPanel1.BorderThickness = 1;
            this.bunifuShadowPanel1.Controls.Add(this.indicatorLine);
            this.bunifuShadowPanel1.Controls.Add(this.lienheBtn);
            this.bunifuShadowPanel1.Controls.Add(this.trangchuBtn);
            this.bunifuShadowPanel1.Controls.Add(this.hanghoaBtn);
            this.bunifuShadowPanel1.Controls.Add(this.hoadonBtn);
            this.bunifuShadowPanel1.Controls.Add(this.nhanhvienBtn);
            this.bunifuShadowPanel1.Controls.Add(this.khachhangBtn);
            this.bunifuShadowPanel1.FillStyle = Bunifu.UI.WinForms.BunifuShadowPanel.FillStyles.Solid;
            this.bunifuShadowPanel1.GradientMode = Bunifu.UI.WinForms.BunifuShadowPanel.GradientModes.Vertical;
            this.bunifuShadowPanel1.Location = new System.Drawing.Point(-7, -40);
            this.bunifuShadowPanel1.Name = "bunifuShadowPanel1";
            this.bunifuShadowPanel1.PanelColor = System.Drawing.Color.White;
            this.bunifuShadowPanel1.PanelColor2 = System.Drawing.Color.White;
            this.bunifuShadowPanel1.ShadowColor = System.Drawing.Color.WhiteSmoke;
            this.bunifuShadowPanel1.ShadowDept = 2;
            this.bunifuShadowPanel1.ShadowDepth = 2;
            this.bunifuShadowPanel1.ShadowStyle = Bunifu.UI.WinForms.BunifuShadowPanel.ShadowStyles.Dropped;
            this.bunifuShadowPanel1.ShadowTopLeftVisible = false;
            this.bunifuShadowPanel1.Size = new System.Drawing.Size(116, 881);
            this.bunifuShadowPanel1.Style = Bunifu.UI.WinForms.BunifuShadowPanel.BevelStyles.Flat;
            this.bunifuShadowPanel1.TabIndex = 11;
            // 
            // indicatorLine
            // 
            this.indicatorLine.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(125)))), ((int)(((byte)(250)))));
            this.indicatorLine.Location = new System.Drawing.Point(-36, 228);
            this.indicatorLine.Name = "indicatorLine";
            this.indicatorLine.Size = new System.Drawing.Size(48, 48);
            this.indicatorLine.TabIndex = 14;
            this.indicatorLine.TabStop = false;
            // 
            // lienheBtn
            // 
            this.lienheBtn.AllowAnimations = true;
            this.lienheBtn.AllowMouseEffects = true;
            this.lienheBtn.AllowToggling = false;
            this.lienheBtn.AnimationSpeed = 300;
            this.lienheBtn.AutoGenerateColors = false;
            this.lienheBtn.AutoRoundBorders = false;
            this.lienheBtn.AutoSizeLeftIcon = true;
            this.lienheBtn.AutoSizeRightIcon = true;
            this.lienheBtn.BackColor = System.Drawing.Color.Transparent;
            this.lienheBtn.BackColor1 = System.Drawing.Color.White;
            this.lienheBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("lienheBtn.BackgroundImage")));
            this.lienheBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.lienheBtn.ButtonText = "";
            this.lienheBtn.ButtonTextMarginLeft = 0;
            this.lienheBtn.ColorContrastOnClick = 45;
            this.lienheBtn.ColorContrastOnHover = 45;
            this.lienheBtn.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.lienheBtn.CustomizableEdges = borderEdges1;
            this.lienheBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.lienheBtn.DisabledBorderColor = System.Drawing.Color.Empty;
            this.lienheBtn.DisabledFillColor = System.Drawing.Color.White;
            this.lienheBtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.lienheBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.lienheBtn.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.lienheBtn.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(223)))), ((int)(((byte)(230)))), ((int)(((byte)(241)))));
            this.lienheBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.lienheBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.lienheBtn.IconLeftPadding = new System.Windows.Forms.Padding(3);
            this.lienheBtn.IconMarginLeft = 11;
            this.lienheBtn.IconPadding = 10;
            this.lienheBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.lienheBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.lienheBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.lienheBtn.IconSize = 25;
            this.lienheBtn.IdleBorderColor = System.Drawing.Color.White;
            this.lienheBtn.IdleBorderRadius = 1;
            this.lienheBtn.IdleBorderThickness = 1;
            this.lienheBtn.IdleFillColor = System.Drawing.Color.White;
            this.lienheBtn.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("lienheBtn.IdleIconLeftImage")));
            this.lienheBtn.IdleIconRightImage = null;
            this.lienheBtn.ImeMode = System.Windows.Forms.ImeMode.NoControl;
            this.lienheBtn.IndicateFocus = false;
            this.lienheBtn.Location = new System.Drawing.Point(0, 607);
            this.lienheBtn.Name = "lienheBtn";
            this.lienheBtn.OnDisabledState.BorderColor = System.Drawing.Color.Empty;
            this.lienheBtn.OnDisabledState.BorderRadius = 1;
            this.lienheBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.lienheBtn.OnDisabledState.BorderThickness = 1;
            this.lienheBtn.OnDisabledState.FillColor = System.Drawing.Color.White;
            this.lienheBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.lienheBtn.OnDisabledState.IconLeftImage = null;
            this.lienheBtn.OnDisabledState.IconRightImage = null;
            this.lienheBtn.onHoverState.BorderColor = System.Drawing.Color.White;
            this.lienheBtn.onHoverState.BorderRadius = 1;
            this.lienheBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.lienheBtn.onHoverState.BorderThickness = 1;
            this.lienheBtn.onHoverState.FillColor = System.Drawing.Color.White;
            this.lienheBtn.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(125)))), ((int)(((byte)(250)))));
            this.lienheBtn.onHoverState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("resource.IconLeftImage")));
            this.lienheBtn.onHoverState.IconRightImage = null;
            this.lienheBtn.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.lienheBtn.OnIdleState.BorderRadius = 1;
            this.lienheBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.lienheBtn.OnIdleState.BorderThickness = 1;
            this.lienheBtn.OnIdleState.FillColor = System.Drawing.Color.White;
            this.lienheBtn.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(223)))), ((int)(((byte)(230)))), ((int)(((byte)(241)))));
            this.lienheBtn.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("lienheBtn.OnIdleState.IconLeftImage")));
            this.lienheBtn.OnIdleState.IconRightImage = null;
            this.lienheBtn.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.lienheBtn.OnPressedState.BorderRadius = 1;
            this.lienheBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.lienheBtn.OnPressedState.BorderThickness = 1;
            this.lienheBtn.OnPressedState.FillColor = System.Drawing.Color.White;
            this.lienheBtn.OnPressedState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(125)))), ((int)(((byte)(250)))));
            this.lienheBtn.OnPressedState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("resource.IconLeftImage1")));
            this.lienheBtn.OnPressedState.IconRightImage = null;
            this.lienheBtn.Size = new System.Drawing.Size(112, 43);
            this.lienheBtn.TabIndex = 24;
            this.lienheBtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.lienheBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.lienheBtn.TextMarginLeft = 0;
            this.lienheBtn.TextPadding = new System.Windows.Forms.Padding(0);
            this.lienheBtn.UseDefaultRadiusAndThickness = true;
            // 
            // trangchuBtn
            // 
            this.trangchuBtn.AllowAnimations = true;
            this.trangchuBtn.AllowMouseEffects = true;
            this.trangchuBtn.AllowToggling = false;
            this.trangchuBtn.AnimationSpeed = 300;
            this.trangchuBtn.AutoGenerateColors = false;
            this.trangchuBtn.AutoRoundBorders = false;
            this.trangchuBtn.AutoSizeLeftIcon = true;
            this.trangchuBtn.AutoSizeRightIcon = true;
            this.trangchuBtn.BackColor = System.Drawing.Color.Transparent;
            this.trangchuBtn.BackColor1 = System.Drawing.Color.White;
            this.trangchuBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("trangchuBtn.BackgroundImage")));
            this.trangchuBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.trangchuBtn.ButtonText = "";
            this.trangchuBtn.ButtonTextMarginLeft = 0;
            this.trangchuBtn.ColorContrastOnClick = 45;
            this.trangchuBtn.ColorContrastOnHover = 45;
            this.trangchuBtn.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.trangchuBtn.CustomizableEdges = borderEdges2;
            this.trangchuBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.trangchuBtn.DisabledBorderColor = System.Drawing.Color.Empty;
            this.trangchuBtn.DisabledFillColor = System.Drawing.Color.White;
            this.trangchuBtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.trangchuBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.trangchuBtn.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.trangchuBtn.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(223)))), ((int)(((byte)(230)))), ((int)(((byte)(241)))));
            this.trangchuBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.trangchuBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.trangchuBtn.IconLeftPadding = new System.Windows.Forms.Padding(3);
            this.trangchuBtn.IconMarginLeft = 11;
            this.trangchuBtn.IconPadding = 10;
            this.trangchuBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.trangchuBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.trangchuBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.trangchuBtn.IconSize = 25;
            this.trangchuBtn.IdleBorderColor = System.Drawing.Color.White;
            this.trangchuBtn.IdleBorderRadius = 1;
            this.trangchuBtn.IdleBorderThickness = 1;
            this.trangchuBtn.IdleFillColor = System.Drawing.Color.White;
            this.trangchuBtn.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("trangchuBtn.IdleIconLeftImage")));
            this.trangchuBtn.IdleIconRightImage = null;
            this.trangchuBtn.ImeMode = System.Windows.Forms.ImeMode.NoControl;
            this.trangchuBtn.IndicateFocus = false;
            this.trangchuBtn.Location = new System.Drawing.Point(0, 233);
            this.trangchuBtn.Name = "trangchuBtn";
            this.trangchuBtn.OnDisabledState.BorderColor = System.Drawing.Color.Empty;
            this.trangchuBtn.OnDisabledState.BorderRadius = 1;
            this.trangchuBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.trangchuBtn.OnDisabledState.BorderThickness = 1;
            this.trangchuBtn.OnDisabledState.FillColor = System.Drawing.Color.White;
            this.trangchuBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.trangchuBtn.OnDisabledState.IconLeftImage = null;
            this.trangchuBtn.OnDisabledState.IconRightImage = null;
            this.trangchuBtn.onHoverState.BorderColor = System.Drawing.Color.White;
            this.trangchuBtn.onHoverState.BorderRadius = 1;
            this.trangchuBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.trangchuBtn.onHoverState.BorderThickness = 1;
            this.trangchuBtn.onHoverState.FillColor = System.Drawing.Color.White;
            this.trangchuBtn.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(125)))), ((int)(((byte)(250)))));
            this.trangchuBtn.onHoverState.IconLeftImage = global::BTL.Properties.Resources.home_color;
            this.trangchuBtn.onHoverState.IconRightImage = null;
            this.trangchuBtn.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.trangchuBtn.OnIdleState.BorderRadius = 1;
            this.trangchuBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.trangchuBtn.OnIdleState.BorderThickness = 1;
            this.trangchuBtn.OnIdleState.FillColor = System.Drawing.Color.White;
            this.trangchuBtn.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(223)))), ((int)(((byte)(230)))), ((int)(((byte)(241)))));
            this.trangchuBtn.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("trangchuBtn.OnIdleState.IconLeftImage")));
            this.trangchuBtn.OnIdleState.IconRightImage = null;
            this.trangchuBtn.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.trangchuBtn.OnPressedState.BorderRadius = 1;
            this.trangchuBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.trangchuBtn.OnPressedState.BorderThickness = 1;
            this.trangchuBtn.OnPressedState.FillColor = System.Drawing.Color.White;
            this.trangchuBtn.OnPressedState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(125)))), ((int)(((byte)(250)))));
            this.trangchuBtn.OnPressedState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("resource.IconLeftImage2")));
            this.trangchuBtn.OnPressedState.IconRightImage = null;
            this.trangchuBtn.Size = new System.Drawing.Size(112, 43);
            this.trangchuBtn.TabIndex = 19;
            this.trangchuBtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.trangchuBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.trangchuBtn.TextMarginLeft = 0;
            this.trangchuBtn.TextPadding = new System.Windows.Forms.Padding(0);
            this.trangchuBtn.UseDefaultRadiusAndThickness = true;
            // 
            // hanghoaBtn
            // 
            this.hanghoaBtn.AllowAnimations = true;
            this.hanghoaBtn.AllowMouseEffects = true;
            this.hanghoaBtn.AllowToggling = false;
            this.hanghoaBtn.AnimationSpeed = 300;
            this.hanghoaBtn.AutoGenerateColors = false;
            this.hanghoaBtn.AutoRoundBorders = false;
            this.hanghoaBtn.AutoSizeLeftIcon = true;
            this.hanghoaBtn.AutoSizeRightIcon = true;
            this.hanghoaBtn.BackColor = System.Drawing.Color.Transparent;
            this.hanghoaBtn.BackColor1 = System.Drawing.Color.White;
            this.hanghoaBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("hanghoaBtn.BackgroundImage")));
            this.hanghoaBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.hanghoaBtn.ButtonText = "";
            this.hanghoaBtn.ButtonTextMarginLeft = 0;
            this.hanghoaBtn.ColorContrastOnClick = 45;
            this.hanghoaBtn.ColorContrastOnHover = 45;
            this.hanghoaBtn.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.hanghoaBtn.CustomizableEdges = borderEdges3;
            this.hanghoaBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.hanghoaBtn.DisabledBorderColor = System.Drawing.Color.Empty;
            this.hanghoaBtn.DisabledFillColor = System.Drawing.Color.White;
            this.hanghoaBtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.hanghoaBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.hanghoaBtn.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.hanghoaBtn.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(223)))), ((int)(((byte)(230)))), ((int)(((byte)(241)))));
            this.hanghoaBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.hanghoaBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.hanghoaBtn.IconLeftPadding = new System.Windows.Forms.Padding(3);
            this.hanghoaBtn.IconMarginLeft = 11;
            this.hanghoaBtn.IconPadding = 10;
            this.hanghoaBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.hanghoaBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.hanghoaBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.hanghoaBtn.IconSize = 25;
            this.hanghoaBtn.IdleBorderColor = System.Drawing.Color.White;
            this.hanghoaBtn.IdleBorderRadius = 1;
            this.hanghoaBtn.IdleBorderThickness = 1;
            this.hanghoaBtn.IdleFillColor = System.Drawing.Color.White;
            this.hanghoaBtn.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("hanghoaBtn.IdleIconLeftImage")));
            this.hanghoaBtn.IdleIconRightImage = null;
            this.hanghoaBtn.ImeMode = System.Windows.Forms.ImeMode.NoControl;
            this.hanghoaBtn.IndicateFocus = false;
            this.hanghoaBtn.Location = new System.Drawing.Point(0, 300);
            this.hanghoaBtn.Name = "hanghoaBtn";
            this.hanghoaBtn.OnDisabledState.BorderColor = System.Drawing.Color.Empty;
            this.hanghoaBtn.OnDisabledState.BorderRadius = 1;
            this.hanghoaBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.hanghoaBtn.OnDisabledState.BorderThickness = 1;
            this.hanghoaBtn.OnDisabledState.FillColor = System.Drawing.Color.White;
            this.hanghoaBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.hanghoaBtn.OnDisabledState.IconLeftImage = null;
            this.hanghoaBtn.OnDisabledState.IconRightImage = null;
            this.hanghoaBtn.onHoverState.BorderColor = System.Drawing.Color.White;
            this.hanghoaBtn.onHoverState.BorderRadius = 1;
            this.hanghoaBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.hanghoaBtn.onHoverState.BorderThickness = 1;
            this.hanghoaBtn.onHoverState.FillColor = System.Drawing.Color.White;
            this.hanghoaBtn.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(125)))), ((int)(((byte)(250)))));
            this.hanghoaBtn.onHoverState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("resource.IconLeftImage3")));
            this.hanghoaBtn.onHoverState.IconRightImage = null;
            this.hanghoaBtn.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.hanghoaBtn.OnIdleState.BorderRadius = 1;
            this.hanghoaBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.hanghoaBtn.OnIdleState.BorderThickness = 1;
            this.hanghoaBtn.OnIdleState.FillColor = System.Drawing.Color.White;
            this.hanghoaBtn.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(223)))), ((int)(((byte)(230)))), ((int)(((byte)(241)))));
            this.hanghoaBtn.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("hanghoaBtn.OnIdleState.IconLeftImage")));
            this.hanghoaBtn.OnIdleState.IconRightImage = null;
            this.hanghoaBtn.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.hanghoaBtn.OnPressedState.BorderRadius = 1;
            this.hanghoaBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.hanghoaBtn.OnPressedState.BorderThickness = 1;
            this.hanghoaBtn.OnPressedState.FillColor = System.Drawing.Color.White;
            this.hanghoaBtn.OnPressedState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(125)))), ((int)(((byte)(250)))));
            this.hanghoaBtn.OnPressedState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("resource.IconLeftImage4")));
            this.hanghoaBtn.OnPressedState.IconRightImage = null;
            this.hanghoaBtn.Size = new System.Drawing.Size(112, 43);
            this.hanghoaBtn.TabIndex = 20;
            this.hanghoaBtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.hanghoaBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.hanghoaBtn.TextMarginLeft = 0;
            this.hanghoaBtn.TextPadding = new System.Windows.Forms.Padding(0);
            this.hanghoaBtn.UseDefaultRadiusAndThickness = true;
            // 
            // hoadonBtn
            // 
            this.hoadonBtn.AllowAnimations = true;
            this.hoadonBtn.AllowMouseEffects = true;
            this.hoadonBtn.AllowToggling = false;
            this.hoadonBtn.AnimationSpeed = 300;
            this.hoadonBtn.AutoGenerateColors = false;
            this.hoadonBtn.AutoRoundBorders = false;
            this.hoadonBtn.AutoSizeLeftIcon = true;
            this.hoadonBtn.AutoSizeRightIcon = true;
            this.hoadonBtn.BackColor = System.Drawing.Color.Transparent;
            this.hoadonBtn.BackColor1 = System.Drawing.Color.White;
            this.hoadonBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("hoadonBtn.BackgroundImage")));
            this.hoadonBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.hoadonBtn.ButtonText = "";
            this.hoadonBtn.ButtonTextMarginLeft = 0;
            this.hoadonBtn.ColorContrastOnClick = 45;
            this.hoadonBtn.ColorContrastOnHover = 45;
            this.hoadonBtn.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.hoadonBtn.CustomizableEdges = borderEdges4;
            this.hoadonBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.hoadonBtn.DisabledBorderColor = System.Drawing.Color.Empty;
            this.hoadonBtn.DisabledFillColor = System.Drawing.Color.White;
            this.hoadonBtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.hoadonBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.hoadonBtn.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.hoadonBtn.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(223)))), ((int)(((byte)(230)))), ((int)(((byte)(241)))));
            this.hoadonBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.hoadonBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.hoadonBtn.IconLeftPadding = new System.Windows.Forms.Padding(3);
            this.hoadonBtn.IconMarginLeft = 11;
            this.hoadonBtn.IconPadding = 10;
            this.hoadonBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.hoadonBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.hoadonBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.hoadonBtn.IconSize = 25;
            this.hoadonBtn.IdleBorderColor = System.Drawing.Color.White;
            this.hoadonBtn.IdleBorderRadius = 1;
            this.hoadonBtn.IdleBorderThickness = 1;
            this.hoadonBtn.IdleFillColor = System.Drawing.Color.White;
            this.hoadonBtn.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("hoadonBtn.IdleIconLeftImage")));
            this.hoadonBtn.IdleIconRightImage = null;
            this.hoadonBtn.ImeMode = System.Windows.Forms.ImeMode.NoControl;
            this.hoadonBtn.IndicateFocus = false;
            this.hoadonBtn.Location = new System.Drawing.Point(0, 532);
            this.hoadonBtn.Name = "hoadonBtn";
            this.hoadonBtn.OnDisabledState.BorderColor = System.Drawing.Color.Empty;
            this.hoadonBtn.OnDisabledState.BorderRadius = 1;
            this.hoadonBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.hoadonBtn.OnDisabledState.BorderThickness = 1;
            this.hoadonBtn.OnDisabledState.FillColor = System.Drawing.Color.White;
            this.hoadonBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.hoadonBtn.OnDisabledState.IconLeftImage = null;
            this.hoadonBtn.OnDisabledState.IconRightImage = null;
            this.hoadonBtn.onHoverState.BorderColor = System.Drawing.Color.White;
            this.hoadonBtn.onHoverState.BorderRadius = 1;
            this.hoadonBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.hoadonBtn.onHoverState.BorderThickness = 1;
            this.hoadonBtn.onHoverState.FillColor = System.Drawing.Color.White;
            this.hoadonBtn.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(125)))), ((int)(((byte)(250)))));
            this.hoadonBtn.onHoverState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("resource.IconLeftImage5")));
            this.hoadonBtn.onHoverState.IconRightImage = null;
            this.hoadonBtn.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.hoadonBtn.OnIdleState.BorderRadius = 1;
            this.hoadonBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.hoadonBtn.OnIdleState.BorderThickness = 1;
            this.hoadonBtn.OnIdleState.FillColor = System.Drawing.Color.White;
            this.hoadonBtn.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(223)))), ((int)(((byte)(230)))), ((int)(((byte)(241)))));
            this.hoadonBtn.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("hoadonBtn.OnIdleState.IconLeftImage")));
            this.hoadonBtn.OnIdleState.IconRightImage = null;
            this.hoadonBtn.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.hoadonBtn.OnPressedState.BorderRadius = 1;
            this.hoadonBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.hoadonBtn.OnPressedState.BorderThickness = 1;
            this.hoadonBtn.OnPressedState.FillColor = System.Drawing.Color.White;
            this.hoadonBtn.OnPressedState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(125)))), ((int)(((byte)(250)))));
            this.hoadonBtn.OnPressedState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("resource.IconLeftImage6")));
            this.hoadonBtn.OnPressedState.IconRightImage = null;
            this.hoadonBtn.Size = new System.Drawing.Size(112, 43);
            this.hoadonBtn.TabIndex = 23;
            this.hoadonBtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.hoadonBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.hoadonBtn.TextMarginLeft = 0;
            this.hoadonBtn.TextPadding = new System.Windows.Forms.Padding(0);
            this.hoadonBtn.UseDefaultRadiusAndThickness = true;
            // 
            // nhanhvienBtn
            // 
            this.nhanhvienBtn.AllowAnimations = true;
            this.nhanhvienBtn.AllowMouseEffects = true;
            this.nhanhvienBtn.AllowToggling = false;
            this.nhanhvienBtn.AnimationSpeed = 300;
            this.nhanhvienBtn.AutoGenerateColors = false;
            this.nhanhvienBtn.AutoRoundBorders = false;
            this.nhanhvienBtn.AutoSizeLeftIcon = true;
            this.nhanhvienBtn.AutoSizeRightIcon = true;
            this.nhanhvienBtn.BackColor = System.Drawing.Color.Transparent;
            this.nhanhvienBtn.BackColor1 = System.Drawing.Color.White;
            this.nhanhvienBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("nhanhvienBtn.BackgroundImage")));
            this.nhanhvienBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.nhanhvienBtn.ButtonText = "";
            this.nhanhvienBtn.ButtonTextMarginLeft = 0;
            this.nhanhvienBtn.ColorContrastOnClick = 45;
            this.nhanhvienBtn.ColorContrastOnHover = 45;
            this.nhanhvienBtn.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.nhanhvienBtn.CustomizableEdges = borderEdges5;
            this.nhanhvienBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.nhanhvienBtn.DisabledBorderColor = System.Drawing.Color.Empty;
            this.nhanhvienBtn.DisabledFillColor = System.Drawing.Color.White;
            this.nhanhvienBtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.nhanhvienBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.nhanhvienBtn.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.nhanhvienBtn.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(223)))), ((int)(((byte)(230)))), ((int)(((byte)(241)))));
            this.nhanhvienBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.nhanhvienBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.nhanhvienBtn.IconLeftPadding = new System.Windows.Forms.Padding(3);
            this.nhanhvienBtn.IconMarginLeft = 11;
            this.nhanhvienBtn.IconPadding = 10;
            this.nhanhvienBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.nhanhvienBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.nhanhvienBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.nhanhvienBtn.IconSize = 25;
            this.nhanhvienBtn.IdleBorderColor = System.Drawing.Color.White;
            this.nhanhvienBtn.IdleBorderRadius = 1;
            this.nhanhvienBtn.IdleBorderThickness = 1;
            this.nhanhvienBtn.IdleFillColor = System.Drawing.Color.White;
            this.nhanhvienBtn.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("nhanhvienBtn.IdleIconLeftImage")));
            this.nhanhvienBtn.IdleIconRightImage = null;
            this.nhanhvienBtn.ImeMode = System.Windows.Forms.ImeMode.NoControl;
            this.nhanhvienBtn.IndicateFocus = false;
            this.nhanhvienBtn.Location = new System.Drawing.Point(-3, 376);
            this.nhanhvienBtn.Name = "nhanhvienBtn";
            this.nhanhvienBtn.OnDisabledState.BorderColor = System.Drawing.Color.Empty;
            this.nhanhvienBtn.OnDisabledState.BorderRadius = 1;
            this.nhanhvienBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.nhanhvienBtn.OnDisabledState.BorderThickness = 1;
            this.nhanhvienBtn.OnDisabledState.FillColor = System.Drawing.Color.White;
            this.nhanhvienBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.nhanhvienBtn.OnDisabledState.IconLeftImage = null;
            this.nhanhvienBtn.OnDisabledState.IconRightImage = null;
            this.nhanhvienBtn.onHoverState.BorderColor = System.Drawing.Color.White;
            this.nhanhvienBtn.onHoverState.BorderRadius = 1;
            this.nhanhvienBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.nhanhvienBtn.onHoverState.BorderThickness = 1;
            this.nhanhvienBtn.onHoverState.FillColor = System.Drawing.Color.White;
            this.nhanhvienBtn.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(125)))), ((int)(((byte)(250)))));
            this.nhanhvienBtn.onHoverState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("resource.IconLeftImage7")));
            this.nhanhvienBtn.onHoverState.IconRightImage = null;
            this.nhanhvienBtn.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.nhanhvienBtn.OnIdleState.BorderRadius = 1;
            this.nhanhvienBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.nhanhvienBtn.OnIdleState.BorderThickness = 1;
            this.nhanhvienBtn.OnIdleState.FillColor = System.Drawing.Color.White;
            this.nhanhvienBtn.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(223)))), ((int)(((byte)(230)))), ((int)(((byte)(241)))));
            this.nhanhvienBtn.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("nhanhvienBtn.OnIdleState.IconLeftImage")));
            this.nhanhvienBtn.OnIdleState.IconRightImage = null;
            this.nhanhvienBtn.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.nhanhvienBtn.OnPressedState.BorderRadius = 1;
            this.nhanhvienBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.nhanhvienBtn.OnPressedState.BorderThickness = 1;
            this.nhanhvienBtn.OnPressedState.FillColor = System.Drawing.Color.White;
            this.nhanhvienBtn.OnPressedState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(125)))), ((int)(((byte)(250)))));
            this.nhanhvienBtn.OnPressedState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("resource.IconLeftImage8")));
            this.nhanhvienBtn.OnPressedState.IconRightImage = null;
            this.nhanhvienBtn.Size = new System.Drawing.Size(115, 43);
            this.nhanhvienBtn.TabIndex = 21;
            this.nhanhvienBtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.nhanhvienBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.nhanhvienBtn.TextMarginLeft = 0;
            this.nhanhvienBtn.TextPadding = new System.Windows.Forms.Padding(0);
            this.nhanhvienBtn.UseDefaultRadiusAndThickness = true;
            // 
            // khachhangBtn
            // 
            this.khachhangBtn.AllowAnimations = true;
            this.khachhangBtn.AllowMouseEffects = true;
            this.khachhangBtn.AllowToggling = false;
            this.khachhangBtn.AnimationSpeed = 300;
            this.khachhangBtn.AutoGenerateColors = false;
            this.khachhangBtn.AutoRoundBorders = false;
            this.khachhangBtn.AutoSizeLeftIcon = true;
            this.khachhangBtn.AutoSizeRightIcon = true;
            this.khachhangBtn.BackColor = System.Drawing.Color.Transparent;
            this.khachhangBtn.BackColor1 = System.Drawing.Color.White;
            this.khachhangBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("khachhangBtn.BackgroundImage")));
            this.khachhangBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.khachhangBtn.ButtonText = "";
            this.khachhangBtn.ButtonTextMarginLeft = 0;
            this.khachhangBtn.ColorContrastOnClick = 45;
            this.khachhangBtn.ColorContrastOnHover = 45;
            this.khachhangBtn.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.khachhangBtn.CustomizableEdges = borderEdges6;
            this.khachhangBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.khachhangBtn.DisabledBorderColor = System.Drawing.Color.Empty;
            this.khachhangBtn.DisabledFillColor = System.Drawing.Color.White;
            this.khachhangBtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.khachhangBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.khachhangBtn.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.khachhangBtn.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(223)))), ((int)(((byte)(230)))), ((int)(((byte)(241)))));
            this.khachhangBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.khachhangBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.khachhangBtn.IconLeftPadding = new System.Windows.Forms.Padding(3);
            this.khachhangBtn.IconMarginLeft = 11;
            this.khachhangBtn.IconPadding = 10;
            this.khachhangBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.khachhangBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.khachhangBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.khachhangBtn.IconSize = 25;
            this.khachhangBtn.IdleBorderColor = System.Drawing.Color.White;
            this.khachhangBtn.IdleBorderRadius = 1;
            this.khachhangBtn.IdleBorderThickness = 1;
            this.khachhangBtn.IdleFillColor = System.Drawing.Color.White;
            this.khachhangBtn.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("khachhangBtn.IdleIconLeftImage")));
            this.khachhangBtn.IdleIconRightImage = null;
            this.khachhangBtn.ImeMode = System.Windows.Forms.ImeMode.NoControl;
            this.khachhangBtn.IndicateFocus = false;
            this.khachhangBtn.Location = new System.Drawing.Point(0, 450);
            this.khachhangBtn.Name = "khachhangBtn";
            this.khachhangBtn.OnDisabledState.BorderColor = System.Drawing.Color.Empty;
            this.khachhangBtn.OnDisabledState.BorderRadius = 1;
            this.khachhangBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.khachhangBtn.OnDisabledState.BorderThickness = 1;
            this.khachhangBtn.OnDisabledState.FillColor = System.Drawing.Color.White;
            this.khachhangBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.khachhangBtn.OnDisabledState.IconLeftImage = null;
            this.khachhangBtn.OnDisabledState.IconRightImage = null;
            this.khachhangBtn.onHoverState.BorderColor = System.Drawing.Color.White;
            this.khachhangBtn.onHoverState.BorderRadius = 1;
            this.khachhangBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.khachhangBtn.onHoverState.BorderThickness = 1;
            this.khachhangBtn.onHoverState.FillColor = System.Drawing.Color.White;
            this.khachhangBtn.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(125)))), ((int)(((byte)(250)))));
            this.khachhangBtn.onHoverState.IconLeftImage = global::BTL.Properties.Resources.khachhang_color;
            this.khachhangBtn.onHoverState.IconRightImage = null;
            this.khachhangBtn.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.khachhangBtn.OnIdleState.BorderRadius = 1;
            this.khachhangBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.khachhangBtn.OnIdleState.BorderThickness = 1;
            this.khachhangBtn.OnIdleState.FillColor = System.Drawing.Color.White;
            this.khachhangBtn.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(223)))), ((int)(((byte)(230)))), ((int)(((byte)(241)))));
            this.khachhangBtn.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("khachhangBtn.OnIdleState.IconLeftImage")));
            this.khachhangBtn.OnIdleState.IconRightImage = null;
            this.khachhangBtn.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.khachhangBtn.OnPressedState.BorderRadius = 1;
            this.khachhangBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.khachhangBtn.OnPressedState.BorderThickness = 1;
            this.khachhangBtn.OnPressedState.FillColor = System.Drawing.Color.White;
            this.khachhangBtn.OnPressedState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(125)))), ((int)(((byte)(250)))));
            this.khachhangBtn.OnPressedState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("resource.IconLeftImage9")));
            this.khachhangBtn.OnPressedState.IconRightImage = null;
            this.khachhangBtn.Size = new System.Drawing.Size(112, 43);
            this.khachhangBtn.TabIndex = 22;
            this.khachhangBtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.khachhangBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.khachhangBtn.TextMarginLeft = 0;
            this.khachhangBtn.TextPadding = new System.Windows.Forms.Padding(0);
            this.khachhangBtn.UseDefaultRadiusAndThickness = true;
            // 
            // bunifuPanel2
            // 
            this.bunifuPanel2.BackgroundColor = System.Drawing.Color.White;
            this.bunifuPanel2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel2.BackgroundImage")));
            this.bunifuPanel2.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel2.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuPanel2.BorderRadius = 20;
            this.bunifuPanel2.BorderThickness = 1;
            this.bunifuPanel2.Location = new System.Drawing.Point(1032, 12);
            this.bunifuPanel2.Name = "bunifuPanel2";
            this.bunifuPanel2.ShowBorders = true;
            this.bunifuPanel2.Size = new System.Drawing.Size(209, 65);
            this.bunifuPanel2.TabIndex = 27;
            // 
            // formDoanhThu
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(239)))), ((int)(((byte)(243)))), ((int)(((byte)(249)))));
            this.ClientSize = new System.Drawing.Size(1271, 785);
            this.Controls.Add(this.bunifuPanel2);
            this.Controls.Add(this.bunifuShadowPanel1);
            this.Name = "formDoanhThu";
            this.Text = "frDoanhThu";
            this.bunifuShadowPanel1.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.indicatorLine)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuShadowPanel bunifuShadowPanel1;
        private System.Windows.Forms.PictureBox indicatorLine;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 lienheBtn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 trangchuBtn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 hanghoaBtn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 hoadonBtn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 nhanhvienBtn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 khachhangBtn;
        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel2;
    }
}