namespace BTL.GUI
{
    partial class formKhachHang
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(formKhachHang));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle1 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle3 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle4 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle5 = new System.Windows.Forms.DataGridViewCellStyle();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            this.khachhangSearchBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.khachhangSearch = new Bunifu.UI.WinForms.BunifuTextBox();
            this.khachhangTitle = new Bunifu.UI.WinForms.BunifuLabel();
            this.khachhangPanel = new Bunifu.UI.WinForms.BunifuPanel();
            this.khachhangTable = new Guna.UI2.WinForms.Guna2DataGridView();
            this.xuatKhachHang = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.khachhangPanelSub = new Bunifu.UI.WinForms.BunifuLabel();
            this.khachhangPanelTitle = new Bunifu.UI.WinForms.BunifuLabel();
            this.khachhangLuuBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.khachhangThemBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.khachhangXoaBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.bunifuPanel2 = new Bunifu.UI.WinForms.BunifuPanel();
            this.khachhangPanel.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.khachhangTable)).BeginInit();
            this.SuspendLayout();
            // 
            // khachhangSearchBtn
            // 
            this.khachhangSearchBtn.AllowAnimations = true;
            this.khachhangSearchBtn.AllowMouseEffects = true;
            this.khachhangSearchBtn.AllowToggling = false;
            this.khachhangSearchBtn.AnimationSpeed = 200;
            this.khachhangSearchBtn.AutoGenerateColors = false;
            this.khachhangSearchBtn.AutoRoundBorders = false;
            this.khachhangSearchBtn.AutoSizeLeftIcon = true;
            this.khachhangSearchBtn.AutoSizeRightIcon = true;
            this.khachhangSearchBtn.BackColor = System.Drawing.Color.Transparent;
            this.khachhangSearchBtn.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.khachhangSearchBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("khachhangSearchBtn.BackgroundImage")));
            this.khachhangSearchBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.khachhangSearchBtn.ButtonText = "";
            this.khachhangSearchBtn.ButtonTextMarginLeft = 0;
            this.khachhangSearchBtn.ColorContrastOnClick = 45;
            this.khachhangSearchBtn.ColorContrastOnHover = 45;
            this.khachhangSearchBtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.khachhangSearchBtn.CustomizableEdges = borderEdges1;
            this.khachhangSearchBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.khachhangSearchBtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.khachhangSearchBtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.khachhangSearchBtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.khachhangSearchBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.khachhangSearchBtn.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.khachhangSearchBtn.ForeColor = System.Drawing.Color.White;
            this.khachhangSearchBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.khachhangSearchBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.khachhangSearchBtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.khachhangSearchBtn.IconMarginLeft = 11;
            this.khachhangSearchBtn.IconPadding = 10;
            this.khachhangSearchBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.khachhangSearchBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.khachhangSearchBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.khachhangSearchBtn.IconSize = 25;
            this.khachhangSearchBtn.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.khachhangSearchBtn.IdleBorderRadius = 25;
            this.khachhangSearchBtn.IdleBorderThickness = 1;
            this.khachhangSearchBtn.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.khachhangSearchBtn.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("khachhangSearchBtn.IdleIconLeftImage")));
            this.khachhangSearchBtn.IdleIconRightImage = null;
            this.khachhangSearchBtn.IndicateFocus = false;
            this.khachhangSearchBtn.Location = new System.Drawing.Point(644, 23);
            this.khachhangSearchBtn.Name = "khachhangSearchBtn";
            this.khachhangSearchBtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.khachhangSearchBtn.OnDisabledState.BorderRadius = 25;
            this.khachhangSearchBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.khachhangSearchBtn.OnDisabledState.BorderThickness = 1;
            this.khachhangSearchBtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.khachhangSearchBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.khachhangSearchBtn.OnDisabledState.IconLeftImage = null;
            this.khachhangSearchBtn.OnDisabledState.IconRightImage = null;
            this.khachhangSearchBtn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.khachhangSearchBtn.onHoverState.BorderRadius = 25;
            this.khachhangSearchBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.khachhangSearchBtn.onHoverState.BorderThickness = 1;
            this.khachhangSearchBtn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.khachhangSearchBtn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.khachhangSearchBtn.onHoverState.IconLeftImage = null;
            this.khachhangSearchBtn.onHoverState.IconRightImage = null;
            this.khachhangSearchBtn.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.khachhangSearchBtn.OnIdleState.BorderRadius = 25;
            this.khachhangSearchBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.khachhangSearchBtn.OnIdleState.BorderThickness = 1;
            this.khachhangSearchBtn.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.khachhangSearchBtn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.khachhangSearchBtn.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("khachhangSearchBtn.OnIdleState.IconLeftImage")));
            this.khachhangSearchBtn.OnIdleState.IconRightImage = null;
            this.khachhangSearchBtn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.khachhangSearchBtn.OnPressedState.BorderRadius = 25;
            this.khachhangSearchBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.khachhangSearchBtn.OnPressedState.BorderThickness = 1;
            this.khachhangSearchBtn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.khachhangSearchBtn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.khachhangSearchBtn.OnPressedState.IconLeftImage = null;
            this.khachhangSearchBtn.OnPressedState.IconRightImage = null;
            this.khachhangSearchBtn.Size = new System.Drawing.Size(42, 39);
            this.khachhangSearchBtn.TabIndex = 22;
            this.khachhangSearchBtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.khachhangSearchBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.khachhangSearchBtn.TextMarginLeft = 0;
            this.khachhangSearchBtn.TextPadding = new System.Windows.Forms.Padding(0);
            this.khachhangSearchBtn.UseDefaultRadiusAndThickness = true;
            this.khachhangSearchBtn.Click += new System.EventHandler(this.khachhangSearchBtn_Click);
            // 
            // khachhangSearch
            // 
            this.khachhangSearch.AcceptsReturn = false;
            this.khachhangSearch.AcceptsTab = false;
            this.khachhangSearch.AnimationSpeed = 200;
            this.khachhangSearch.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.khachhangSearch.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.khachhangSearch.AutoSizeHeight = true;
            this.khachhangSearch.BackColor = System.Drawing.Color.Transparent;
            this.khachhangSearch.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("khachhangSearch.BackgroundImage")));
            this.khachhangSearch.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.khachhangSearch.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.khachhangSearch.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.khachhangSearch.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(235)))), ((int)(((byte)(235)))), ((int)(((byte)(235)))));
            this.khachhangSearch.BorderRadius = 20;
            this.khachhangSearch.BorderThickness = 1;
            this.khachhangSearch.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.khachhangSearch.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.khachhangSearch.DefaultFont = new System.Drawing.Font("Segoe UI", 10F);
            this.khachhangSearch.DefaultText = "";
            this.khachhangSearch.FillColor = System.Drawing.Color.White;
            this.khachhangSearch.HideSelection = true;
            this.khachhangSearch.IconLeft = ((System.Drawing.Image)(resources.GetObject("khachhangSearch.IconLeft")));
            this.khachhangSearch.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.khachhangSearch.IconPadding = 10;
            this.khachhangSearch.IconRight = null;
            this.khachhangSearch.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.khachhangSearch.Lines = new string[0];
            this.khachhangSearch.Location = new System.Drawing.Point(271, 21);
            this.khachhangSearch.Margin = new System.Windows.Forms.Padding(20, 3, 3, 3);
            this.khachhangSearch.MaxLength = 32767;
            this.khachhangSearch.MinimumSize = new System.Drawing.Size(1, 1);
            this.khachhangSearch.Modified = false;
            this.khachhangSearch.Multiline = false;
            this.khachhangSearch.Name = "khachhangSearch";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.khachhangSearch.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.khachhangSearch.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.khachhangSearch.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(235)))), ((int)(((byte)(235)))), ((int)(((byte)(235)))));
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.khachhangSearch.OnIdleState = stateProperties4;
            this.khachhangSearch.Padding = new System.Windows.Forms.Padding(40, 3, 3, 3);
            this.khachhangSearch.PasswordChar = '\0';
            this.khachhangSearch.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.khachhangSearch.PlaceholderText = "Tìm kiếm";
            this.khachhangSearch.ReadOnly = false;
            this.khachhangSearch.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.khachhangSearch.SelectedText = "";
            this.khachhangSearch.SelectionLength = 0;
            this.khachhangSearch.SelectionStart = 0;
            this.khachhangSearch.ShortcutsEnabled = true;
            this.khachhangSearch.Size = new System.Drawing.Size(367, 41);
            this.khachhangSearch.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.khachhangSearch.TabIndex = 21;
            this.khachhangSearch.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.khachhangSearch.TextMarginBottom = 0;
            this.khachhangSearch.TextMarginLeft = 15;
            this.khachhangSearch.TextMarginTop = 0;
            this.khachhangSearch.TextPlaceholder = "Tìm kiếm";
            this.khachhangSearch.UseSystemPasswordChar = false;
            this.khachhangSearch.WordWrap = true;
            this.khachhangSearch.KeyDown += new System.Windows.Forms.KeyEventHandler(this.khachhangSearch_KeyDown);
            // 
            // khachhangTitle
            // 
            this.khachhangTitle.AllowParentOverrides = false;
            this.khachhangTitle.AutoEllipsis = false;
            this.khachhangTitle.Cursor = System.Windows.Forms.Cursors.Default;
            this.khachhangTitle.CursorType = System.Windows.Forms.Cursors.Default;
            this.khachhangTitle.Font = new System.Drawing.Font("Segoe UI Semibold", 13F, System.Drawing.FontStyle.Bold);
            this.khachhangTitle.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(79)))), ((int)(((byte)(79)))), ((int)(((byte)(79)))));
            this.khachhangTitle.Location = new System.Drawing.Point(134, 23);
            this.khachhangTitle.Name = "khachhangTitle";
            this.khachhangTitle.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.khachhangTitle.Size = new System.Drawing.Size(119, 30);
            this.khachhangTitle.TabIndex = 20;
            this.khachhangTitle.Text = "Khách Hàng";
            this.khachhangTitle.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.khachhangTitle.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // khachhangPanel
            // 
            this.khachhangPanel.BackgroundColor = System.Drawing.Color.White;
            this.khachhangPanel.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("khachhangPanel.BackgroundImage")));
            this.khachhangPanel.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.khachhangPanel.BorderColor = System.Drawing.Color.Gainsboro;
            this.khachhangPanel.BorderRadius = 25;
            this.khachhangPanel.BorderThickness = 1;
            this.khachhangPanel.Controls.Add(this.khachhangTable);
            this.khachhangPanel.Controls.Add(this.xuatKhachHang);
            this.khachhangPanel.Controls.Add(this.khachhangPanelSub);
            this.khachhangPanel.Controls.Add(this.khachhangPanelTitle);
            this.khachhangPanel.Controls.Add(this.khachhangLuuBtn);
            this.khachhangPanel.Controls.Add(this.khachhangThemBtn);
            this.khachhangPanel.Controls.Add(this.khachhangXoaBtn);
            this.khachhangPanel.Location = new System.Drawing.Point(134, 127);
            this.khachhangPanel.Name = "khachhangPanel";
            this.khachhangPanel.ShowBorders = true;
            this.khachhangPanel.Size = new System.Drawing.Size(1107, 630);
            this.khachhangPanel.TabIndex = 23;
            // 
            // khachhangTable
            // 
            this.khachhangTable.AllowUserToAddRows = false;
            this.khachhangTable.AllowUserToDeleteRows = false;
            dataGridViewCellStyle1.BackColor = System.Drawing.Color.White;
            this.khachhangTable.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle1;
            this.khachhangTable.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.khachhangTable.BackgroundColor = System.Drawing.Color.White;
            this.khachhangTable.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.khachhangTable.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.khachhangTable.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle2.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle2.BackColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.Font = new System.Drawing.Font("Segoe UI Semibold", 10.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            dataGridViewCellStyle2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(33)))), ((int)(((byte)(35)))), ((int)(((byte)(74)))));
            dataGridViewCellStyle2.Padding = new System.Windows.Forms.Padding(15, 0, 15, 0);
            dataGridViewCellStyle2.SelectionBackColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.SelectionForeColor = System.Drawing.SystemColors.HighlightText;
            dataGridViewCellStyle2.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.khachhangTable.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2;
            this.khachhangTable.ColumnHeadersHeight = 55;
            this.khachhangTable.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.DisableResizing;
            dataGridViewCellStyle3.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle3.BackColor = System.Drawing.Color.White;
            dataGridViewCellStyle3.Font = new System.Drawing.Font("Segoe UI Semibold", 9F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle3.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(71)))), ((int)(((byte)(69)))), ((int)(((byte)(94)))));
            dataGridViewCellStyle3.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(231)))), ((int)(((byte)(229)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle3.SelectionForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(71)))), ((int)(((byte)(69)))), ((int)(((byte)(94)))));
            dataGridViewCellStyle3.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.khachhangTable.DefaultCellStyle = dataGridViewCellStyle3;
            this.khachhangTable.EnableHeadersVisualStyles = false;
            this.khachhangTable.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(231)))), ((int)(((byte)(229)))), ((int)(((byte)(255)))));
            this.khachhangTable.Location = new System.Drawing.Point(42, 122);
            this.khachhangTable.Name = "khachhangTable";
            this.khachhangTable.ReadOnly = true;
            this.khachhangTable.RowHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.Single;
            dataGridViewCellStyle4.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleCenter;
            dataGridViewCellStyle4.BackColor = System.Drawing.SystemColors.Control;
            dataGridViewCellStyle4.Font = new System.Drawing.Font("Microsoft Sans Serif", 7.8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            dataGridViewCellStyle4.ForeColor = System.Drawing.SystemColors.WindowText;
            dataGridViewCellStyle4.Padding = new System.Windows.Forms.Padding(0, 0, 0, 10);
            dataGridViewCellStyle4.SelectionBackColor = System.Drawing.Color.White;
            dataGridViewCellStyle4.SelectionForeColor = System.Drawing.SystemColors.HighlightText;
            dataGridViewCellStyle4.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.khachhangTable.RowHeadersDefaultCellStyle = dataGridViewCellStyle4;
            this.khachhangTable.RowHeadersVisible = false;
            this.khachhangTable.RowHeadersWidth = 51;
            this.khachhangTable.RowHeadersWidthSizeMode = System.Windows.Forms.DataGridViewRowHeadersWidthSizeMode.DisableResizing;
            dataGridViewCellStyle5.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle5.Padding = new System.Windows.Forms.Padding(15, 0, 0, 5);
            dataGridViewCellStyle5.SelectionBackColor = System.Drawing.Color.AliceBlue;
            this.khachhangTable.RowsDefaultCellStyle = dataGridViewCellStyle5;
            this.khachhangTable.RowTemplate.Height = 55;
            this.khachhangTable.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.khachhangTable.Size = new System.Drawing.Size(1029, 470);
            this.khachhangTable.TabIndex = 47;
            this.khachhangTable.ThemeStyle.AlternatingRowsStyle.BackColor = System.Drawing.Color.White;
            this.khachhangTable.ThemeStyle.AlternatingRowsStyle.Font = null;
            this.khachhangTable.ThemeStyle.AlternatingRowsStyle.ForeColor = System.Drawing.Color.Empty;
            this.khachhangTable.ThemeStyle.AlternatingRowsStyle.SelectionBackColor = System.Drawing.Color.Empty;
            this.khachhangTable.ThemeStyle.AlternatingRowsStyle.SelectionForeColor = System.Drawing.Color.Empty;
            this.khachhangTable.ThemeStyle.BackColor = System.Drawing.Color.White;
            this.khachhangTable.ThemeStyle.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(231)))), ((int)(((byte)(229)))), ((int)(((byte)(255)))));
            this.khachhangTable.ThemeStyle.HeaderStyle.BackColor = System.Drawing.Color.White;
            this.khachhangTable.ThemeStyle.HeaderStyle.BorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            this.khachhangTable.ThemeStyle.HeaderStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 10.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            this.khachhangTable.ThemeStyle.HeaderStyle.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(33)))), ((int)(((byte)(35)))), ((int)(((byte)(74)))));
            this.khachhangTable.ThemeStyle.HeaderStyle.HeaightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.DisableResizing;
            this.khachhangTable.ThemeStyle.HeaderStyle.Height = 55;
            this.khachhangTable.ThemeStyle.ReadOnly = true;
            this.khachhangTable.ThemeStyle.RowsStyle.BackColor = System.Drawing.Color.White;
            this.khachhangTable.ThemeStyle.RowsStyle.BorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.khachhangTable.ThemeStyle.RowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9F, System.Drawing.FontStyle.Bold);
            this.khachhangTable.ThemeStyle.RowsStyle.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(71)))), ((int)(((byte)(69)))), ((int)(((byte)(94)))));
            this.khachhangTable.ThemeStyle.RowsStyle.Height = 55;
            this.khachhangTable.ThemeStyle.RowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(231)))), ((int)(((byte)(229)))), ((int)(((byte)(255)))));
            this.khachhangTable.ThemeStyle.RowsStyle.SelectionForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(71)))), ((int)(((byte)(69)))), ((int)(((byte)(94)))));
            // 
            // xuatKhachHang
            // 
            this.xuatKhachHang.AllowAnimations = true;
            this.xuatKhachHang.AllowMouseEffects = true;
            this.xuatKhachHang.AllowToggling = false;
            this.xuatKhachHang.AnimationSpeed = 200;
            this.xuatKhachHang.AutoGenerateColors = false;
            this.xuatKhachHang.AutoRoundBorders = false;
            this.xuatKhachHang.AutoSizeLeftIcon = true;
            this.xuatKhachHang.AutoSizeRightIcon = true;
            this.xuatKhachHang.BackColor = System.Drawing.Color.Transparent;
            this.xuatKhachHang.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(127)))), ((int)(((byte)(127)))), ((int)(((byte)(213)))));
            this.xuatKhachHang.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("xuatKhachHang.BackgroundImage")));
            this.xuatKhachHang.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.xuatKhachHang.ButtonText = "Xuất File";
            this.xuatKhachHang.ButtonTextMarginLeft = 0;
            this.xuatKhachHang.ColorContrastOnClick = 45;
            this.xuatKhachHang.ColorContrastOnHover = 45;
            this.xuatKhachHang.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.xuatKhachHang.CustomizableEdges = borderEdges2;
            this.xuatKhachHang.DialogResult = System.Windows.Forms.DialogResult.None;
            this.xuatKhachHang.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.xuatKhachHang.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.xuatKhachHang.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.xuatKhachHang.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.xuatKhachHang.Font = new System.Drawing.Font("Segoe UI Semibold", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            this.xuatKhachHang.ForeColor = System.Drawing.Color.White;
            this.xuatKhachHang.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.xuatKhachHang.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.xuatKhachHang.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.xuatKhachHang.IconMarginLeft = 11;
            this.xuatKhachHang.IconPadding = 10;
            this.xuatKhachHang.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.xuatKhachHang.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.xuatKhachHang.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.xuatKhachHang.IconSize = 25;
            this.xuatKhachHang.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(127)))), ((int)(((byte)(127)))), ((int)(((byte)(213)))));
            this.xuatKhachHang.IdleBorderRadius = 10;
            this.xuatKhachHang.IdleBorderThickness = 1;
            this.xuatKhachHang.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(127)))), ((int)(((byte)(127)))), ((int)(((byte)(213)))));
            this.xuatKhachHang.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("xuatKhachHang.IdleIconLeftImage")));
            this.xuatKhachHang.IdleIconRightImage = null;
            this.xuatKhachHang.IndicateFocus = false;
            this.xuatKhachHang.Location = new System.Drawing.Point(911, 35);
            this.xuatKhachHang.Name = "xuatKhachHang";
            this.xuatKhachHang.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.xuatKhachHang.OnDisabledState.BorderRadius = 10;
            this.xuatKhachHang.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.xuatKhachHang.OnDisabledState.BorderThickness = 1;
            this.xuatKhachHang.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.xuatKhachHang.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.xuatKhachHang.OnDisabledState.IconLeftImage = null;
            this.xuatKhachHang.OnDisabledState.IconRightImage = null;
            this.xuatKhachHang.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.xuatKhachHang.onHoverState.BorderRadius = 10;
            this.xuatKhachHang.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.xuatKhachHang.onHoverState.BorderThickness = 1;
            this.xuatKhachHang.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.xuatKhachHang.onHoverState.ForeColor = System.Drawing.Color.White;
            this.xuatKhachHang.onHoverState.IconLeftImage = null;
            this.xuatKhachHang.onHoverState.IconRightImage = null;
            this.xuatKhachHang.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(127)))), ((int)(((byte)(127)))), ((int)(((byte)(213)))));
            this.xuatKhachHang.OnIdleState.BorderRadius = 10;
            this.xuatKhachHang.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.xuatKhachHang.OnIdleState.BorderThickness = 1;
            this.xuatKhachHang.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(127)))), ((int)(((byte)(127)))), ((int)(((byte)(213)))));
            this.xuatKhachHang.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.xuatKhachHang.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("xuatKhachHang.OnIdleState.IconLeftImage")));
            this.xuatKhachHang.OnIdleState.IconRightImage = null;
            this.xuatKhachHang.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.xuatKhachHang.OnPressedState.BorderRadius = 10;
            this.xuatKhachHang.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.xuatKhachHang.OnPressedState.BorderThickness = 1;
            this.xuatKhachHang.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.xuatKhachHang.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.xuatKhachHang.OnPressedState.IconLeftImage = null;
            this.xuatKhachHang.OnPressedState.IconRightImage = null;
            this.xuatKhachHang.Size = new System.Drawing.Size(161, 40);
            this.xuatKhachHang.TabIndex = 42;
            this.xuatKhachHang.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.xuatKhachHang.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.xuatKhachHang.TextMarginLeft = 0;
            this.xuatKhachHang.TextPadding = new System.Windows.Forms.Padding(15, 0, 0, 0);
            this.xuatKhachHang.UseDefaultRadiusAndThickness = true;
            this.xuatKhachHang.Click += new System.EventHandler(this.xuatKhachHang_Click);
            // 
            // khachhangPanelSub
            // 
            this.khachhangPanelSub.AllowParentOverrides = false;
            this.khachhangPanelSub.AutoEllipsis = false;
            this.khachhangPanelSub.CursorType = null;
            this.khachhangPanelSub.Font = new System.Drawing.Font("Segoe UI", 7F);
            this.khachhangPanelSub.ForeColor = System.Drawing.SystemColors.ActiveBorder;
            this.khachhangPanelSub.Location = new System.Drawing.Point(43, 60);
            this.khachhangPanelSub.Name = "khachhangPanelSub";
            this.khachhangPanelSub.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.khachhangPanelSub.Size = new System.Drawing.Size(128, 15);
            this.khachhangPanelSub.TabIndex = 40;
            this.khachhangPanelSub.Text = "Tìm thấy một số kết quả";
            this.khachhangPanelSub.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.khachhangPanelSub.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // khachhangPanelTitle
            // 
            this.khachhangPanelTitle.AllowParentOverrides = false;
            this.khachhangPanelTitle.AutoEllipsis = false;
            this.khachhangPanelTitle.CursorType = null;
            this.khachhangPanelTitle.Font = new System.Drawing.Font("Segoe UI Semibold", 13F, System.Drawing.FontStyle.Bold);
            this.khachhangPanelTitle.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(79)))), ((int)(((byte)(79)))), ((int)(((byte)(79)))));
            this.khachhangPanelTitle.Location = new System.Drawing.Point(43, 24);
            this.khachhangPanelTitle.Name = "khachhangPanelTitle";
            this.khachhangPanelTitle.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.khachhangPanelTitle.Size = new System.Drawing.Size(226, 30);
            this.khachhangPanelTitle.TabIndex = 41;
            this.khachhangPanelTitle.Text = "Thông Tin Khách Hàng";
            this.khachhangPanelTitle.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.khachhangPanelTitle.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // khachhangLuuBtn
            // 
            this.khachhangLuuBtn.AllowAnimations = true;
            this.khachhangLuuBtn.AllowMouseEffects = true;
            this.khachhangLuuBtn.AllowToggling = false;
            this.khachhangLuuBtn.AnimationSpeed = 200;
            this.khachhangLuuBtn.AutoGenerateColors = false;
            this.khachhangLuuBtn.AutoRoundBorders = false;
            this.khachhangLuuBtn.AutoSizeLeftIcon = true;
            this.khachhangLuuBtn.AutoSizeRightIcon = true;
            this.khachhangLuuBtn.BackColor = System.Drawing.Color.Transparent;
            this.khachhangLuuBtn.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.khachhangLuuBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("khachhangLuuBtn.BackgroundImage")));
            this.khachhangLuuBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.khachhangLuuBtn.ButtonText = "Sửa";
            this.khachhangLuuBtn.ButtonTextMarginLeft = 0;
            this.khachhangLuuBtn.ColorContrastOnClick = 45;
            this.khachhangLuuBtn.ColorContrastOnHover = 45;
            this.khachhangLuuBtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.khachhangLuuBtn.CustomizableEdges = borderEdges3;
            this.khachhangLuuBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.khachhangLuuBtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.khachhangLuuBtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.khachhangLuuBtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.khachhangLuuBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.khachhangLuuBtn.Font = new System.Drawing.Font("Segoe UI Semibold", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            this.khachhangLuuBtn.ForeColor = System.Drawing.Color.White;
            this.khachhangLuuBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.khachhangLuuBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.khachhangLuuBtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.khachhangLuuBtn.IconMarginLeft = 11;
            this.khachhangLuuBtn.IconPadding = 10;
            this.khachhangLuuBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.khachhangLuuBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.khachhangLuuBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.khachhangLuuBtn.IconSize = 25;
            this.khachhangLuuBtn.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.khachhangLuuBtn.IdleBorderRadius = 10;
            this.khachhangLuuBtn.IdleBorderThickness = 1;
            this.khachhangLuuBtn.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.khachhangLuuBtn.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("khachhangLuuBtn.IdleIconLeftImage")));
            this.khachhangLuuBtn.IdleIconRightImage = null;
            this.khachhangLuuBtn.IndicateFocus = false;
            this.khachhangLuuBtn.Location = new System.Drawing.Point(798, 35);
            this.khachhangLuuBtn.Name = "khachhangLuuBtn";
            this.khachhangLuuBtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.khachhangLuuBtn.OnDisabledState.BorderRadius = 10;
            this.khachhangLuuBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.khachhangLuuBtn.OnDisabledState.BorderThickness = 1;
            this.khachhangLuuBtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.khachhangLuuBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.khachhangLuuBtn.OnDisabledState.IconLeftImage = null;
            this.khachhangLuuBtn.OnDisabledState.IconRightImage = null;
            this.khachhangLuuBtn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.khachhangLuuBtn.onHoverState.BorderRadius = 10;
            this.khachhangLuuBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.khachhangLuuBtn.onHoverState.BorderThickness = 1;
            this.khachhangLuuBtn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.khachhangLuuBtn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.khachhangLuuBtn.onHoverState.IconLeftImage = null;
            this.khachhangLuuBtn.onHoverState.IconRightImage = null;
            this.khachhangLuuBtn.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.khachhangLuuBtn.OnIdleState.BorderRadius = 10;
            this.khachhangLuuBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.khachhangLuuBtn.OnIdleState.BorderThickness = 1;
            this.khachhangLuuBtn.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.khachhangLuuBtn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.khachhangLuuBtn.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("khachhangLuuBtn.OnIdleState.IconLeftImage")));
            this.khachhangLuuBtn.OnIdleState.IconRightImage = null;
            this.khachhangLuuBtn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.khachhangLuuBtn.OnPressedState.BorderRadius = 10;
            this.khachhangLuuBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.khachhangLuuBtn.OnPressedState.BorderThickness = 1;
            this.khachhangLuuBtn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.khachhangLuuBtn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.khachhangLuuBtn.OnPressedState.IconLeftImage = null;
            this.khachhangLuuBtn.OnPressedState.IconRightImage = null;
            this.khachhangLuuBtn.Size = new System.Drawing.Size(96, 40);
            this.khachhangLuuBtn.TabIndex = 5;
            this.khachhangLuuBtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.khachhangLuuBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.khachhangLuuBtn.TextMarginLeft = 0;
            this.khachhangLuuBtn.TextPadding = new System.Windows.Forms.Padding(15, 0, 0, 0);
            this.khachhangLuuBtn.UseDefaultRadiusAndThickness = true;
            this.khachhangLuuBtn.Click += new System.EventHandler(this.khachhangLuuBtn_Click);
            // 
            // khachhangThemBtn
            // 
            this.khachhangThemBtn.AllowAnimations = true;
            this.khachhangThemBtn.AllowMouseEffects = true;
            this.khachhangThemBtn.AllowToggling = false;
            this.khachhangThemBtn.AnimationSpeed = 200;
            this.khachhangThemBtn.AutoGenerateColors = false;
            this.khachhangThemBtn.AutoRoundBorders = false;
            this.khachhangThemBtn.AutoSizeLeftIcon = true;
            this.khachhangThemBtn.AutoSizeRightIcon = true;
            this.khachhangThemBtn.BackColor = System.Drawing.Color.Transparent;
            this.khachhangThemBtn.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(95)))), ((int)(((byte)(210)))), ((int)(((byte)(143)))));
            this.khachhangThemBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("khachhangThemBtn.BackgroundImage")));
            this.khachhangThemBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.khachhangThemBtn.ButtonText = "Thêm";
            this.khachhangThemBtn.ButtonTextMarginLeft = 0;
            this.khachhangThemBtn.ColorContrastOnClick = 45;
            this.khachhangThemBtn.ColorContrastOnHover = 45;
            this.khachhangThemBtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.khachhangThemBtn.CustomizableEdges = borderEdges4;
            this.khachhangThemBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.khachhangThemBtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.khachhangThemBtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.khachhangThemBtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.khachhangThemBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.khachhangThemBtn.Font = new System.Drawing.Font("Segoe UI Semibold", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            this.khachhangThemBtn.ForeColor = System.Drawing.Color.White;
            this.khachhangThemBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.khachhangThemBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.khachhangThemBtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.khachhangThemBtn.IconMarginLeft = 11;
            this.khachhangThemBtn.IconPadding = 10;
            this.khachhangThemBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.khachhangThemBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.khachhangThemBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.khachhangThemBtn.IconSize = 25;
            this.khachhangThemBtn.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(95)))), ((int)(((byte)(210)))), ((int)(((byte)(143)))));
            this.khachhangThemBtn.IdleBorderRadius = 10;
            this.khachhangThemBtn.IdleBorderThickness = 1;
            this.khachhangThemBtn.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(95)))), ((int)(((byte)(210)))), ((int)(((byte)(143)))));
            this.khachhangThemBtn.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("khachhangThemBtn.IdleIconLeftImage")));
            this.khachhangThemBtn.IdleIconRightImage = null;
            this.khachhangThemBtn.IndicateFocus = false;
            this.khachhangThemBtn.Location = new System.Drawing.Point(564, 35);
            this.khachhangThemBtn.Name = "khachhangThemBtn";
            this.khachhangThemBtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.khachhangThemBtn.OnDisabledState.BorderRadius = 10;
            this.khachhangThemBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.khachhangThemBtn.OnDisabledState.BorderThickness = 1;
            this.khachhangThemBtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.khachhangThemBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.khachhangThemBtn.OnDisabledState.IconLeftImage = null;
            this.khachhangThemBtn.OnDisabledState.IconRightImage = null;
            this.khachhangThemBtn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.khachhangThemBtn.onHoverState.BorderRadius = 10;
            this.khachhangThemBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.khachhangThemBtn.onHoverState.BorderThickness = 1;
            this.khachhangThemBtn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.khachhangThemBtn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.khachhangThemBtn.onHoverState.IconLeftImage = null;
            this.khachhangThemBtn.onHoverState.IconRightImage = null;
            this.khachhangThemBtn.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(95)))), ((int)(((byte)(210)))), ((int)(((byte)(143)))));
            this.khachhangThemBtn.OnIdleState.BorderRadius = 10;
            this.khachhangThemBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.khachhangThemBtn.OnIdleState.BorderThickness = 1;
            this.khachhangThemBtn.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(95)))), ((int)(((byte)(210)))), ((int)(((byte)(143)))));
            this.khachhangThemBtn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.khachhangThemBtn.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("khachhangThemBtn.OnIdleState.IconLeftImage")));
            this.khachhangThemBtn.OnIdleState.IconRightImage = null;
            this.khachhangThemBtn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.khachhangThemBtn.OnPressedState.BorderRadius = 10;
            this.khachhangThemBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.khachhangThemBtn.OnPressedState.BorderThickness = 1;
            this.khachhangThemBtn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.khachhangThemBtn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.khachhangThemBtn.OnPressedState.IconLeftImage = null;
            this.khachhangThemBtn.OnPressedState.IconRightImage = null;
            this.khachhangThemBtn.Size = new System.Drawing.Size(96, 40);
            this.khachhangThemBtn.TabIndex = 4;
            this.khachhangThemBtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.khachhangThemBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.khachhangThemBtn.TextMarginLeft = 0;
            this.khachhangThemBtn.TextPadding = new System.Windows.Forms.Padding(15, 0, 0, 0);
            this.khachhangThemBtn.UseDefaultRadiusAndThickness = true;
            this.khachhangThemBtn.Click += new System.EventHandler(this.khachhangThemBtn_Click);
            // 
            // khachhangXoaBtn
            // 
            this.khachhangXoaBtn.AllowAnimations = true;
            this.khachhangXoaBtn.AllowMouseEffects = true;
            this.khachhangXoaBtn.AllowToggling = false;
            this.khachhangXoaBtn.AnimationSpeed = 200;
            this.khachhangXoaBtn.AutoGenerateColors = false;
            this.khachhangXoaBtn.AutoRoundBorders = false;
            this.khachhangXoaBtn.AutoSizeLeftIcon = true;
            this.khachhangXoaBtn.AutoSizeRightIcon = true;
            this.khachhangXoaBtn.BackColor = System.Drawing.Color.Transparent;
            this.khachhangXoaBtn.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(246)))), ((int)(((byte)(78)))), ((int)(((byte)(96)))));
            this.khachhangXoaBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("khachhangXoaBtn.BackgroundImage")));
            this.khachhangXoaBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.khachhangXoaBtn.ButtonText = "Xóa";
            this.khachhangXoaBtn.ButtonTextMarginLeft = 0;
            this.khachhangXoaBtn.ColorContrastOnClick = 45;
            this.khachhangXoaBtn.ColorContrastOnHover = 45;
            this.khachhangXoaBtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.khachhangXoaBtn.CustomizableEdges = borderEdges5;
            this.khachhangXoaBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.khachhangXoaBtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.khachhangXoaBtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.khachhangXoaBtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.khachhangXoaBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.khachhangXoaBtn.Font = new System.Drawing.Font("Segoe UI Semibold", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            this.khachhangXoaBtn.ForeColor = System.Drawing.Color.White;
            this.khachhangXoaBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.khachhangXoaBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.khachhangXoaBtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.khachhangXoaBtn.IconMarginLeft = 11;
            this.khachhangXoaBtn.IconPadding = 10;
            this.khachhangXoaBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.khachhangXoaBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.khachhangXoaBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.khachhangXoaBtn.IconSize = 25;
            this.khachhangXoaBtn.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(246)))), ((int)(((byte)(78)))), ((int)(((byte)(96)))));
            this.khachhangXoaBtn.IdleBorderRadius = 10;
            this.khachhangXoaBtn.IdleBorderThickness = 1;
            this.khachhangXoaBtn.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(246)))), ((int)(((byte)(78)))), ((int)(((byte)(96)))));
            this.khachhangXoaBtn.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("khachhangXoaBtn.IdleIconLeftImage")));
            this.khachhangXoaBtn.IdleIconRightImage = null;
            this.khachhangXoaBtn.IndicateFocus = false;
            this.khachhangXoaBtn.Location = new System.Drawing.Point(682, 35);
            this.khachhangXoaBtn.Name = "khachhangXoaBtn";
            this.khachhangXoaBtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.khachhangXoaBtn.OnDisabledState.BorderRadius = 10;
            this.khachhangXoaBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.khachhangXoaBtn.OnDisabledState.BorderThickness = 1;
            this.khachhangXoaBtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.khachhangXoaBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.khachhangXoaBtn.OnDisabledState.IconLeftImage = null;
            this.khachhangXoaBtn.OnDisabledState.IconRightImage = null;
            this.khachhangXoaBtn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.khachhangXoaBtn.onHoverState.BorderRadius = 10;
            this.khachhangXoaBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.khachhangXoaBtn.onHoverState.BorderThickness = 1;
            this.khachhangXoaBtn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.khachhangXoaBtn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.khachhangXoaBtn.onHoverState.IconLeftImage = null;
            this.khachhangXoaBtn.onHoverState.IconRightImage = null;
            this.khachhangXoaBtn.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(246)))), ((int)(((byte)(78)))), ((int)(((byte)(96)))));
            this.khachhangXoaBtn.OnIdleState.BorderRadius = 10;
            this.khachhangXoaBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.khachhangXoaBtn.OnIdleState.BorderThickness = 1;
            this.khachhangXoaBtn.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(246)))), ((int)(((byte)(78)))), ((int)(((byte)(96)))));
            this.khachhangXoaBtn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.khachhangXoaBtn.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("khachhangXoaBtn.OnIdleState.IconLeftImage")));
            this.khachhangXoaBtn.OnIdleState.IconRightImage = null;
            this.khachhangXoaBtn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.khachhangXoaBtn.OnPressedState.BorderRadius = 10;
            this.khachhangXoaBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.khachhangXoaBtn.OnPressedState.BorderThickness = 1;
            this.khachhangXoaBtn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.khachhangXoaBtn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.khachhangXoaBtn.OnPressedState.IconLeftImage = null;
            this.khachhangXoaBtn.OnPressedState.IconRightImage = null;
            this.khachhangXoaBtn.Size = new System.Drawing.Size(96, 40);
            this.khachhangXoaBtn.TabIndex = 3;
            this.khachhangXoaBtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.khachhangXoaBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.khachhangXoaBtn.TextMarginLeft = 0;
            this.khachhangXoaBtn.TextPadding = new System.Windows.Forms.Padding(15, 0, 0, 0);
            this.khachhangXoaBtn.UseDefaultRadiusAndThickness = true;
            this.khachhangXoaBtn.Click += new System.EventHandler(this.khachhangXoaBtn_Click);
            // 
            // bunifuPanel2
            // 
            this.bunifuPanel2.BackgroundColor = System.Drawing.Color.White;
            this.bunifuPanel2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel2.BackgroundImage")));
            this.bunifuPanel2.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel2.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuPanel2.BorderRadius = 20;
            this.bunifuPanel2.BorderThickness = 1;
            this.bunifuPanel2.Location = new System.Drawing.Point(1032, 12);
            this.bunifuPanel2.Name = "bunifuPanel2";
            this.bunifuPanel2.ShowBorders = true;
            this.bunifuPanel2.Size = new System.Drawing.Size(209, 65);
            this.bunifuPanel2.TabIndex = 27;
            // 
            // formKhachHang
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(239)))), ((int)(((byte)(243)))), ((int)(((byte)(249)))));
            this.ClientSize = new System.Drawing.Size(1271, 785);
            this.Controls.Add(this.bunifuPanel2);
            this.Controls.Add(this.khachhangPanel);
            this.Controls.Add(this.khachhangSearchBtn);
            this.Controls.Add(this.khachhangSearch);
            this.Controls.Add(this.khachhangTitle);
            this.Name = "formKhachHang";
            this.Text = "formKhachHang";
            this.khachhangPanel.ResumeLayout(false);
            this.khachhangPanel.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.khachhangTable)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 khachhangSearchBtn;
        private Bunifu.UI.WinForms.BunifuTextBox khachhangSearch;
        private Bunifu.UI.WinForms.BunifuLabel khachhangTitle;
        private Bunifu.UI.WinForms.BunifuPanel khachhangPanel;
        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel2;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 khachhangLuuBtn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 khachhangThemBtn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 khachhangXoaBtn;
        private Bunifu.UI.WinForms.BunifuLabel khachhangPanelSub;
        private Bunifu.UI.WinForms.BunifuLabel khachhangPanelTitle;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 xuatKhachHang;
        private Guna.UI2.WinForms.Guna2DataGridView khachhangTable;
    }
}