namespace BTL.GUI
{
    partial class formHoaDon
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(formHoaDon));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle1 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle3 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle4 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle5 = new System.Windows.Forms.DataGridViewCellStyle();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            this.hoadonSearchBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.hoadonSearch = new Bunifu.UI.WinForms.BunifuTextBox();
            this.hoadonTitle = new Bunifu.UI.WinForms.BunifuLabel();
            this.hoadonPanel = new Bunifu.UI.WinForms.BunifuPanel();
            this.hoadonTable = new Guna.UI2.WinForms.Guna2DataGridView();
            this.xuatHoaDon = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.hoadonPanelSub = new Bunifu.UI.WinForms.BunifuLabel();
            this.hoadonPanelTitle = new Bunifu.UI.WinForms.BunifuLabel();
            this.hanghoaLuuBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.hanghoaThemBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.hanghoaXoaBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.bunifuPanel2 = new Bunifu.UI.WinForms.BunifuPanel();
            this.hoadonPanel.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.hoadonTable)).BeginInit();
            this.SuspendLayout();
            // 
            // hoadonSearchBtn
            // 
            this.hoadonSearchBtn.AllowAnimations = true;
            this.hoadonSearchBtn.AllowMouseEffects = true;
            this.hoadonSearchBtn.AllowToggling = false;
            this.hoadonSearchBtn.AnimationSpeed = 200;
            this.hoadonSearchBtn.AutoGenerateColors = false;
            this.hoadonSearchBtn.AutoRoundBorders = false;
            this.hoadonSearchBtn.AutoSizeLeftIcon = true;
            this.hoadonSearchBtn.AutoSizeRightIcon = true;
            this.hoadonSearchBtn.BackColor = System.Drawing.Color.Transparent;
            this.hoadonSearchBtn.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.hoadonSearchBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("hoadonSearchBtn.BackgroundImage")));
            this.hoadonSearchBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.hoadonSearchBtn.ButtonText = "";
            this.hoadonSearchBtn.ButtonTextMarginLeft = 0;
            this.hoadonSearchBtn.ColorContrastOnClick = 45;
            this.hoadonSearchBtn.ColorContrastOnHover = 45;
            this.hoadonSearchBtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.hoadonSearchBtn.CustomizableEdges = borderEdges1;
            this.hoadonSearchBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.hoadonSearchBtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.hoadonSearchBtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.hoadonSearchBtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.hoadonSearchBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.hoadonSearchBtn.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.hoadonSearchBtn.ForeColor = System.Drawing.Color.White;
            this.hoadonSearchBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.hoadonSearchBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.hoadonSearchBtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.hoadonSearchBtn.IconMarginLeft = 11;
            this.hoadonSearchBtn.IconPadding = 10;
            this.hoadonSearchBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.hoadonSearchBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.hoadonSearchBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.hoadonSearchBtn.IconSize = 25;
            this.hoadonSearchBtn.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.hoadonSearchBtn.IdleBorderRadius = 25;
            this.hoadonSearchBtn.IdleBorderThickness = 1;
            this.hoadonSearchBtn.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.hoadonSearchBtn.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("hoadonSearchBtn.IdleIconLeftImage")));
            this.hoadonSearchBtn.IdleIconRightImage = null;
            this.hoadonSearchBtn.IndicateFocus = false;
            this.hoadonSearchBtn.Location = new System.Drawing.Point(644, 23);
            this.hoadonSearchBtn.Name = "hoadonSearchBtn";
            this.hoadonSearchBtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.hoadonSearchBtn.OnDisabledState.BorderRadius = 25;
            this.hoadonSearchBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.hoadonSearchBtn.OnDisabledState.BorderThickness = 1;
            this.hoadonSearchBtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.hoadonSearchBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.hoadonSearchBtn.OnDisabledState.IconLeftImage = null;
            this.hoadonSearchBtn.OnDisabledState.IconRightImage = null;
            this.hoadonSearchBtn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.hoadonSearchBtn.onHoverState.BorderRadius = 25;
            this.hoadonSearchBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.hoadonSearchBtn.onHoverState.BorderThickness = 1;
            this.hoadonSearchBtn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.hoadonSearchBtn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.hoadonSearchBtn.onHoverState.IconLeftImage = null;
            this.hoadonSearchBtn.onHoverState.IconRightImage = null;
            this.hoadonSearchBtn.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.hoadonSearchBtn.OnIdleState.BorderRadius = 25;
            this.hoadonSearchBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.hoadonSearchBtn.OnIdleState.BorderThickness = 1;
            this.hoadonSearchBtn.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.hoadonSearchBtn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.hoadonSearchBtn.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("hoadonSearchBtn.OnIdleState.IconLeftImage")));
            this.hoadonSearchBtn.OnIdleState.IconRightImage = null;
            this.hoadonSearchBtn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.hoadonSearchBtn.OnPressedState.BorderRadius = 25;
            this.hoadonSearchBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.hoadonSearchBtn.OnPressedState.BorderThickness = 1;
            this.hoadonSearchBtn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.hoadonSearchBtn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.hoadonSearchBtn.OnPressedState.IconLeftImage = null;
            this.hoadonSearchBtn.OnPressedState.IconRightImage = null;
            this.hoadonSearchBtn.Size = new System.Drawing.Size(42, 39);
            this.hoadonSearchBtn.TabIndex = 22;
            this.hoadonSearchBtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.hoadonSearchBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.hoadonSearchBtn.TextMarginLeft = 0;
            this.hoadonSearchBtn.TextPadding = new System.Windows.Forms.Padding(0);
            this.hoadonSearchBtn.UseDefaultRadiusAndThickness = true;
            this.hoadonSearchBtn.Click += new System.EventHandler(this.hoadonSearchBtn_Click);
            // 
            // hoadonSearch
            // 
            this.hoadonSearch.AcceptsReturn = false;
            this.hoadonSearch.AcceptsTab = false;
            this.hoadonSearch.AnimationSpeed = 200;
            this.hoadonSearch.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.hoadonSearch.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.hoadonSearch.AutoSizeHeight = true;
            this.hoadonSearch.BackColor = System.Drawing.Color.Transparent;
            this.hoadonSearch.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("hoadonSearch.BackgroundImage")));
            this.hoadonSearch.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.hoadonSearch.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.hoadonSearch.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.hoadonSearch.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(235)))), ((int)(((byte)(235)))), ((int)(((byte)(235)))));
            this.hoadonSearch.BorderRadius = 20;
            this.hoadonSearch.BorderThickness = 1;
            this.hoadonSearch.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.hoadonSearch.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.hoadonSearch.DefaultFont = new System.Drawing.Font("Segoe UI", 10F);
            this.hoadonSearch.DefaultText = "";
            this.hoadonSearch.FillColor = System.Drawing.Color.White;
            this.hoadonSearch.HideSelection = true;
            this.hoadonSearch.IconLeft = ((System.Drawing.Image)(resources.GetObject("hoadonSearch.IconLeft")));
            this.hoadonSearch.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.hoadonSearch.IconPadding = 10;
            this.hoadonSearch.IconRight = null;
            this.hoadonSearch.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.hoadonSearch.Lines = new string[0];
            this.hoadonSearch.Location = new System.Drawing.Point(271, 21);
            this.hoadonSearch.Margin = new System.Windows.Forms.Padding(20, 3, 3, 3);
            this.hoadonSearch.MaxLength = 32767;
            this.hoadonSearch.MinimumSize = new System.Drawing.Size(1, 1);
            this.hoadonSearch.Modified = false;
            this.hoadonSearch.Multiline = false;
            this.hoadonSearch.Name = "hoadonSearch";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.hoadonSearch.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.hoadonSearch.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.hoadonSearch.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(235)))), ((int)(((byte)(235)))), ((int)(((byte)(235)))));
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.hoadonSearch.OnIdleState = stateProperties4;
            this.hoadonSearch.Padding = new System.Windows.Forms.Padding(40, 3, 3, 3);
            this.hoadonSearch.PasswordChar = '\0';
            this.hoadonSearch.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.hoadonSearch.PlaceholderText = "Tìm kiếm";
            this.hoadonSearch.ReadOnly = false;
            this.hoadonSearch.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.hoadonSearch.SelectedText = "";
            this.hoadonSearch.SelectionLength = 0;
            this.hoadonSearch.SelectionStart = 0;
            this.hoadonSearch.ShortcutsEnabled = true;
            this.hoadonSearch.Size = new System.Drawing.Size(367, 41);
            this.hoadonSearch.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.hoadonSearch.TabIndex = 21;
            this.hoadonSearch.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.hoadonSearch.TextMarginBottom = 0;
            this.hoadonSearch.TextMarginLeft = 15;
            this.hoadonSearch.TextMarginTop = 0;
            this.hoadonSearch.TextPlaceholder = "Tìm kiếm";
            this.hoadonSearch.UseSystemPasswordChar = false;
            this.hoadonSearch.WordWrap = true;
            this.hoadonSearch.KeyDown += new System.Windows.Forms.KeyEventHandler(this.hoadonSearch_KeyDown);
            // 
            // hoadonTitle
            // 
            this.hoadonTitle.AllowParentOverrides = false;
            this.hoadonTitle.AutoEllipsis = false;
            this.hoadonTitle.Cursor = System.Windows.Forms.Cursors.Default;
            this.hoadonTitle.CursorType = System.Windows.Forms.Cursors.Default;
            this.hoadonTitle.Font = new System.Drawing.Font("Segoe UI Semibold", 13F, System.Drawing.FontStyle.Bold);
            this.hoadonTitle.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(79)))), ((int)(((byte)(79)))), ((int)(((byte)(79)))));
            this.hoadonTitle.Location = new System.Drawing.Point(134, 23);
            this.hoadonTitle.Name = "hoadonTitle";
            this.hoadonTitle.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.hoadonTitle.Size = new System.Drawing.Size(88, 30);
            this.hoadonTitle.TabIndex = 20;
            this.hoadonTitle.Text = "Hóa Đơn";
            this.hoadonTitle.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.hoadonTitle.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // hoadonPanel
            // 
            this.hoadonPanel.BackgroundColor = System.Drawing.Color.White;
            this.hoadonPanel.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("hoadonPanel.BackgroundImage")));
            this.hoadonPanel.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.hoadonPanel.BorderColor = System.Drawing.Color.Gainsboro;
            this.hoadonPanel.BorderRadius = 25;
            this.hoadonPanel.BorderThickness = 1;
            this.hoadonPanel.Controls.Add(this.hoadonTable);
            this.hoadonPanel.Controls.Add(this.xuatHoaDon);
            this.hoadonPanel.Controls.Add(this.hoadonPanelSub);
            this.hoadonPanel.Controls.Add(this.hoadonPanelTitle);
            this.hoadonPanel.Controls.Add(this.hanghoaLuuBtn);
            this.hoadonPanel.Controls.Add(this.hanghoaThemBtn);
            this.hoadonPanel.Controls.Add(this.hanghoaXoaBtn);
            this.hoadonPanel.Location = new System.Drawing.Point(134, 127);
            this.hoadonPanel.Name = "hoadonPanel";
            this.hoadonPanel.ShowBorders = true;
            this.hoadonPanel.Size = new System.Drawing.Size(1107, 630);
            this.hoadonPanel.TabIndex = 25;
            // 
            // hoadonTable
            // 
            this.hoadonTable.AllowUserToAddRows = false;
            this.hoadonTable.AllowUserToDeleteRows = false;
            dataGridViewCellStyle1.BackColor = System.Drawing.Color.White;
            this.hoadonTable.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle1;
            this.hoadonTable.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.hoadonTable.BackgroundColor = System.Drawing.Color.White;
            this.hoadonTable.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.hoadonTable.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.hoadonTable.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle2.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle2.BackColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.Font = new System.Drawing.Font("Segoe UI Semibold", 10.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            dataGridViewCellStyle2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(33)))), ((int)(((byte)(35)))), ((int)(((byte)(74)))));
            dataGridViewCellStyle2.Padding = new System.Windows.Forms.Padding(15, 0, 15, 0);
            dataGridViewCellStyle2.SelectionBackColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.SelectionForeColor = System.Drawing.SystemColors.HighlightText;
            dataGridViewCellStyle2.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.hoadonTable.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2;
            this.hoadonTable.ColumnHeadersHeight = 55;
            this.hoadonTable.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.DisableResizing;
            dataGridViewCellStyle3.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle3.BackColor = System.Drawing.Color.White;
            dataGridViewCellStyle3.Font = new System.Drawing.Font("Segoe UI Semibold", 9F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle3.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(71)))), ((int)(((byte)(69)))), ((int)(((byte)(94)))));
            dataGridViewCellStyle3.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(231)))), ((int)(((byte)(229)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle3.SelectionForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(71)))), ((int)(((byte)(69)))), ((int)(((byte)(94)))));
            dataGridViewCellStyle3.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.hoadonTable.DefaultCellStyle = dataGridViewCellStyle3;
            this.hoadonTable.EnableHeadersVisualStyles = false;
            this.hoadonTable.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(231)))), ((int)(((byte)(229)))), ((int)(((byte)(255)))));
            this.hoadonTable.Location = new System.Drawing.Point(42, 122);
            this.hoadonTable.Name = "hoadonTable";
            this.hoadonTable.ReadOnly = true;
            this.hoadonTable.RowHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.Single;
            dataGridViewCellStyle4.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleCenter;
            dataGridViewCellStyle4.BackColor = System.Drawing.SystemColors.Control;
            dataGridViewCellStyle4.Font = new System.Drawing.Font("Microsoft Sans Serif", 7.8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            dataGridViewCellStyle4.ForeColor = System.Drawing.SystemColors.WindowText;
            dataGridViewCellStyle4.Padding = new System.Windows.Forms.Padding(0, 0, 0, 10);
            dataGridViewCellStyle4.SelectionBackColor = System.Drawing.Color.White;
            dataGridViewCellStyle4.SelectionForeColor = System.Drawing.SystemColors.HighlightText;
            dataGridViewCellStyle4.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.hoadonTable.RowHeadersDefaultCellStyle = dataGridViewCellStyle4;
            this.hoadonTable.RowHeadersVisible = false;
            this.hoadonTable.RowHeadersWidth = 51;
            this.hoadonTable.RowHeadersWidthSizeMode = System.Windows.Forms.DataGridViewRowHeadersWidthSizeMode.DisableResizing;
            dataGridViewCellStyle5.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle5.Padding = new System.Windows.Forms.Padding(15, 0, 0, 5);
            dataGridViewCellStyle5.SelectionBackColor = System.Drawing.Color.AliceBlue;
            this.hoadonTable.RowsDefaultCellStyle = dataGridViewCellStyle5;
            this.hoadonTable.RowTemplate.Height = 55;
            this.hoadonTable.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.hoadonTable.Size = new System.Drawing.Size(1029, 470);
            this.hoadonTable.TabIndex = 46;
            this.hoadonTable.ThemeStyle.AlternatingRowsStyle.BackColor = System.Drawing.Color.White;
            this.hoadonTable.ThemeStyle.AlternatingRowsStyle.Font = null;
            this.hoadonTable.ThemeStyle.AlternatingRowsStyle.ForeColor = System.Drawing.Color.Empty;
            this.hoadonTable.ThemeStyle.AlternatingRowsStyle.SelectionBackColor = System.Drawing.Color.Empty;
            this.hoadonTable.ThemeStyle.AlternatingRowsStyle.SelectionForeColor = System.Drawing.Color.Empty;
            this.hoadonTable.ThemeStyle.BackColor = System.Drawing.Color.White;
            this.hoadonTable.ThemeStyle.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(231)))), ((int)(((byte)(229)))), ((int)(((byte)(255)))));
            this.hoadonTable.ThemeStyle.HeaderStyle.BackColor = System.Drawing.Color.White;
            this.hoadonTable.ThemeStyle.HeaderStyle.BorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            this.hoadonTable.ThemeStyle.HeaderStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 10.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            this.hoadonTable.ThemeStyle.HeaderStyle.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(33)))), ((int)(((byte)(35)))), ((int)(((byte)(74)))));
            this.hoadonTable.ThemeStyle.HeaderStyle.HeaightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.DisableResizing;
            this.hoadonTable.ThemeStyle.HeaderStyle.Height = 55;
            this.hoadonTable.ThemeStyle.ReadOnly = true;
            this.hoadonTable.ThemeStyle.RowsStyle.BackColor = System.Drawing.Color.White;
            this.hoadonTable.ThemeStyle.RowsStyle.BorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.hoadonTable.ThemeStyle.RowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9F, System.Drawing.FontStyle.Bold);
            this.hoadonTable.ThemeStyle.RowsStyle.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(71)))), ((int)(((byte)(69)))), ((int)(((byte)(94)))));
            this.hoadonTable.ThemeStyle.RowsStyle.Height = 55;
            this.hoadonTable.ThemeStyle.RowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(231)))), ((int)(((byte)(229)))), ((int)(((byte)(255)))));
            this.hoadonTable.ThemeStyle.RowsStyle.SelectionForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(71)))), ((int)(((byte)(69)))), ((int)(((byte)(94)))));
            // 
            // xuatHoaDon
            // 
            this.xuatHoaDon.AllowAnimations = true;
            this.xuatHoaDon.AllowMouseEffects = true;
            this.xuatHoaDon.AllowToggling = false;
            this.xuatHoaDon.AnimationSpeed = 200;
            this.xuatHoaDon.AutoGenerateColors = false;
            this.xuatHoaDon.AutoRoundBorders = false;
            this.xuatHoaDon.AutoSizeLeftIcon = true;
            this.xuatHoaDon.AutoSizeRightIcon = true;
            this.xuatHoaDon.BackColor = System.Drawing.Color.Transparent;
            this.xuatHoaDon.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(127)))), ((int)(((byte)(127)))), ((int)(((byte)(213)))));
            this.xuatHoaDon.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("xuatHoaDon.BackgroundImage")));
            this.xuatHoaDon.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.xuatHoaDon.ButtonText = "Xuất Hóa Đơn";
            this.xuatHoaDon.ButtonTextMarginLeft = 0;
            this.xuatHoaDon.ColorContrastOnClick = 45;
            this.xuatHoaDon.ColorContrastOnHover = 45;
            this.xuatHoaDon.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.xuatHoaDon.CustomizableEdges = borderEdges2;
            this.xuatHoaDon.DialogResult = System.Windows.Forms.DialogResult.None;
            this.xuatHoaDon.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.xuatHoaDon.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.xuatHoaDon.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.xuatHoaDon.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.xuatHoaDon.Font = new System.Drawing.Font("Segoe UI Semibold", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            this.xuatHoaDon.ForeColor = System.Drawing.Color.White;
            this.xuatHoaDon.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.xuatHoaDon.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.xuatHoaDon.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.xuatHoaDon.IconMarginLeft = 11;
            this.xuatHoaDon.IconPadding = 10;
            this.xuatHoaDon.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.xuatHoaDon.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.xuatHoaDon.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.xuatHoaDon.IconSize = 25;
            this.xuatHoaDon.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(127)))), ((int)(((byte)(127)))), ((int)(((byte)(213)))));
            this.xuatHoaDon.IdleBorderRadius = 10;
            this.xuatHoaDon.IdleBorderThickness = 1;
            this.xuatHoaDon.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(127)))), ((int)(((byte)(127)))), ((int)(((byte)(213)))));
            this.xuatHoaDon.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("xuatHoaDon.IdleIconLeftImage")));
            this.xuatHoaDon.IdleIconRightImage = null;
            this.xuatHoaDon.IndicateFocus = false;
            this.xuatHoaDon.Location = new System.Drawing.Point(911, 35);
            this.xuatHoaDon.Name = "xuatHoaDon";
            this.xuatHoaDon.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.xuatHoaDon.OnDisabledState.BorderRadius = 10;
            this.xuatHoaDon.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.xuatHoaDon.OnDisabledState.BorderThickness = 1;
            this.xuatHoaDon.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.xuatHoaDon.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.xuatHoaDon.OnDisabledState.IconLeftImage = null;
            this.xuatHoaDon.OnDisabledState.IconRightImage = null;
            this.xuatHoaDon.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.xuatHoaDon.onHoverState.BorderRadius = 10;
            this.xuatHoaDon.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.xuatHoaDon.onHoverState.BorderThickness = 1;
            this.xuatHoaDon.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.xuatHoaDon.onHoverState.ForeColor = System.Drawing.Color.White;
            this.xuatHoaDon.onHoverState.IconLeftImage = null;
            this.xuatHoaDon.onHoverState.IconRightImage = null;
            this.xuatHoaDon.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(127)))), ((int)(((byte)(127)))), ((int)(((byte)(213)))));
            this.xuatHoaDon.OnIdleState.BorderRadius = 10;
            this.xuatHoaDon.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.xuatHoaDon.OnIdleState.BorderThickness = 1;
            this.xuatHoaDon.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(127)))), ((int)(((byte)(127)))), ((int)(((byte)(213)))));
            this.xuatHoaDon.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.xuatHoaDon.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("xuatHoaDon.OnIdleState.IconLeftImage")));
            this.xuatHoaDon.OnIdleState.IconRightImage = null;
            this.xuatHoaDon.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.xuatHoaDon.OnPressedState.BorderRadius = 10;
            this.xuatHoaDon.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.xuatHoaDon.OnPressedState.BorderThickness = 1;
            this.xuatHoaDon.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.xuatHoaDon.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.xuatHoaDon.OnPressedState.IconLeftImage = null;
            this.xuatHoaDon.OnPressedState.IconRightImage = null;
            this.xuatHoaDon.Size = new System.Drawing.Size(161, 40);
            this.xuatHoaDon.TabIndex = 40;
            this.xuatHoaDon.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.xuatHoaDon.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.xuatHoaDon.TextMarginLeft = 0;
            this.xuatHoaDon.TextPadding = new System.Windows.Forms.Padding(15, 0, 0, 0);
            this.xuatHoaDon.UseDefaultRadiusAndThickness = true;
            this.xuatHoaDon.Click += new System.EventHandler(this.xuatHoaDon_Click);
            // 
            // hoadonPanelSub
            // 
            this.hoadonPanelSub.AllowParentOverrides = false;
            this.hoadonPanelSub.AutoEllipsis = false;
            this.hoadonPanelSub.CursorType = null;
            this.hoadonPanelSub.Font = new System.Drawing.Font("Segoe UI", 7F);
            this.hoadonPanelSub.ForeColor = System.Drawing.SystemColors.ActiveBorder;
            this.hoadonPanelSub.Location = new System.Drawing.Point(43, 60);
            this.hoadonPanelSub.Name = "hoadonPanelSub";
            this.hoadonPanelSub.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.hoadonPanelSub.Size = new System.Drawing.Size(128, 15);
            this.hoadonPanelSub.TabIndex = 38;
            this.hoadonPanelSub.Text = "Tìm thấy một số kết quả";
            this.hoadonPanelSub.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.hoadonPanelSub.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // hoadonPanelTitle
            // 
            this.hoadonPanelTitle.AllowParentOverrides = false;
            this.hoadonPanelTitle.AutoEllipsis = false;
            this.hoadonPanelTitle.CursorType = null;
            this.hoadonPanelTitle.Font = new System.Drawing.Font("Segoe UI Semibold", 13F, System.Drawing.FontStyle.Bold);
            this.hoadonPanelTitle.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(79)))), ((int)(((byte)(79)))), ((int)(((byte)(79)))));
            this.hoadonPanelTitle.Location = new System.Drawing.Point(43, 24);
            this.hoadonPanelTitle.Name = "hoadonPanelTitle";
            this.hoadonPanelTitle.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.hoadonPanelTitle.Size = new System.Drawing.Size(195, 30);
            this.hoadonPanelTitle.TabIndex = 39;
            this.hoadonPanelTitle.Text = "Thông Tin Hóa Đơn";
            this.hoadonPanelTitle.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.hoadonPanelTitle.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // hanghoaLuuBtn
            // 
            this.hanghoaLuuBtn.AllowAnimations = true;
            this.hanghoaLuuBtn.AllowMouseEffects = true;
            this.hanghoaLuuBtn.AllowToggling = false;
            this.hanghoaLuuBtn.AnimationSpeed = 200;
            this.hanghoaLuuBtn.AutoGenerateColors = false;
            this.hanghoaLuuBtn.AutoRoundBorders = false;
            this.hanghoaLuuBtn.AutoSizeLeftIcon = true;
            this.hanghoaLuuBtn.AutoSizeRightIcon = true;
            this.hanghoaLuuBtn.BackColor = System.Drawing.Color.Transparent;
            this.hanghoaLuuBtn.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.hanghoaLuuBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("hanghoaLuuBtn.BackgroundImage")));
            this.hanghoaLuuBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.hanghoaLuuBtn.ButtonText = "Sửa";
            this.hanghoaLuuBtn.ButtonTextMarginLeft = 0;
            this.hanghoaLuuBtn.ColorContrastOnClick = 45;
            this.hanghoaLuuBtn.ColorContrastOnHover = 45;
            this.hanghoaLuuBtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.hanghoaLuuBtn.CustomizableEdges = borderEdges3;
            this.hanghoaLuuBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.hanghoaLuuBtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.hanghoaLuuBtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.hanghoaLuuBtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.hanghoaLuuBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.hanghoaLuuBtn.Font = new System.Drawing.Font("Segoe UI Semibold", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            this.hanghoaLuuBtn.ForeColor = System.Drawing.Color.White;
            this.hanghoaLuuBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.hanghoaLuuBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.hanghoaLuuBtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.hanghoaLuuBtn.IconMarginLeft = 11;
            this.hanghoaLuuBtn.IconPadding = 10;
            this.hanghoaLuuBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.hanghoaLuuBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.hanghoaLuuBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.hanghoaLuuBtn.IconSize = 25;
            this.hanghoaLuuBtn.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.hanghoaLuuBtn.IdleBorderRadius = 10;
            this.hanghoaLuuBtn.IdleBorderThickness = 1;
            this.hanghoaLuuBtn.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.hanghoaLuuBtn.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("hanghoaLuuBtn.IdleIconLeftImage")));
            this.hanghoaLuuBtn.IdleIconRightImage = null;
            this.hanghoaLuuBtn.IndicateFocus = false;
            this.hanghoaLuuBtn.Location = new System.Drawing.Point(797, 35);
            this.hanghoaLuuBtn.Name = "hanghoaLuuBtn";
            this.hanghoaLuuBtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.hanghoaLuuBtn.OnDisabledState.BorderRadius = 10;
            this.hanghoaLuuBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.hanghoaLuuBtn.OnDisabledState.BorderThickness = 1;
            this.hanghoaLuuBtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.hanghoaLuuBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.hanghoaLuuBtn.OnDisabledState.IconLeftImage = null;
            this.hanghoaLuuBtn.OnDisabledState.IconRightImage = null;
            this.hanghoaLuuBtn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.hanghoaLuuBtn.onHoverState.BorderRadius = 10;
            this.hanghoaLuuBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.hanghoaLuuBtn.onHoverState.BorderThickness = 1;
            this.hanghoaLuuBtn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.hanghoaLuuBtn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.hanghoaLuuBtn.onHoverState.IconLeftImage = null;
            this.hanghoaLuuBtn.onHoverState.IconRightImage = null;
            this.hanghoaLuuBtn.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.hanghoaLuuBtn.OnIdleState.BorderRadius = 10;
            this.hanghoaLuuBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.hanghoaLuuBtn.OnIdleState.BorderThickness = 1;
            this.hanghoaLuuBtn.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.hanghoaLuuBtn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.hanghoaLuuBtn.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("hanghoaLuuBtn.OnIdleState.IconLeftImage")));
            this.hanghoaLuuBtn.OnIdleState.IconRightImage = null;
            this.hanghoaLuuBtn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.hanghoaLuuBtn.OnPressedState.BorderRadius = 10;
            this.hanghoaLuuBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.hanghoaLuuBtn.OnPressedState.BorderThickness = 1;
            this.hanghoaLuuBtn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.hanghoaLuuBtn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.hanghoaLuuBtn.OnPressedState.IconLeftImage = null;
            this.hanghoaLuuBtn.OnPressedState.IconRightImage = null;
            this.hanghoaLuuBtn.Size = new System.Drawing.Size(96, 40);
            this.hanghoaLuuBtn.TabIndex = 5;
            this.hanghoaLuuBtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.hanghoaLuuBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.hanghoaLuuBtn.TextMarginLeft = 0;
            this.hanghoaLuuBtn.TextPadding = new System.Windows.Forms.Padding(15, 0, 0, 0);
            this.hanghoaLuuBtn.UseDefaultRadiusAndThickness = true;
            this.hanghoaLuuBtn.Click += new System.EventHandler(this.hanghoaLuuBtn_Click);
            // 
            // hanghoaThemBtn
            // 
            this.hanghoaThemBtn.AllowAnimations = true;
            this.hanghoaThemBtn.AllowMouseEffects = true;
            this.hanghoaThemBtn.AllowToggling = false;
            this.hanghoaThemBtn.AnimationSpeed = 200;
            this.hanghoaThemBtn.AutoGenerateColors = false;
            this.hanghoaThemBtn.AutoRoundBorders = false;
            this.hanghoaThemBtn.AutoSizeLeftIcon = true;
            this.hanghoaThemBtn.AutoSizeRightIcon = true;
            this.hanghoaThemBtn.BackColor = System.Drawing.Color.Transparent;
            this.hanghoaThemBtn.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(95)))), ((int)(((byte)(210)))), ((int)(((byte)(143)))));
            this.hanghoaThemBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("hanghoaThemBtn.BackgroundImage")));
            this.hanghoaThemBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.hanghoaThemBtn.ButtonText = "Thêm";
            this.hanghoaThemBtn.ButtonTextMarginLeft = 0;
            this.hanghoaThemBtn.ColorContrastOnClick = 45;
            this.hanghoaThemBtn.ColorContrastOnHover = 45;
            this.hanghoaThemBtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.hanghoaThemBtn.CustomizableEdges = borderEdges4;
            this.hanghoaThemBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.hanghoaThemBtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.hanghoaThemBtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.hanghoaThemBtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.hanghoaThemBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.hanghoaThemBtn.Font = new System.Drawing.Font("Segoe UI Semibold", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            this.hanghoaThemBtn.ForeColor = System.Drawing.Color.White;
            this.hanghoaThemBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.hanghoaThemBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.hanghoaThemBtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.hanghoaThemBtn.IconMarginLeft = 11;
            this.hanghoaThemBtn.IconPadding = 10;
            this.hanghoaThemBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.hanghoaThemBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.hanghoaThemBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.hanghoaThemBtn.IconSize = 25;
            this.hanghoaThemBtn.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(95)))), ((int)(((byte)(210)))), ((int)(((byte)(143)))));
            this.hanghoaThemBtn.IdleBorderRadius = 10;
            this.hanghoaThemBtn.IdleBorderThickness = 1;
            this.hanghoaThemBtn.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(95)))), ((int)(((byte)(210)))), ((int)(((byte)(143)))));
            this.hanghoaThemBtn.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("hanghoaThemBtn.IdleIconLeftImage")));
            this.hanghoaThemBtn.IdleIconRightImage = null;
            this.hanghoaThemBtn.IndicateFocus = false;
            this.hanghoaThemBtn.Location = new System.Drawing.Point(563, 35);
            this.hanghoaThemBtn.Name = "hanghoaThemBtn";
            this.hanghoaThemBtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.hanghoaThemBtn.OnDisabledState.BorderRadius = 10;
            this.hanghoaThemBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.hanghoaThemBtn.OnDisabledState.BorderThickness = 1;
            this.hanghoaThemBtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.hanghoaThemBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.hanghoaThemBtn.OnDisabledState.IconLeftImage = null;
            this.hanghoaThemBtn.OnDisabledState.IconRightImage = null;
            this.hanghoaThemBtn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.hanghoaThemBtn.onHoverState.BorderRadius = 10;
            this.hanghoaThemBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.hanghoaThemBtn.onHoverState.BorderThickness = 1;
            this.hanghoaThemBtn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.hanghoaThemBtn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.hanghoaThemBtn.onHoverState.IconLeftImage = null;
            this.hanghoaThemBtn.onHoverState.IconRightImage = null;
            this.hanghoaThemBtn.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(95)))), ((int)(((byte)(210)))), ((int)(((byte)(143)))));
            this.hanghoaThemBtn.OnIdleState.BorderRadius = 10;
            this.hanghoaThemBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.hanghoaThemBtn.OnIdleState.BorderThickness = 1;
            this.hanghoaThemBtn.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(95)))), ((int)(((byte)(210)))), ((int)(((byte)(143)))));
            this.hanghoaThemBtn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.hanghoaThemBtn.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("hanghoaThemBtn.OnIdleState.IconLeftImage")));
            this.hanghoaThemBtn.OnIdleState.IconRightImage = null;
            this.hanghoaThemBtn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.hanghoaThemBtn.OnPressedState.BorderRadius = 10;
            this.hanghoaThemBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.hanghoaThemBtn.OnPressedState.BorderThickness = 1;
            this.hanghoaThemBtn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.hanghoaThemBtn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.hanghoaThemBtn.OnPressedState.IconLeftImage = null;
            this.hanghoaThemBtn.OnPressedState.IconRightImage = null;
            this.hanghoaThemBtn.Size = new System.Drawing.Size(96, 40);
            this.hanghoaThemBtn.TabIndex = 4;
            this.hanghoaThemBtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.hanghoaThemBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.hanghoaThemBtn.TextMarginLeft = 0;
            this.hanghoaThemBtn.TextPadding = new System.Windows.Forms.Padding(15, 0, 0, 0);
            this.hanghoaThemBtn.UseDefaultRadiusAndThickness = true;
            this.hanghoaThemBtn.Click += new System.EventHandler(this.hanghoaThemBtn_Click);
            // 
            // hanghoaXoaBtn
            // 
            this.hanghoaXoaBtn.AllowAnimations = true;
            this.hanghoaXoaBtn.AllowMouseEffects = true;
            this.hanghoaXoaBtn.AllowToggling = false;
            this.hanghoaXoaBtn.AnimationSpeed = 200;
            this.hanghoaXoaBtn.AutoGenerateColors = false;
            this.hanghoaXoaBtn.AutoRoundBorders = false;
            this.hanghoaXoaBtn.AutoSizeLeftIcon = true;
            this.hanghoaXoaBtn.AutoSizeRightIcon = true;
            this.hanghoaXoaBtn.BackColor = System.Drawing.Color.Transparent;
            this.hanghoaXoaBtn.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(246)))), ((int)(((byte)(78)))), ((int)(((byte)(96)))));
            this.hanghoaXoaBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("hanghoaXoaBtn.BackgroundImage")));
            this.hanghoaXoaBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.hanghoaXoaBtn.ButtonText = "Xóa";
            this.hanghoaXoaBtn.ButtonTextMarginLeft = 0;
            this.hanghoaXoaBtn.ColorContrastOnClick = 45;
            this.hanghoaXoaBtn.ColorContrastOnHover = 45;
            this.hanghoaXoaBtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.hanghoaXoaBtn.CustomizableEdges = borderEdges5;
            this.hanghoaXoaBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.hanghoaXoaBtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.hanghoaXoaBtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.hanghoaXoaBtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.hanghoaXoaBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.hanghoaXoaBtn.Font = new System.Drawing.Font("Segoe UI Semibold", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            this.hanghoaXoaBtn.ForeColor = System.Drawing.Color.White;
            this.hanghoaXoaBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.hanghoaXoaBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.hanghoaXoaBtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.hanghoaXoaBtn.IconMarginLeft = 11;
            this.hanghoaXoaBtn.IconPadding = 10;
            this.hanghoaXoaBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.hanghoaXoaBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.hanghoaXoaBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.hanghoaXoaBtn.IconSize = 25;
            this.hanghoaXoaBtn.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(246)))), ((int)(((byte)(78)))), ((int)(((byte)(96)))));
            this.hanghoaXoaBtn.IdleBorderRadius = 10;
            this.hanghoaXoaBtn.IdleBorderThickness = 1;
            this.hanghoaXoaBtn.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(246)))), ((int)(((byte)(78)))), ((int)(((byte)(96)))));
            this.hanghoaXoaBtn.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("hanghoaXoaBtn.IdleIconLeftImage")));
            this.hanghoaXoaBtn.IdleIconRightImage = null;
            this.hanghoaXoaBtn.IndicateFocus = false;
            this.hanghoaXoaBtn.Location = new System.Drawing.Point(681, 35);
            this.hanghoaXoaBtn.Name = "hanghoaXoaBtn";
            this.hanghoaXoaBtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.hanghoaXoaBtn.OnDisabledState.BorderRadius = 10;
            this.hanghoaXoaBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.hanghoaXoaBtn.OnDisabledState.BorderThickness = 1;
            this.hanghoaXoaBtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.hanghoaXoaBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.hanghoaXoaBtn.OnDisabledState.IconLeftImage = null;
            this.hanghoaXoaBtn.OnDisabledState.IconRightImage = null;
            this.hanghoaXoaBtn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.hanghoaXoaBtn.onHoverState.BorderRadius = 10;
            this.hanghoaXoaBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.hanghoaXoaBtn.onHoverState.BorderThickness = 1;
            this.hanghoaXoaBtn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.hanghoaXoaBtn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.hanghoaXoaBtn.onHoverState.IconLeftImage = null;
            this.hanghoaXoaBtn.onHoverState.IconRightImage = null;
            this.hanghoaXoaBtn.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(246)))), ((int)(((byte)(78)))), ((int)(((byte)(96)))));
            this.hanghoaXoaBtn.OnIdleState.BorderRadius = 10;
            this.hanghoaXoaBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.hanghoaXoaBtn.OnIdleState.BorderThickness = 1;
            this.hanghoaXoaBtn.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(246)))), ((int)(((byte)(78)))), ((int)(((byte)(96)))));
            this.hanghoaXoaBtn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.hanghoaXoaBtn.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("hanghoaXoaBtn.OnIdleState.IconLeftImage")));
            this.hanghoaXoaBtn.OnIdleState.IconRightImage = null;
            this.hanghoaXoaBtn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.hanghoaXoaBtn.OnPressedState.BorderRadius = 10;
            this.hanghoaXoaBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.hanghoaXoaBtn.OnPressedState.BorderThickness = 1;
            this.hanghoaXoaBtn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.hanghoaXoaBtn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.hanghoaXoaBtn.OnPressedState.IconLeftImage = null;
            this.hanghoaXoaBtn.OnPressedState.IconRightImage = null;
            this.hanghoaXoaBtn.Size = new System.Drawing.Size(96, 40);
            this.hanghoaXoaBtn.TabIndex = 3;
            this.hanghoaXoaBtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.hanghoaXoaBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.hanghoaXoaBtn.TextMarginLeft = 0;
            this.hanghoaXoaBtn.TextPadding = new System.Windows.Forms.Padding(15, 0, 0, 0);
            this.hanghoaXoaBtn.UseDefaultRadiusAndThickness = true;
            this.hanghoaXoaBtn.Click += new System.EventHandler(this.hanghoaXoaBtn_Click);
            // 
            // bunifuPanel2
            // 
            this.bunifuPanel2.BackgroundColor = System.Drawing.Color.White;
            this.bunifuPanel2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel2.BackgroundImage")));
            this.bunifuPanel2.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel2.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuPanel2.BorderRadius = 20;
            this.bunifuPanel2.BorderThickness = 1;
            this.bunifuPanel2.Location = new System.Drawing.Point(1032, 12);
            this.bunifuPanel2.Name = "bunifuPanel2";
            this.bunifuPanel2.ShowBorders = true;
            this.bunifuPanel2.Size = new System.Drawing.Size(209, 65);
            this.bunifuPanel2.TabIndex = 28;
            // 
            // formHoaDon
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(239)))), ((int)(((byte)(243)))), ((int)(((byte)(249)))));
            this.ClientSize = new System.Drawing.Size(1271, 785);
            this.Controls.Add(this.bunifuPanel2);
            this.Controls.Add(this.hoadonPanel);
            this.Controls.Add(this.hoadonSearchBtn);
            this.Controls.Add(this.hoadonSearch);
            this.Controls.Add(this.hoadonTitle);
            this.Name = "formHoaDon";
            this.Text = "formHoaDon";
            this.hoadonPanel.ResumeLayout(false);
            this.hoadonPanel.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.hoadonTable)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 hoadonSearchBtn;
        private Bunifu.UI.WinForms.BunifuTextBox hoadonSearch;
        private Bunifu.UI.WinForms.BunifuLabel hoadonTitle;
        private Bunifu.UI.WinForms.BunifuPanel hoadonPanel;
        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel2;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 hanghoaLuuBtn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 hanghoaThemBtn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 hanghoaXoaBtn;
        private Bunifu.UI.WinForms.BunifuLabel hoadonPanelSub;
        private Bunifu.UI.WinForms.BunifuLabel hoadonPanelTitle;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 xuatHoaDon;
        private Guna.UI2.WinForms.Guna2DataGridView hoadonTable;
    }
}