namespace BTL.GUI
{
    partial class MainForm
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(MainForm));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuIconButton.BorderEdges borderEdges8 = new Bunifu.UI.WinForms.BunifuButton.BunifuIconButton.BorderEdges();
            this.bunifuShadowPanel1 = new Bunifu.UI.WinForms.BunifuShadowPanel();
            this.logOut = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.indicatorLine = new System.Windows.Forms.PictureBox();
            this.lienheBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.trangchuBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.hanghoaBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.hoadonBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.nhanvienBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.khachhangBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.adminJob = new Bunifu.UI.WinForms.BunifuLabel();
            this.adminAvt = new Bunifu.UI.WinForms.BunifuButton.BunifuIconButton();
            this.bunifuShadowPanel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.indicatorLine)).BeginInit();
            this.SuspendLayout();
            // 
            // bunifuShadowPanel1
            // 
            this.bunifuShadowPanel1.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left)));
            this.bunifuShadowPanel1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuShadowPanel1.BorderColor = System.Drawing.Color.White;
            this.bunifuShadowPanel1.BorderRadius = 1;
            this.bunifuShadowPanel1.BorderThickness = 1;
            this.bunifuShadowPanel1.Controls.Add(this.logOut);
            this.bunifuShadowPanel1.Controls.Add(this.indicatorLine);
            this.bunifuShadowPanel1.Controls.Add(this.lienheBtn);
            this.bunifuShadowPanel1.Controls.Add(this.trangchuBtn);
            this.bunifuShadowPanel1.Controls.Add(this.hanghoaBtn);
            this.bunifuShadowPanel1.Controls.Add(this.hoadonBtn);
            this.bunifuShadowPanel1.Controls.Add(this.nhanvienBtn);
            this.bunifuShadowPanel1.Controls.Add(this.khachhangBtn);
            this.bunifuShadowPanel1.FillStyle = Bunifu.UI.WinForms.BunifuShadowPanel.FillStyles.Solid;
            this.bunifuShadowPanel1.GradientMode = Bunifu.UI.WinForms.BunifuShadowPanel.GradientModes.Vertical;
            this.bunifuShadowPanel1.Location = new System.Drawing.Point(-7, -40);
            this.bunifuShadowPanel1.Name = "bunifuShadowPanel1";
            this.bunifuShadowPanel1.PanelColor = System.Drawing.Color.White;
            this.bunifuShadowPanel1.PanelColor2 = System.Drawing.Color.White;
            this.bunifuShadowPanel1.ShadowColor = System.Drawing.Color.White;
            this.bunifuShadowPanel1.ShadowDept = 2;
            this.bunifuShadowPanel1.ShadowDepth = 2;
            this.bunifuShadowPanel1.ShadowStyle = Bunifu.UI.WinForms.BunifuShadowPanel.ShadowStyles.Dropped;
            this.bunifuShadowPanel1.ShadowTopLeftVisible = false;
            this.bunifuShadowPanel1.Size = new System.Drawing.Size(116, 881);
            this.bunifuShadowPanel1.Style = Bunifu.UI.WinForms.BunifuShadowPanel.BevelStyles.Flat;
            this.bunifuShadowPanel1.TabIndex = 10;
            // 
            // logOut
            // 
            this.logOut.AllowAnimations = true;
            this.logOut.AllowMouseEffects = true;
            this.logOut.AllowToggling = false;
            this.logOut.AnimationSpeed = 300;
            this.logOut.AutoGenerateColors = false;
            this.logOut.AutoRoundBorders = false;
            this.logOut.AutoSizeLeftIcon = true;
            this.logOut.AutoSizeRightIcon = true;
            this.logOut.BackColor = System.Drawing.Color.Transparent;
            this.logOut.BackColor1 = System.Drawing.Color.White;
            this.logOut.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("logOut.BackgroundImage")));
            this.logOut.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.logOut.ButtonText = "";
            this.logOut.ButtonTextMarginLeft = 0;
            this.logOut.ColorContrastOnClick = 45;
            this.logOut.ColorContrastOnHover = 45;
            this.logOut.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.logOut.CustomizableEdges = borderEdges1;
            this.logOut.DialogResult = System.Windows.Forms.DialogResult.None;
            this.logOut.DisabledBorderColor = System.Drawing.Color.Empty;
            this.logOut.DisabledFillColor = System.Drawing.Color.White;
            this.logOut.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.logOut.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.logOut.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.logOut.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(223)))), ((int)(((byte)(230)))), ((int)(((byte)(241)))));
            this.logOut.IconLeftAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.logOut.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.logOut.IconLeftPadding = new System.Windows.Forms.Padding(3);
            this.logOut.IconMarginLeft = 11;
            this.logOut.IconPadding = 10;
            this.logOut.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.logOut.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.logOut.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.logOut.IconSize = 25;
            this.logOut.IdleBorderColor = System.Drawing.Color.White;
            this.logOut.IdleBorderRadius = 1;
            this.logOut.IdleBorderThickness = 1;
            this.logOut.IdleFillColor = System.Drawing.Color.White;
            this.logOut.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("logOut.IdleIconLeftImage")));
            this.logOut.IdleIconRightImage = null;
            this.logOut.ImeMode = System.Windows.Forms.ImeMode.NoControl;
            this.logOut.IndicateFocus = false;
            this.logOut.Location = new System.Drawing.Point(4, 706);
            this.logOut.Name = "logOut";
            this.logOut.OnDisabledState.BorderColor = System.Drawing.Color.Empty;
            this.logOut.OnDisabledState.BorderRadius = 1;
            this.logOut.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.logOut.OnDisabledState.BorderThickness = 1;
            this.logOut.OnDisabledState.FillColor = System.Drawing.Color.White;
            this.logOut.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.logOut.OnDisabledState.IconLeftImage = null;
            this.logOut.OnDisabledState.IconRightImage = null;
            this.logOut.onHoverState.BorderColor = System.Drawing.Color.White;
            this.logOut.onHoverState.BorderRadius = 1;
            this.logOut.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.logOut.onHoverState.BorderThickness = 1;
            this.logOut.onHoverState.FillColor = System.Drawing.Color.White;
            this.logOut.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(125)))), ((int)(((byte)(250)))));
            this.logOut.onHoverState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("resource.IconLeftImage")));
            this.logOut.onHoverState.IconRightImage = null;
            this.logOut.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.logOut.OnIdleState.BorderRadius = 1;
            this.logOut.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.logOut.OnIdleState.BorderThickness = 1;
            this.logOut.OnIdleState.FillColor = System.Drawing.Color.White;
            this.logOut.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(223)))), ((int)(((byte)(230)))), ((int)(((byte)(241)))));
            this.logOut.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton21.OnIdleState.IconLeftImage")));
            this.logOut.OnIdleState.IconRightImage = null;
            this.logOut.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.logOut.OnPressedState.BorderRadius = 1;
            this.logOut.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.logOut.OnPressedState.BorderThickness = 1;
            this.logOut.OnPressedState.FillColor = System.Drawing.Color.White;
            this.logOut.OnPressedState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(125)))), ((int)(((byte)(250)))));
            this.logOut.OnPressedState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("resource.IconLeftImage1")));
            this.logOut.OnPressedState.IconRightImage = null;
            this.logOut.Size = new System.Drawing.Size(109, 43);
            this.logOut.TabIndex = 26;
            this.logOut.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.logOut.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.logOut.TextMarginLeft = 0;
            this.logOut.TextPadding = new System.Windows.Forms.Padding(0);
            this.logOut.UseDefaultRadiusAndThickness = true;
            this.logOut.Click += new System.EventHandler(this.logOut_Click);
            // 
            // indicatorLine
            // 
            this.indicatorLine.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(125)))), ((int)(((byte)(250)))));
            this.indicatorLine.Location = new System.Drawing.Point(-36, 228);
            this.indicatorLine.Name = "indicatorLine";
            this.indicatorLine.Size = new System.Drawing.Size(48, 48);
            this.indicatorLine.TabIndex = 14;
            this.indicatorLine.TabStop = false;
            // 
            // lienheBtn
            // 
            this.lienheBtn.AllowAnimations = true;
            this.lienheBtn.AllowMouseEffects = true;
            this.lienheBtn.AllowToggling = false;
            this.lienheBtn.AnimationSpeed = 300;
            this.lienheBtn.AutoGenerateColors = false;
            this.lienheBtn.AutoRoundBorders = false;
            this.lienheBtn.AutoSizeLeftIcon = true;
            this.lienheBtn.AutoSizeRightIcon = true;
            this.lienheBtn.BackColor = System.Drawing.Color.Transparent;
            this.lienheBtn.BackColor1 = System.Drawing.Color.White;
            this.lienheBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("lienheBtn.BackgroundImage")));
            this.lienheBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.lienheBtn.ButtonText = "";
            this.lienheBtn.ButtonTextMarginLeft = 0;
            this.lienheBtn.ColorContrastOnClick = 45;
            this.lienheBtn.ColorContrastOnHover = 45;
            this.lienheBtn.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.lienheBtn.CustomizableEdges = borderEdges2;
            this.lienheBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.lienheBtn.DisabledBorderColor = System.Drawing.Color.Empty;
            this.lienheBtn.DisabledFillColor = System.Drawing.Color.White;
            this.lienheBtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.lienheBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.lienheBtn.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.lienheBtn.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(223)))), ((int)(((byte)(230)))), ((int)(((byte)(241)))));
            this.lienheBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.lienheBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.lienheBtn.IconLeftPadding = new System.Windows.Forms.Padding(3);
            this.lienheBtn.IconMarginLeft = 11;
            this.lienheBtn.IconPadding = 10;
            this.lienheBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.lienheBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.lienheBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.lienheBtn.IconSize = 25;
            this.lienheBtn.IdleBorderColor = System.Drawing.Color.White;
            this.lienheBtn.IdleBorderRadius = 1;
            this.lienheBtn.IdleBorderThickness = 1;
            this.lienheBtn.IdleFillColor = System.Drawing.Color.White;
            this.lienheBtn.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("lienheBtn.IdleIconLeftImage")));
            this.lienheBtn.IdleIconRightImage = null;
            this.lienheBtn.ImeMode = System.Windows.Forms.ImeMode.NoControl;
            this.lienheBtn.IndicateFocus = false;
            this.lienheBtn.Location = new System.Drawing.Point(0, 607);
            this.lienheBtn.Name = "lienheBtn";
            this.lienheBtn.OnDisabledState.BorderColor = System.Drawing.Color.Empty;
            this.lienheBtn.OnDisabledState.BorderRadius = 1;
            this.lienheBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.lienheBtn.OnDisabledState.BorderThickness = 1;
            this.lienheBtn.OnDisabledState.FillColor = System.Drawing.Color.White;
            this.lienheBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.lienheBtn.OnDisabledState.IconLeftImage = null;
            this.lienheBtn.OnDisabledState.IconRightImage = null;
            this.lienheBtn.onHoverState.BorderColor = System.Drawing.Color.White;
            this.lienheBtn.onHoverState.BorderRadius = 1;
            this.lienheBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.lienheBtn.onHoverState.BorderThickness = 1;
            this.lienheBtn.onHoverState.FillColor = System.Drawing.Color.White;
            this.lienheBtn.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(125)))), ((int)(((byte)(250)))));
            this.lienheBtn.onHoverState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("resource.IconLeftImage2")));
            this.lienheBtn.onHoverState.IconRightImage = null;
            this.lienheBtn.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.lienheBtn.OnIdleState.BorderRadius = 1;
            this.lienheBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.lienheBtn.OnIdleState.BorderThickness = 1;
            this.lienheBtn.OnIdleState.FillColor = System.Drawing.Color.White;
            this.lienheBtn.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(223)))), ((int)(((byte)(230)))), ((int)(((byte)(241)))));
            this.lienheBtn.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("lienheBtn.OnIdleState.IconLeftImage")));
            this.lienheBtn.OnIdleState.IconRightImage = null;
            this.lienheBtn.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.lienheBtn.OnPressedState.BorderRadius = 1;
            this.lienheBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.lienheBtn.OnPressedState.BorderThickness = 1;
            this.lienheBtn.OnPressedState.FillColor = System.Drawing.Color.White;
            this.lienheBtn.OnPressedState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(125)))), ((int)(((byte)(250)))));
            this.lienheBtn.OnPressedState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("resource.IconLeftImage3")));
            this.lienheBtn.OnPressedState.IconRightImage = null;
            this.lienheBtn.Size = new System.Drawing.Size(112, 43);
            this.lienheBtn.TabIndex = 24;
            this.lienheBtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.lienheBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.lienheBtn.TextMarginLeft = 0;
            this.lienheBtn.TextPadding = new System.Windows.Forms.Padding(0);
            this.lienheBtn.UseDefaultRadiusAndThickness = true;
            this.lienheBtn.Click += new System.EventHandler(this.lienheBtn_Click);
            // 
            // trangchuBtn
            // 
            this.trangchuBtn.AllowAnimations = true;
            this.trangchuBtn.AllowMouseEffects = true;
            this.trangchuBtn.AllowToggling = false;
            this.trangchuBtn.AnimationSpeed = 300;
            this.trangchuBtn.AutoGenerateColors = false;
            this.trangchuBtn.AutoRoundBorders = false;
            this.trangchuBtn.AutoSizeLeftIcon = true;
            this.trangchuBtn.AutoSizeRightIcon = true;
            this.trangchuBtn.BackColor = System.Drawing.Color.Transparent;
            this.trangchuBtn.BackColor1 = System.Drawing.Color.White;
            this.trangchuBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("trangchuBtn.BackgroundImage")));
            this.trangchuBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.trangchuBtn.ButtonText = "";
            this.trangchuBtn.ButtonTextMarginLeft = 0;
            this.trangchuBtn.ColorContrastOnClick = 45;
            this.trangchuBtn.ColorContrastOnHover = 45;
            this.trangchuBtn.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.trangchuBtn.CustomizableEdges = borderEdges3;
            this.trangchuBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.trangchuBtn.DisabledBorderColor = System.Drawing.Color.Empty;
            this.trangchuBtn.DisabledFillColor = System.Drawing.Color.White;
            this.trangchuBtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.trangchuBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.trangchuBtn.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.trangchuBtn.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(223)))), ((int)(((byte)(230)))), ((int)(((byte)(241)))));
            this.trangchuBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.trangchuBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.trangchuBtn.IconLeftPadding = new System.Windows.Forms.Padding(3);
            this.trangchuBtn.IconMarginLeft = 11;
            this.trangchuBtn.IconPadding = 10;
            this.trangchuBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.trangchuBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.trangchuBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.trangchuBtn.IconSize = 25;
            this.trangchuBtn.IdleBorderColor = System.Drawing.Color.White;
            this.trangchuBtn.IdleBorderRadius = 1;
            this.trangchuBtn.IdleBorderThickness = 1;
            this.trangchuBtn.IdleFillColor = System.Drawing.Color.White;
            this.trangchuBtn.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("trangchuBtn.IdleIconLeftImage")));
            this.trangchuBtn.IdleIconRightImage = null;
            this.trangchuBtn.ImeMode = System.Windows.Forms.ImeMode.NoControl;
            this.trangchuBtn.IndicateFocus = false;
            this.trangchuBtn.Location = new System.Drawing.Point(0, 233);
            this.trangchuBtn.Name = "trangchuBtn";
            this.trangchuBtn.OnDisabledState.BorderColor = System.Drawing.Color.Empty;
            this.trangchuBtn.OnDisabledState.BorderRadius = 1;
            this.trangchuBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.trangchuBtn.OnDisabledState.BorderThickness = 1;
            this.trangchuBtn.OnDisabledState.FillColor = System.Drawing.Color.White;
            this.trangchuBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.trangchuBtn.OnDisabledState.IconLeftImage = null;
            this.trangchuBtn.OnDisabledState.IconRightImage = null;
            this.trangchuBtn.onHoverState.BorderColor = System.Drawing.Color.White;
            this.trangchuBtn.onHoverState.BorderRadius = 1;
            this.trangchuBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.trangchuBtn.onHoverState.BorderThickness = 1;
            this.trangchuBtn.onHoverState.FillColor = System.Drawing.Color.White;
            this.trangchuBtn.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(125)))), ((int)(((byte)(250)))));
            this.trangchuBtn.onHoverState.IconLeftImage = global::BTL.Properties.Resources.home_color;
            this.trangchuBtn.onHoverState.IconRightImage = null;
            this.trangchuBtn.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.trangchuBtn.OnIdleState.BorderRadius = 1;
            this.trangchuBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.trangchuBtn.OnIdleState.BorderThickness = 1;
            this.trangchuBtn.OnIdleState.FillColor = System.Drawing.Color.White;
            this.trangchuBtn.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(223)))), ((int)(((byte)(230)))), ((int)(((byte)(241)))));
            this.trangchuBtn.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("trangchuBtn.OnIdleState.IconLeftImage")));
            this.trangchuBtn.OnIdleState.IconRightImage = null;
            this.trangchuBtn.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.trangchuBtn.OnPressedState.BorderRadius = 1;
            this.trangchuBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.trangchuBtn.OnPressedState.BorderThickness = 1;
            this.trangchuBtn.OnPressedState.FillColor = System.Drawing.Color.White;
            this.trangchuBtn.OnPressedState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(125)))), ((int)(((byte)(250)))));
            this.trangchuBtn.OnPressedState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("resource.IconLeftImage4")));
            this.trangchuBtn.OnPressedState.IconRightImage = null;
            this.trangchuBtn.Size = new System.Drawing.Size(112, 43);
            this.trangchuBtn.TabIndex = 19;
            this.trangchuBtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.trangchuBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.trangchuBtn.TextMarginLeft = 0;
            this.trangchuBtn.TextPadding = new System.Windows.Forms.Padding(0);
            this.trangchuBtn.UseDefaultRadiusAndThickness = true;
            this.trangchuBtn.Click += new System.EventHandler(this.trangchuBtn_Click);
            // 
            // hanghoaBtn
            // 
            this.hanghoaBtn.AllowAnimations = true;
            this.hanghoaBtn.AllowMouseEffects = true;
            this.hanghoaBtn.AllowToggling = false;
            this.hanghoaBtn.AnimationSpeed = 300;
            this.hanghoaBtn.AutoGenerateColors = false;
            this.hanghoaBtn.AutoRoundBorders = false;
            this.hanghoaBtn.AutoSizeLeftIcon = true;
            this.hanghoaBtn.AutoSizeRightIcon = true;
            this.hanghoaBtn.BackColor = System.Drawing.Color.Transparent;
            this.hanghoaBtn.BackColor1 = System.Drawing.Color.White;
            this.hanghoaBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("hanghoaBtn.BackgroundImage")));
            this.hanghoaBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.hanghoaBtn.ButtonText = "";
            this.hanghoaBtn.ButtonTextMarginLeft = 0;
            this.hanghoaBtn.ColorContrastOnClick = 45;
            this.hanghoaBtn.ColorContrastOnHover = 45;
            this.hanghoaBtn.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.hanghoaBtn.CustomizableEdges = borderEdges4;
            this.hanghoaBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.hanghoaBtn.DisabledBorderColor = System.Drawing.Color.Empty;
            this.hanghoaBtn.DisabledFillColor = System.Drawing.Color.White;
            this.hanghoaBtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.hanghoaBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.hanghoaBtn.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.hanghoaBtn.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(223)))), ((int)(((byte)(230)))), ((int)(((byte)(241)))));
            this.hanghoaBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.hanghoaBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.hanghoaBtn.IconLeftPadding = new System.Windows.Forms.Padding(3);
            this.hanghoaBtn.IconMarginLeft = 11;
            this.hanghoaBtn.IconPadding = 10;
            this.hanghoaBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.hanghoaBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.hanghoaBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.hanghoaBtn.IconSize = 25;
            this.hanghoaBtn.IdleBorderColor = System.Drawing.Color.White;
            this.hanghoaBtn.IdleBorderRadius = 1;
            this.hanghoaBtn.IdleBorderThickness = 1;
            this.hanghoaBtn.IdleFillColor = System.Drawing.Color.White;
            this.hanghoaBtn.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("hanghoaBtn.IdleIconLeftImage")));
            this.hanghoaBtn.IdleIconRightImage = null;
            this.hanghoaBtn.ImeMode = System.Windows.Forms.ImeMode.NoControl;
            this.hanghoaBtn.IndicateFocus = false;
            this.hanghoaBtn.Location = new System.Drawing.Point(0, 300);
            this.hanghoaBtn.Name = "hanghoaBtn";
            this.hanghoaBtn.OnDisabledState.BorderColor = System.Drawing.Color.Empty;
            this.hanghoaBtn.OnDisabledState.BorderRadius = 1;
            this.hanghoaBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.hanghoaBtn.OnDisabledState.BorderThickness = 1;
            this.hanghoaBtn.OnDisabledState.FillColor = System.Drawing.Color.White;
            this.hanghoaBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.hanghoaBtn.OnDisabledState.IconLeftImage = null;
            this.hanghoaBtn.OnDisabledState.IconRightImage = null;
            this.hanghoaBtn.onHoverState.BorderColor = System.Drawing.Color.White;
            this.hanghoaBtn.onHoverState.BorderRadius = 1;
            this.hanghoaBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.hanghoaBtn.onHoverState.BorderThickness = 1;
            this.hanghoaBtn.onHoverState.FillColor = System.Drawing.Color.White;
            this.hanghoaBtn.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(125)))), ((int)(((byte)(250)))));
            this.hanghoaBtn.onHoverState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("resource.IconLeftImage5")));
            this.hanghoaBtn.onHoverState.IconRightImage = null;
            this.hanghoaBtn.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.hanghoaBtn.OnIdleState.BorderRadius = 1;
            this.hanghoaBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.hanghoaBtn.OnIdleState.BorderThickness = 1;
            this.hanghoaBtn.OnIdleState.FillColor = System.Drawing.Color.White;
            this.hanghoaBtn.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(223)))), ((int)(((byte)(230)))), ((int)(((byte)(241)))));
            this.hanghoaBtn.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("hanghoaBtn.OnIdleState.IconLeftImage")));
            this.hanghoaBtn.OnIdleState.IconRightImage = null;
            this.hanghoaBtn.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.hanghoaBtn.OnPressedState.BorderRadius = 1;
            this.hanghoaBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.hanghoaBtn.OnPressedState.BorderThickness = 1;
            this.hanghoaBtn.OnPressedState.FillColor = System.Drawing.Color.White;
            this.hanghoaBtn.OnPressedState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(125)))), ((int)(((byte)(250)))));
            this.hanghoaBtn.OnPressedState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("resource.IconLeftImage6")));
            this.hanghoaBtn.OnPressedState.IconRightImage = null;
            this.hanghoaBtn.Size = new System.Drawing.Size(112, 43);
            this.hanghoaBtn.TabIndex = 20;
            this.hanghoaBtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.hanghoaBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.hanghoaBtn.TextMarginLeft = 0;
            this.hanghoaBtn.TextPadding = new System.Windows.Forms.Padding(0);
            this.hanghoaBtn.UseDefaultRadiusAndThickness = true;
            this.hanghoaBtn.Click += new System.EventHandler(this.hanghoaBtn_Click);
            // 
            // hoadonBtn
            // 
            this.hoadonBtn.AllowAnimations = true;
            this.hoadonBtn.AllowMouseEffects = true;
            this.hoadonBtn.AllowToggling = false;
            this.hoadonBtn.AnimationSpeed = 300;
            this.hoadonBtn.AutoGenerateColors = false;
            this.hoadonBtn.AutoRoundBorders = false;
            this.hoadonBtn.AutoSizeLeftIcon = true;
            this.hoadonBtn.AutoSizeRightIcon = true;
            this.hoadonBtn.BackColor = System.Drawing.Color.Transparent;
            this.hoadonBtn.BackColor1 = System.Drawing.Color.White;
            this.hoadonBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("hoadonBtn.BackgroundImage")));
            this.hoadonBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.hoadonBtn.ButtonText = "";
            this.hoadonBtn.ButtonTextMarginLeft = 0;
            this.hoadonBtn.ColorContrastOnClick = 45;
            this.hoadonBtn.ColorContrastOnHover = 45;
            this.hoadonBtn.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.hoadonBtn.CustomizableEdges = borderEdges5;
            this.hoadonBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.hoadonBtn.DisabledBorderColor = System.Drawing.Color.Empty;
            this.hoadonBtn.DisabledFillColor = System.Drawing.Color.White;
            this.hoadonBtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.hoadonBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.hoadonBtn.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.hoadonBtn.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(223)))), ((int)(((byte)(230)))), ((int)(((byte)(241)))));
            this.hoadonBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.hoadonBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.hoadonBtn.IconLeftPadding = new System.Windows.Forms.Padding(3);
            this.hoadonBtn.IconMarginLeft = 11;
            this.hoadonBtn.IconPadding = 10;
            this.hoadonBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.hoadonBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.hoadonBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.hoadonBtn.IconSize = 25;
            this.hoadonBtn.IdleBorderColor = System.Drawing.Color.White;
            this.hoadonBtn.IdleBorderRadius = 1;
            this.hoadonBtn.IdleBorderThickness = 1;
            this.hoadonBtn.IdleFillColor = System.Drawing.Color.White;
            this.hoadonBtn.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("hoadonBtn.IdleIconLeftImage")));
            this.hoadonBtn.IdleIconRightImage = null;
            this.hoadonBtn.ImeMode = System.Windows.Forms.ImeMode.NoControl;
            this.hoadonBtn.IndicateFocus = false;
            this.hoadonBtn.Location = new System.Drawing.Point(0, 532);
            this.hoadonBtn.Name = "hoadonBtn";
            this.hoadonBtn.OnDisabledState.BorderColor = System.Drawing.Color.Empty;
            this.hoadonBtn.OnDisabledState.BorderRadius = 1;
            this.hoadonBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.hoadonBtn.OnDisabledState.BorderThickness = 1;
            this.hoadonBtn.OnDisabledState.FillColor = System.Drawing.Color.White;
            this.hoadonBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.hoadonBtn.OnDisabledState.IconLeftImage = null;
            this.hoadonBtn.OnDisabledState.IconRightImage = null;
            this.hoadonBtn.onHoverState.BorderColor = System.Drawing.Color.White;
            this.hoadonBtn.onHoverState.BorderRadius = 1;
            this.hoadonBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.hoadonBtn.onHoverState.BorderThickness = 1;
            this.hoadonBtn.onHoverState.FillColor = System.Drawing.Color.White;
            this.hoadonBtn.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(125)))), ((int)(((byte)(250)))));
            this.hoadonBtn.onHoverState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("resource.IconLeftImage7")));
            this.hoadonBtn.onHoverState.IconRightImage = null;
            this.hoadonBtn.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.hoadonBtn.OnIdleState.BorderRadius = 1;
            this.hoadonBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.hoadonBtn.OnIdleState.BorderThickness = 1;
            this.hoadonBtn.OnIdleState.FillColor = System.Drawing.Color.White;
            this.hoadonBtn.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(223)))), ((int)(((byte)(230)))), ((int)(((byte)(241)))));
            this.hoadonBtn.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("hoadonBtn.OnIdleState.IconLeftImage")));
            this.hoadonBtn.OnIdleState.IconRightImage = null;
            this.hoadonBtn.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.hoadonBtn.OnPressedState.BorderRadius = 1;
            this.hoadonBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.hoadonBtn.OnPressedState.BorderThickness = 1;
            this.hoadonBtn.OnPressedState.FillColor = System.Drawing.Color.White;
            this.hoadonBtn.OnPressedState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(125)))), ((int)(((byte)(250)))));
            this.hoadonBtn.OnPressedState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("resource.IconLeftImage8")));
            this.hoadonBtn.OnPressedState.IconRightImage = null;
            this.hoadonBtn.Size = new System.Drawing.Size(112, 43);
            this.hoadonBtn.TabIndex = 23;
            this.hoadonBtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.hoadonBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.hoadonBtn.TextMarginLeft = 0;
            this.hoadonBtn.TextPadding = new System.Windows.Forms.Padding(0);
            this.hoadonBtn.UseDefaultRadiusAndThickness = true;
            this.hoadonBtn.Click += new System.EventHandler(this.hoadonBtn_Click);
            // 
            // nhanvienBtn
            // 
            this.nhanvienBtn.AllowAnimations = true;
            this.nhanvienBtn.AllowMouseEffects = true;
            this.nhanvienBtn.AllowToggling = false;
            this.nhanvienBtn.AnimationSpeed = 300;
            this.nhanvienBtn.AutoGenerateColors = false;
            this.nhanvienBtn.AutoRoundBorders = false;
            this.nhanvienBtn.AutoSizeLeftIcon = true;
            this.nhanvienBtn.AutoSizeRightIcon = true;
            this.nhanvienBtn.BackColor = System.Drawing.Color.Transparent;
            this.nhanvienBtn.BackColor1 = System.Drawing.Color.White;
            this.nhanvienBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("nhanvienBtn.BackgroundImage")));
            this.nhanvienBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.nhanvienBtn.ButtonText = "";
            this.nhanvienBtn.ButtonTextMarginLeft = 0;
            this.nhanvienBtn.ColorContrastOnClick = 45;
            this.nhanvienBtn.ColorContrastOnHover = 45;
            this.nhanvienBtn.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.nhanvienBtn.CustomizableEdges = borderEdges6;
            this.nhanvienBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.nhanvienBtn.DisabledBorderColor = System.Drawing.Color.Empty;
            this.nhanvienBtn.DisabledFillColor = System.Drawing.Color.White;
            this.nhanvienBtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.nhanvienBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.nhanvienBtn.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.nhanvienBtn.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(223)))), ((int)(((byte)(230)))), ((int)(((byte)(241)))));
            this.nhanvienBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.nhanvienBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.nhanvienBtn.IconLeftPadding = new System.Windows.Forms.Padding(3);
            this.nhanvienBtn.IconMarginLeft = 11;
            this.nhanvienBtn.IconPadding = 10;
            this.nhanvienBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.nhanvienBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.nhanvienBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.nhanvienBtn.IconSize = 25;
            this.nhanvienBtn.IdleBorderColor = System.Drawing.Color.White;
            this.nhanvienBtn.IdleBorderRadius = 1;
            this.nhanvienBtn.IdleBorderThickness = 1;
            this.nhanvienBtn.IdleFillColor = System.Drawing.Color.White;
            this.nhanvienBtn.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("nhanvienBtn.IdleIconLeftImage")));
            this.nhanvienBtn.IdleIconRightImage = null;
            this.nhanvienBtn.ImeMode = System.Windows.Forms.ImeMode.NoControl;
            this.nhanvienBtn.IndicateFocus = false;
            this.nhanvienBtn.Location = new System.Drawing.Point(-3, 376);
            this.nhanvienBtn.Name = "nhanvienBtn";
            this.nhanvienBtn.OnDisabledState.BorderColor = System.Drawing.Color.Empty;
            this.nhanvienBtn.OnDisabledState.BorderRadius = 1;
            this.nhanvienBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.nhanvienBtn.OnDisabledState.BorderThickness = 1;
            this.nhanvienBtn.OnDisabledState.FillColor = System.Drawing.Color.White;
            this.nhanvienBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.nhanvienBtn.OnDisabledState.IconLeftImage = null;
            this.nhanvienBtn.OnDisabledState.IconRightImage = null;
            this.nhanvienBtn.onHoverState.BorderColor = System.Drawing.Color.White;
            this.nhanvienBtn.onHoverState.BorderRadius = 1;
            this.nhanvienBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.nhanvienBtn.onHoverState.BorderThickness = 1;
            this.nhanvienBtn.onHoverState.FillColor = System.Drawing.Color.White;
            this.nhanvienBtn.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(125)))), ((int)(((byte)(250)))));
            this.nhanvienBtn.onHoverState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("resource.IconLeftImage9")));
            this.nhanvienBtn.onHoverState.IconRightImage = null;
            this.nhanvienBtn.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.nhanvienBtn.OnIdleState.BorderRadius = 1;
            this.nhanvienBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.nhanvienBtn.OnIdleState.BorderThickness = 1;
            this.nhanvienBtn.OnIdleState.FillColor = System.Drawing.Color.White;
            this.nhanvienBtn.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(223)))), ((int)(((byte)(230)))), ((int)(((byte)(241)))));
            this.nhanvienBtn.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("nhanvienBtn.OnIdleState.IconLeftImage")));
            this.nhanvienBtn.OnIdleState.IconRightImage = null;
            this.nhanvienBtn.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.nhanvienBtn.OnPressedState.BorderRadius = 1;
            this.nhanvienBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.nhanvienBtn.OnPressedState.BorderThickness = 1;
            this.nhanvienBtn.OnPressedState.FillColor = System.Drawing.Color.White;
            this.nhanvienBtn.OnPressedState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(125)))), ((int)(((byte)(250)))));
            this.nhanvienBtn.OnPressedState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("resource.IconLeftImage10")));
            this.nhanvienBtn.OnPressedState.IconRightImage = null;
            this.nhanvienBtn.Size = new System.Drawing.Size(115, 43);
            this.nhanvienBtn.TabIndex = 21;
            this.nhanvienBtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.nhanvienBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.nhanvienBtn.TextMarginLeft = 0;
            this.nhanvienBtn.TextPadding = new System.Windows.Forms.Padding(0);
            this.nhanvienBtn.UseDefaultRadiusAndThickness = true;
            this.nhanvienBtn.Click += new System.EventHandler(this.nhanvienBtn_Click);
            // 
            // khachhangBtn
            // 
            this.khachhangBtn.AllowAnimations = true;
            this.khachhangBtn.AllowMouseEffects = true;
            this.khachhangBtn.AllowToggling = false;
            this.khachhangBtn.AnimationSpeed = 300;
            this.khachhangBtn.AutoGenerateColors = false;
            this.khachhangBtn.AutoRoundBorders = false;
            this.khachhangBtn.AutoSizeLeftIcon = true;
            this.khachhangBtn.AutoSizeRightIcon = true;
            this.khachhangBtn.BackColor = System.Drawing.Color.Transparent;
            this.khachhangBtn.BackColor1 = System.Drawing.Color.White;
            this.khachhangBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("khachhangBtn.BackgroundImage")));
            this.khachhangBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.khachhangBtn.ButtonText = "";
            this.khachhangBtn.ButtonTextMarginLeft = 0;
            this.khachhangBtn.ColorContrastOnClick = 45;
            this.khachhangBtn.ColorContrastOnHover = 45;
            this.khachhangBtn.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges7.BottomLeft = true;
            borderEdges7.BottomRight = true;
            borderEdges7.TopLeft = true;
            borderEdges7.TopRight = true;
            this.khachhangBtn.CustomizableEdges = borderEdges7;
            this.khachhangBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.khachhangBtn.DisabledBorderColor = System.Drawing.Color.Empty;
            this.khachhangBtn.DisabledFillColor = System.Drawing.Color.White;
            this.khachhangBtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.khachhangBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.khachhangBtn.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.khachhangBtn.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(223)))), ((int)(((byte)(230)))), ((int)(((byte)(241)))));
            this.khachhangBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.khachhangBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.khachhangBtn.IconLeftPadding = new System.Windows.Forms.Padding(3);
            this.khachhangBtn.IconMarginLeft = 11;
            this.khachhangBtn.IconPadding = 10;
            this.khachhangBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.khachhangBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.khachhangBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.khachhangBtn.IconSize = 25;
            this.khachhangBtn.IdleBorderColor = System.Drawing.Color.White;
            this.khachhangBtn.IdleBorderRadius = 1;
            this.khachhangBtn.IdleBorderThickness = 1;
            this.khachhangBtn.IdleFillColor = System.Drawing.Color.White;
            this.khachhangBtn.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("khachhangBtn.IdleIconLeftImage")));
            this.khachhangBtn.IdleIconRightImage = null;
            this.khachhangBtn.ImeMode = System.Windows.Forms.ImeMode.NoControl;
            this.khachhangBtn.IndicateFocus = false;
            this.khachhangBtn.Location = new System.Drawing.Point(0, 450);
            this.khachhangBtn.Name = "khachhangBtn";
            this.khachhangBtn.OnDisabledState.BorderColor = System.Drawing.Color.Empty;
            this.khachhangBtn.OnDisabledState.BorderRadius = 1;
            this.khachhangBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.khachhangBtn.OnDisabledState.BorderThickness = 1;
            this.khachhangBtn.OnDisabledState.FillColor = System.Drawing.Color.White;
            this.khachhangBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.khachhangBtn.OnDisabledState.IconLeftImage = null;
            this.khachhangBtn.OnDisabledState.IconRightImage = null;
            this.khachhangBtn.onHoverState.BorderColor = System.Drawing.Color.White;
            this.khachhangBtn.onHoverState.BorderRadius = 1;
            this.khachhangBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.khachhangBtn.onHoverState.BorderThickness = 1;
            this.khachhangBtn.onHoverState.FillColor = System.Drawing.Color.White;
            this.khachhangBtn.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(125)))), ((int)(((byte)(250)))));
            this.khachhangBtn.onHoverState.IconLeftImage = global::BTL.Properties.Resources.khachhang_color;
            this.khachhangBtn.onHoverState.IconRightImage = null;
            this.khachhangBtn.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.khachhangBtn.OnIdleState.BorderRadius = 1;
            this.khachhangBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.khachhangBtn.OnIdleState.BorderThickness = 1;
            this.khachhangBtn.OnIdleState.FillColor = System.Drawing.Color.White;
            this.khachhangBtn.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(223)))), ((int)(((byte)(230)))), ((int)(((byte)(241)))));
            this.khachhangBtn.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("khachhangBtn.OnIdleState.IconLeftImage")));
            this.khachhangBtn.OnIdleState.IconRightImage = null;
            this.khachhangBtn.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.khachhangBtn.OnPressedState.BorderRadius = 1;
            this.khachhangBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.khachhangBtn.OnPressedState.BorderThickness = 1;
            this.khachhangBtn.OnPressedState.FillColor = System.Drawing.Color.White;
            this.khachhangBtn.OnPressedState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(125)))), ((int)(((byte)(250)))));
            this.khachhangBtn.OnPressedState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("resource.IconLeftImage11")));
            this.khachhangBtn.OnPressedState.IconRightImage = null;
            this.khachhangBtn.Size = new System.Drawing.Size(112, 43);
            this.khachhangBtn.TabIndex = 22;
            this.khachhangBtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.khachhangBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.khachhangBtn.TextMarginLeft = 0;
            this.khachhangBtn.TextPadding = new System.Windows.Forms.Padding(0);
            this.khachhangBtn.UseDefaultRadiusAndThickness = true;
            this.khachhangBtn.Click += new System.EventHandler(this.khachhangBtn_Click);
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.BackColor = System.Drawing.Color.White;
            this.bunifuLabel1.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.Font = new System.Drawing.Font("Segoe UI Semibold", 10F, System.Drawing.FontStyle.Bold);
            this.bunifuLabel1.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(79)))), ((int)(((byte)(79)))), ((int)(((byte)(79)))));
            this.bunifuLabel1.Location = new System.Drawing.Point(1113, 26);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(64, 23);
            this.bunifuLabel1.TabIndex = 12;
            this.bunifuLabel1.Text = "Việt Bảo";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // adminJob
            // 
            this.adminJob.AllowParentOverrides = false;
            this.adminJob.AutoEllipsis = false;
            this.adminJob.BackColor = System.Drawing.Color.White;
            this.adminJob.CursorType = null;
            this.adminJob.Font = new System.Drawing.Font("Segoe UI", 7.8F);
            this.adminJob.ForeColor = System.Drawing.Color.Silver;
            this.adminJob.Location = new System.Drawing.Point(1113, 50);
            this.adminJob.Name = "adminJob";
            this.adminJob.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.adminJob.Size = new System.Drawing.Size(79, 17);
            this.adminJob.TabIndex = 13;
            this.adminJob.Text = "Quản Trị Viên";
            this.adminJob.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.adminJob.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // adminAvt
            // 
            this.adminAvt.AllowAnimations = true;
            this.adminAvt.AllowBorderColorChanges = true;
            this.adminAvt.AllowMouseEffects = true;
            this.adminAvt.AnimationSpeed = 200;
            this.adminAvt.BackColor = System.Drawing.Color.Transparent;
            this.adminAvt.BackgroundColor = System.Drawing.Color.White;
            this.adminAvt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("adminAvt.BackgroundImage")));
            this.adminAvt.BorderColor = System.Drawing.Color.White;
            this.adminAvt.BorderRadius = 1;
            this.adminAvt.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuIconButton.BorderStyles.Solid;
            this.adminAvt.BorderThickness = 0;
            this.adminAvt.ColorContrastOnClick = 30;
            this.adminAvt.ColorContrastOnHover = 30;
            this.adminAvt.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges8.BottomLeft = true;
            borderEdges8.BottomRight = true;
            borderEdges8.TopLeft = true;
            borderEdges8.TopRight = true;
            this.adminAvt.CustomizableEdges = borderEdges8;
            this.adminAvt.DialogResult = System.Windows.Forms.DialogResult.None;
            this.adminAvt.Enabled = false;
            this.adminAvt.Image = ((System.Drawing.Image)(resources.GetObject("adminAvt.Image")));
            this.adminAvt.ImageMargin = new System.Windows.Forms.Padding(0);
            this.adminAvt.Location = new System.Drawing.Point(1052, 26);
            this.adminAvt.Name = "adminAvt";
            this.adminAvt.RoundBorders = false;
            this.adminAvt.ShowBorders = true;
            this.adminAvt.Size = new System.Drawing.Size(41, 41);
            this.adminAvt.Style = Bunifu.UI.WinForms.BunifuButton.BunifuIconButton.ButtonStyles.Flat;
            this.adminAvt.TabIndex = 15;
            // 
            // MainForm
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 17F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.SystemColors.Window;
            this.ClientSize = new System.Drawing.Size(1271, 830);
            this.Controls.Add(this.adminAvt);
            this.Controls.Add(this.adminJob);
            this.Controls.Add(this.bunifuLabel1);
            this.Controls.Add(this.bunifuShadowPanel1);
            this.Font = new System.Drawing.Font("Segoe UI", 7.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.IsMdiContainer = true;
            this.Name = "MainForm";
            this.Text = "Home";
            this.Load += new System.EventHandler(this.MainForm_Load);
            this.bunifuShadowPanel1.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.indicatorLine)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion
        private Bunifu.UI.WinForms.BunifuShadowPanel bunifuShadowPanel1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 lienheBtn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 trangchuBtn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 hanghoaBtn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 hoadonBtn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 nhanvienBtn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 khachhangBtn;
        private System.Windows.Forms.PictureBox indicatorLine;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private Bunifu.UI.WinForms.BunifuLabel adminJob;
        private Bunifu.UI.WinForms.BunifuButton.BunifuIconButton adminAvt;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 logOut;
    }
}